import {HttpError,hashRequestIp,normalizeEmail,nowIso,randomToken,sha256,uuid} from './core.js';

const decoder=new TextDecoder();
function base64UrlBytes(value){const normalized=String(value||'').replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(String(value||'').length/4)*4,'=');const binary=atob(normalized),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes}
function decodePart(value){try{return JSON.parse(decoder.decode(base64UrlBytes(value)))}catch{throw new HttpError(401,'La identidad de Cloudflare Access no es válida','invalid_access_token')}}
function accessToken(request){const header=String(request.headers.get('Cf-Access-Jwt-Assertion')||'').trim();if(header)return header;const cookie=String(request.headers.get('Cookie')||'').split(';').map(part=>part.trim()).find(part=>part.startsWith('CF_Authorization='));return cookie?decodeURIComponent(cookie.slice('CF_Authorization='.length)):''}
function teamDomain(env){const raw=String(env.CF_ACCESS_TEAM_DOMAIN||'').trim().replace(/^https?:\/\//,'').replace(/\/$/,'');if(!raw)return'';return raw.includes('.')?raw:`${raw}.cloudflareaccess.com`}
function audMatches(claim,expected){if(Array.isArray(claim))return claim.includes(expected);return String(claim||'')===expected}
async function getJwk(env,kid){const domain=teamDomain(env);if(!domain||!env.CF_ACCESS_AUD)throw new HttpError(503,'Cloudflare Access todavía no está configurado','access_not_configured');const response=await fetch(`https://${domain}/cdn-cgi/access/certs`,{cf:{cacheTtl:300,cacheEverything:true}});if(!response.ok)throw new HttpError(503,'No se pudieron validar las llaves de Cloudflare Access','access_keys_unavailable');const payload=await response.json();const keys=Array.isArray(payload.keys)?payload.keys:[];const key=keys.find(item=>String(item.kid||'')===String(kid||''));if(!key)throw new HttpError(401,'La llave de Cloudflare Access no coincide','access_key_not_found');return key}
async function verifyAccessJwt(request,env){const token=accessToken(request);if(!token)throw new HttpError(401,'Inicia sesión mediante Cloudflare Access','access_login_required');const parts=token.split('.');if(parts.length!==3)throw new HttpError(401,'Token de Cloudflare Access inválido','invalid_access_token');const header=decodePart(parts[0]),claims=decodePart(parts[1]);if(header.alg!=='RS256'||!header.kid)throw new HttpError(401,'Algoritmo de identidad no permitido','invalid_access_algorithm');const key=await getJwk(env,header.kid),cryptoKey=await crypto.subtle.importKey('jwk',key,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']),data=new TextEncoder().encode(`${parts[0]}.${parts[1]}`),signature=base64UrlBytes(parts[2]),valid=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',cryptoKey,signature,data);if(!valid)throw new HttpError(401,'La firma de Cloudflare Access no es válida','invalid_access_signature');const domain=teamDomain(env),issuer=`https://${domain}`,now=Math.floor(Date.now()/1000);if(String(claims.iss||'').replace(/\/$/,'')!==issuer)throw new HttpError(401,'Emisor de Cloudflare Access inválido','invalid_access_issuer');if(!audMatches(claims.aud,String(env.CF_ACCESS_AUD)))throw new HttpError(401,'La identidad pertenece a otra aplicación','invalid_access_audience');if(Number(claims.exp||0)<=now)throw new HttpError(401,'La sesión de Google expiró','access_token_expired');const email=normalizeEmail(claims.email||claims.sub);return{email,claims,token}}
async function createSession(env,request,row){const token=randomToken(36),tokenHash=await sha256(token),ipHash=await hashRequestIp(request,env),id=uuid(),timestamp=nowIso();await env.DB.prepare(`INSERT INTO sessions(id,user_id,org_id,token_hash,user_agent,ip_hash,created_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?)`).bind(id,row.user_id,row.org_id,tokenHash,String(request.headers.get('User-Agent')||'').slice(0,300),ipHash,timestamp,timestamp).run();return{token,sessionId:id}}
export function accessSsoStatus(env){return{configured:Boolean(teamDomain(env)&&env.CF_ACCESS_AUD),teamDomain:teamDomain(env),audienceConfigured:Boolean(env.CF_ACCESS_AUD),loginMode:teamDomain(env)&&env.CF_ACCESS_AUD?'cloudflare-access':'password'}}
export async function loginWithCloudflareAccess(request,env){const identity=await verifyAccessJwt(request,env),row=await env.DB.prepare(`SELECT u.id AS user_id,u.email,u.display_name,u.profile_json,m.id AS membership_id,m.org_id,m.role,m.location_scope,o.name AS org_name,o.slug AS org_slug,o.plan FROM users u JOIN memberships m ON m.user_id=u.id AND m.active=1 JOIN organizations o ON o.id=m.org_id AND o.status='active' WHERE u.email=? AND u.active=1 ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,o.created_at LIMIT 1`).bind(identity.email).first();if(!row)throw new HttpError(403,'Tu correo de Google aún no está habilitado en esta empresa','access_user_not_provisioned',{email:identity.email});const session=await createSession(env,request,row),timestamp=nowIso();await env.DB.prepare(`INSERT INTO audit_logs(id,org_id,actor_user_id,actor_email,action,entity_type,entity_id,metadata_json,ip_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(uuid(),row.org_id,row.user_id,row.email,'auth.cloudflare_access','session',session.sessionId,JSON.stringify({identityProvider:'google-or-access',jwtEmail:identity.email}),'',timestamp).run().catch(()=>{});return{token:session.token,sessionId:session.sessionId,user:{id:row.user_id,email:row.email,displayName:row.display_name,profile:JSON.parse(row.profile_json||'{}'),role:row.role,organizationId:row.org_id,organizationName:row.org_name,organizationSlug:row.org_slug,plan:row.plan,locationScope:JSON.parse(row.location_scope||'[]')},identity:{provider:'cloudflare-access',email:identity.email}}}
