import platformWorker from './index.js';
import {authenticate} from './auth.js';
import {corsHeaders,errorResponse,ok,securityHeaders} from './core.js';
import {ensureSchema} from './schema.js';
import {dashboard} from './api/catalog-scoped.js';
import {listProductsV14} from './api/categories-v14.js';

const EXPECTED_UNIQUE_PRODUCTS=193,EXPECTED_SUPPLIERS=12,EXPECTED_PURCHASE_FORMATS=194;
function addPlatformHeaders(response,request,env){const headers=new Headers(response.headers),origin=request.headers.get('Origin')||'';for(const[name,value]of Object.entries(corsHeaders(origin,env)))headers.set(name,value);for(const[name,value]of Object.entries(securityHeaders()))headers.set(name,value);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
async function health(env,schema){
  const[products,suppliers,purchaseFormats,owners,locations]=await Promise.all([env.DB.prepare('SELECT COUNT(*) AS total FROM products WHERE active=1').first(),env.DB.prepare('SELECT COUNT(*) AS total FROM suppliers WHERE active=1').first(),env.DB.prepare('SELECT COUNT(*) AS total FROM supplier_products WHERE active=1').first(),env.DB.prepare('SELECT COUNT(*) AS total FROM platform_owners').first(),env.DB.prepare('SELECT COUNT(*) AS total FROM locations WHERE active=1').first()]);
  const catalogProducts=Number(products?.total||0),catalogSuppliers=Number(suppliers?.total||0),catalogPurchaseFormats=Number(purchaseFormats?.total||0);
  return{service:'pedidos-pro-platform',version:'2.0.0-alpha.14',databaseConfigured:Boolean(env.DB),databaseInitialized:true,schemaVersion:schema.version,catalogReady:catalogProducts>=EXPECTED_UNIQUE_PRODUCTS&&catalogSuppliers>=EXPECTED_SUPPLIERS&&catalogPurchaseFormats>=EXPECTED_PURCHASE_FORMATS,catalogProducts,catalogSuppliers,catalogPurchaseFormats,catalogSourceRows:EXPECTED_PURCHASE_FORMATS,platformOwnerReady:Number(owners?.total||0)>0,activeLocations:Number(locations?.total||0),storageConfigured:Boolean(env.FILES||env.DB),storageBackend:env.FILES?'r2':'d1-chunks',r2Configured:Boolean(env.FILES),aiEndpoint:Boolean(env.AI_ENDPOINT),geminiConfigured:Boolean(env.GEMINI_API_KEY),orderCore:true,simpleWorkflow:true,editableOrderFiles:true,batchEmission:true,categoryOwnership:true,categoryCostCenters:true,productCenterCategories:true,fastNavigation:true,professionalDashboard:true,supplierLogos:true,perSupplierDeliveryDates:true,directPdfActions:true,cleanSupplierPdf:true,professionalReconciliation:true,notifications:true,observability:true,workspaceBackups:true,commercialReadiness:true,deviceQa:true,environment:env.ENVIRONMENT||'development',timestamp:new Date().toISOString()};
}
export default{async fetch(request,env,ctx){const url=new URL(request.url),method=request.method.toUpperCase(),scopedHealth=method==='GET'&&url.pathname==='/health',scopedDashboard=method==='GET'&&url.pathname==='/api/dashboard',scopedProducts=method==='GET'&&url.pathname==='/api/products';if(!scopedHealth&&!scopedDashboard&&!scopedProducts)return platformWorker.fetch(request,env,ctx);try{const schema=await ensureSchema(env);if(scopedHealth)return addPlatformHeaders(ok(await health(env,schema),request,env),request,env);const actor=await authenticate(request,env),payload=scopedDashboard?await dashboard(env,actor):{products:await listProductsV14(env,actor,url)};return addPlatformHeaders(ok(payload,request,env),request,env)}catch(error){if(Number(error?.status||500)>=500)console.error('scoped_request_failed',error);return addPlatformHeaders(errorResponse(error,request,env),request,env)}}};
