import platformWorker from './index-v20.js';
import {authenticate} from './auth.js';
import {corsHeaders,errorResponse,ok,securityHeaders} from './core.js';
import {ensureSchema} from './schema.js';
import {ensureNuvastoBrandV21,getNuvastoBrandV21,NUVASTO,saveNuvastoBrandV21} from './api/brand-v21.js';

function addHeaders(response,request,env){const headers=new Headers(response.headers),origin=request.headers.get('Origin')||'';for(const[name,value]of Object.entries(corsHeaders(origin,env)))headers.set(name,value);for(const[name,value]of Object.entries(securityHeaders()))headers.set(name,value);headers.set('X-Nuvasto-Version','21');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
async function health(request,env,ctx){const response=await platformWorker.fetch(request,env,ctx);if(!response.ok)return addHeaders(response,request,env);const payload=await response.clone().json().catch(()=>({}));return addHeaders(ok({...payload,service:'nuvasto',productName:NUVASTO.productName,productTagline:NUVASTO.tagline,version:'2.0.0-alpha.21',schemaTarget:21,nuvastoBrand:true,nuvastoIdentityAssets:true},request,env),request,env)}
export default{async fetch(request,env,ctx){const url=new URL(request.url),method=request.method.toUpperCase(),path=url.pathname;if(method==='GET'&&path==='/health')return health(request,env,ctx);try{if(path==='/api/professional/brand'){await ensureSchema(env);const actor=await authenticate(request,env);const brand=method==='PUT'?await saveNuvastoBrandV21(request,env,actor):await getNuvastoBrandV21(env,actor);return addHeaders(ok({brand},request,env),request,env)}if(path==='/api/professional'||path.startsWith('/api/professional/')){await ensureSchema(env);const actor=await authenticate(request,env);await ensureNuvastoBrandV21(env,actor)}return addHeaders(await platformWorker.fetch(request,env,ctx),request,env)}catch(error){if(Number(error?.status||500)>=500)console.error('nuvasto_v21_request_failed',error);return addHeaders(errorResponse(error,request,env),request,env)}}};
