import {corsHeaders,errorResponse,HttpError,ok,routeMatch,securityHeaders} from './core.js';
import {ensureSchema} from './schema.js';
import {authenticate,bootstrap,createUser,listSessions,listUsers,login,logout,me,resetPassword as changePassword,revokeSession,updateUser,updateUserProfile} from './auth.js';
import {createCategory,createCostCenter,createLocation,createProduct,createSupplier,dashboard,linkSupplierProduct,listCostCenters,listLocations,listProducts,listSuppliers,setProductCostCenters} from './api/catalog.js';
import {createOrder,getOrder,transitionOrder,updateOrder} from './api/orders.js';
import {setProductCategoryV13} from './api/catalog-v13.js';
import {createReceptionV13} from './api/reception-v13.js';
import {listOrdersV2} from './api/orders-list-v2.js';
import {createOrderBatch} from './api/order-batches.js';
import {createOrderFileV4,ensureOrderPdfV4} from './api/order-core-v4.js';
import {listOrderInvoicesV3} from './api/order-core-v3.js';
import {importCatalog,listSupplierAssets,updateSupplierIdentity} from './api/catalog-admin.js';
import {getDashboardAnalytics} from './api/analytics.js';
import {getGeminiDashboardInsights} from './api/analytics-ai.js';
import {analyzeInvoice,auditLog,getFile,listInvoices,uploadFile} from './api/documents.js';
import {createInvoiceV2} from './api/invoices-v2.js';
import {getSettings,updateSettings} from './api/settings.js';
import {createBrand,listBrands,switchBrand} from './platform.js';
import {listDocuments} from './storage.js';
import {emitOrderBatchV13,exportWorkspaceV13,getAccountReadinessV13,getDiagnosticsV13,getReconciliationSettingsV13,listNotificationsV13,listUserCategoriesV13,quickUpdateOrderV13,recordClientEventV13,reorderCategoriesV13,updateCategoryV13,updateReconciliationSettingsV13} from './api/workflow-v13.js';
import {acknowledgePriceAlertV15,addReceptionQualityV15,billingStateV15,billingWebhookV15,createBackupV15,createCheckoutV15,deleteAutosaveV15,deleteOrderToTrashV15,dispatchNotificationsV15,duplicateOrderV15,executiveExportV15,getAutosaveV15,getDashboardLayoutV15,listAliasesV15,listBackupsV15,listBudgetsV15,listPriceAlertsV15,listReceptionQualityV15,listTrashV15,migrateFilesToR2V15,monitoringSummaryV15,notificationSettingsV15,productPriceHistoryV15,purgeTrashV15,queueNotificationV15,restoreBackupV15,restoreTrashV15,reviewInvoiceLineV15,saveAutosaveV15,saveDashboardLayoutV15,threeWayReconciliationV15,updateNotificationSettingsV15,upsertAliasV15,upsertBudgetV15} from './api/enterprise-v15.js';

const APP_VERSION='2.0.0-alpha.15';
function addPlatformHeaders(response,request,env,requestId='',startedAt=Date.now()){const headers=new Headers(response.headers),origin=request.headers.get('Origin')||'';for(const [name,value] of Object.entries(corsHeaders(origin,env)))headers.set(name,value);for(const [name,value] of Object.entries(securityHeaders()))headers.set(name,value);headers.set('X-Request-Id',requestId||crypto.randomUUID());headers.set('Server-Timing',`app;dur=${Math.max(0,Date.now()-startedAt)}`);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function preflightResponse(request,env){const origin=request.headers.get('Origin')||'';return new Response(null,{status:204,headers:{...corsHeaders(origin,env),...securityHeaders()}})}
async function applyOptionalRateLimit(env,key){if(!env.RATE_LIMITER?.limit)return;const result=await env.RATE_LIMITER.limit({key});if(!result.success)throw new HttpError(429,'Demasiadas solicitudes. Intenta nuevamente.','rate_limited')}

async function handleRequest(request,env,ctx){
  const url=new URL(request.url),path=url.pathname,method=request.method.toUpperCase();if(method==='OPTIONS')return preflightResponse(request,env);const schema=await ensureSchema(env);
  if(method==='GET'&&path==='/health')return ok({service:'pedidos-pro-platform',version:APP_VERSION,databaseConfigured:Boolean(env.DB),databaseInitialized:true,schemaVersion:schema.version,storageConfigured:Boolean(env.FILES||env.DB),storageBackend:env.FILES?'r2':'d1-chunks',r2Configured:Boolean(env.FILES),aiEndpoint:Boolean(env.AI_ENDPOINT),geminiConfigured:Boolean(env.GEMINI_API_KEY),persistentCatalog:true,persistentBranding:true,trashRestore:true,autosave:true,orderDuplication:true,costCenterBudgets:true,advancedReception:true,threeWayReconciliation:true,aliasLearning:true,priceAlerts:true,productPriceHistory:true,humanInvoiceReview:true,multichannelNotifications:true,realBilling:Boolean(env.MERCADOPAGO_ACCESS_TOKEN),backupRestore:true,r2Migration:true,commercialMonitoring:true,e2eReady:true,customDashboard:true,executiveExports:true,environment:env.ENVIRONMENT||'development',timestamp:new Date().toISOString()},request,env);
  if(method==='POST'&&path==='/api/bootstrap'){await applyOptionalRateLimit(env,`bootstrap:${request.headers.get('CF-Connecting-IP')||'unknown'}`);return ok(await bootstrap(request,env),request,env)}
  if(method==='POST'&&path==='/api/auth/login'){await applyOptionalRateLimit(env,`login:${request.headers.get('CF-Connecting-IP')||'unknown'}`);return ok(await login(request,env),request,env)}
  if(method==='POST'&&path==='/api/billing/webhook')return ok(await billingWebhookV15(request,env),request,env);
  const actor=await authenticate(request,env);await applyOptionalRateLimit(env,`user:${actor.userId}`);
  if(method==='POST'&&path==='/api/auth/logout')return ok(await logout(request,env,actor),request,env);if(method==='GET'&&path==='/api/me')return ok(await me(env,actor),request,env);if(method==='GET'&&path==='/api/dashboard')return ok(await dashboard(env,actor),request,env);if(method==='GET'&&path==='/api/dashboard/analytics')return ok({analytics:await getDashboardAnalytics(env,actor,url)},request,env);if(method==='POST'&&path==='/api/dashboard/insights')return ok(await getGeminiDashboardInsights(request,env,actor,url),request,env);if(method==='GET'&&path==='/api/dashboard/layout')return ok(await getDashboardLayoutV15(env,actor),request,env);if(method==='PUT'&&path==='/api/dashboard/layout')return ok(await saveDashboardLayoutV15(request,env,actor),request,env);if(method==='GET'&&path==='/api/settings')return ok(await getSettings(env,actor),request,env);if(method==='PATCH'&&path==='/api/settings')return ok(await updateSettings(request,env,actor),request,env);
  if(method==='GET'&&path==='/api/brands')return ok({brands:await listBrands(env,actor)},request,env);if(method==='POST'&&path==='/api/brands')return ok({brand:await createBrand(request,env,actor)},request,env);const brandParams=routeMatch(path,'/api/brands/:id/switch');if(brandParams&&method==='POST')return ok(await switchBrand(request,env,actor,brandParams.id),request,env);
  if(method==='GET'&&path==='/api/locations')return ok({locations:await listLocations(env,actor)},request,env);if(method==='POST'&&path==='/api/locations')return ok({location:await createLocation(request,env,actor)},request,env);if(method==='GET'&&path==='/api/cost-centers')return ok({costCenters:await listCostCenters(env,actor,url)},request,env);if(method==='POST'&&path==='/api/cost-centers')return ok({costCenter:await createCostCenter(request,env,actor)},request,env);if(method==='GET'&&path==='/api/budgets')return ok({budgets:await listBudgetsV15(env,actor,url)},request,env);if(method==='PUT'&&path==='/api/budgets')return ok({budget:await upsertBudgetV15(request,env,actor)},request,env);
  if(method==='GET'&&path==='/api/categories')return ok({categories:await listUserCategoriesV13(env,actor)},request,env);if(method==='POST'&&path==='/api/categories')return ok({category:await createCategory(request,env,actor)},request,env);if(method==='PUT'&&path==='/api/categories/order')return ok(await reorderCategoriesV13(request,env,actor),request,env);const categoryParams=routeMatch(path,'/api/categories/:id');if(categoryParams&&method==='PATCH')return ok({category:await updateCategoryV13(request,env,actor,categoryParams.id)},request,env);
  if(method==='GET'&&path==='/api/suppliers')return ok({suppliers:await listSuppliers(env,actor,url)},request,env);if(method==='POST'&&path==='/api/suppliers')return ok({supplier:await createSupplier(request,env,actor)},request,env);if(method==='GET'&&path==='/api/supplier-assets')return ok({assets:await listSupplierAssets(env,actor)},request,env);const supplierIdentityParams=routeMatch(path,'/api/suppliers/:id/identity');if(supplierIdentityParams&&method==='PATCH')return ok({identity:await updateSupplierIdentity(request,env,actor,supplierIdentityParams.id)},request,env);if(method==='POST'&&path==='/api/catalog/import')return ok({result:await importCatalog(request,env,actor)},request,env);
  if(method==='GET'&&path==='/api/products')return ok({products:await listProducts(env,actor,url)},request,env);if(method==='POST'&&path==='/api/products')return ok({product:await createProduct(request,env,actor)},request,env);const productCategoryParams=routeMatch(path,'/api/products/:id/category');if(productCategoryParams&&method==='PATCH')return ok(await setProductCategoryV13(request,env,actor,productCategoryParams.id),request,env);const productCostCenterParams=routeMatch(path,'/api/products/:id/cost-centers');if(productCostCenterParams&&method==='PUT')return ok(await setProductCostCenters(request,env,actor,productCostCenterParams.id),request,env);const productSupplierParams=routeMatch(path,'/api/products/:id/suppliers');if(productSupplierParams&&method==='POST')return ok({supplierProduct:await linkSupplierProduct(request,env,actor,productSupplierParams.id)},request,env);const productHistoryParams=routeMatch(path,'/api/products/:id/price-history');if(productHistoryParams&&method==='GET')return ok(await productPriceHistoryV15(env,actor,productHistoryParams.id,url),request,env);
  if(method==='GET'&&path==='/api/orders')return ok({orders:await listOrdersV2(env,actor,url)},request,env);if(method==='POST'&&path==='/api/orders')return ok({order:await createOrder(request,env,actor)},request,env);if(method==='POST'&&path==='/api/order-batches')return ok({batch:await createOrderBatch(request,env,actor)},request,env);if(method==='POST'&&path==='/api/order-batches/v2')return ok({batch:await createOrderFileV4(request,env,actor)},request,env);const batchEmitParams=routeMatch(path,'/api/order-batches/:id/emit');if(batchEmitParams&&method==='POST')return ok(await emitOrderBatchV13(request,env,actor,batchEmitParams.id,ctx),request,env);const orderPdfParams=routeMatch(path,'/api/orders/:id/pdf');if(orderPdfParams&&method==='POST')return ok({document:await ensureOrderPdfV4(request,env,actor,orderPdfParams.id)},request,env);const orderInvoiceParams=routeMatch(path,'/api/orders/:id/invoices');if(orderInvoiceParams&&method==='GET')return ok({invoices:await listOrderInvoicesV3(env,actor,orderInvoiceParams.id)},request,env);const orderQuickParams=routeMatch(path,'/api/orders/:id/quick');if(orderQuickParams&&method==='PATCH')return ok({order:await quickUpdateOrderV13(request,env,actor,orderQuickParams.id)},request,env);const orderDuplicateParams=routeMatch(path,'/api/orders/:id/duplicate');if(orderDuplicateParams&&method==='POST')return ok({order:await duplicateOrderV15(request,env,actor,orderDuplicateParams.id)},request,env);const orderReconcileParams=routeMatch(path,'/api/orders/:id/reconcile-three-way');if(orderReconcileParams&&method==='GET')return ok({reconciliation:await threeWayReconciliationV15(env,actor,orderReconcileParams.id)},request,env);const orderParams=routeMatch(path,'/api/orders/:id');if(orderParams&&method==='GET')return ok({order:await getOrder(env,actor,orderParams.id)},request,env);if(orderParams&&method==='PATCH')return ok({order:await updateOrder(request,env,actor,orderParams.id)},request,env);if(orderParams&&method==='DELETE')return ok(await deleteOrderToTrashV15(request,env,actor,orderParams.id,url),request,env);const transitionParams=routeMatch(path,'/api/orders/:id/transition');if(transitionParams&&method==='POST')return ok({order:await transitionOrder(request,env,actor,transitionParams.id)},request,env);const receptionParams=routeMatch(path,'/api/orders/:id/receptions');if(receptionParams&&method==='POST')return ok({reception:await createReceptionV13(request,env,actor,receptionParams.id)},request,env);
  const receptionQualityParams=routeMatch(path,'/api/receptions/:id/quality');if(receptionQualityParams&&method==='GET')return ok({events:await listReceptionQualityV15(env,actor,receptionQualityParams.id)},request,env);if(receptionQualityParams&&method==='POST')return ok({event:await addReceptionQualityV15(request,env,actor,receptionQualityParams.id)},request,env);
  if(method==='GET'&&path==='/api/invoices')return ok({invoices:await listInvoices(env,actor,url)},request,env);if(method==='POST'&&path==='/api/invoices')return ok({invoice:await createInvoiceV2(request,env,actor)},request,env);if(method==='POST'&&path==='/api/invoices/analyze')return ok({analysis:await analyzeInvoice(request,env,actor)},request,env);const invoiceLineReviewParams=routeMatch(path,'/api/invoice-lines/:id/review');if(invoiceLineReviewParams&&method==='PATCH')return ok({line:await reviewInvoiceLineV15(request,env,actor,invoiceLineReviewParams.id)},request,env);if(method==='GET'&&path==='/api/reconciliation/settings')return ok({settings:await getReconciliationSettingsV13(env,actor)},request,env);if(method==='PATCH'&&path==='/api/reconciliation/settings')return ok({settings:await updateReconciliationSettingsV13(request,env,actor)},request,env);
  if(method==='GET'&&path==='/api/aliases')return ok({aliases:await listAliasesV15(env,actor,url)},request,env);if(method==='POST'&&path==='/api/aliases')return ok({alias:await upsertAliasV15(request,env,actor)},request,env);if(method==='GET'&&path==='/api/price-alerts')return ok({alerts:await listPriceAlertsV15(env,actor,url)},request,env);const alertParams=routeMatch(path,'/api/price-alerts/:id/ack');if(alertParams&&method==='POST')return ok({alert:await acknowledgePriceAlertV15(request,env,actor,alertParams.id)},request,env);
  if(method==='GET'&&path==='/api/documents')return ok({documents:await listDocuments(env,actor,{entityType:String(url.searchParams.get('entityType')||''),entityId:String(url.searchParams.get('entityId')||''),kind:String(url.searchParams.get('kind')||'')})},request,env);if(method==='POST'&&path==='/api/files')return ok({file:await uploadFile(request,env,actor,url)},request,env);const fileParams=routeMatch(path,'/api/files/:key');if(fileParams&&method==='GET')return getFile(env,actor,fileParams.key);
  if(method==='GET'&&path==='/api/autosave')return ok(await getAutosaveV15(env,actor,url),request,env);if(method==='PUT'&&path==='/api/autosave')return ok(await saveAutosaveV15(request,env,actor),request,env);if(method==='DELETE'&&path==='/api/autosave')return ok(await deleteAutosaveV15(request,env,actor,url),request,env);
  if(method==='GET'&&path==='/api/trash')return ok({items:await listTrashV15(env,actor)},request,env);const trashRestoreParams=routeMatch(path,'/api/trash/:id/restore');if(trashRestoreParams&&method==='POST')return ok(await restoreTrashV15(request,env,actor,trashRestoreParams.id),request,env);const trashPurgeParams=routeMatch(path,'/api/trash/:id/purge');if(trashPurgeParams&&method==='POST')return ok(await purgeTrashV15(request,env,actor,trashPurgeParams.id),request,env);
  if(method==='GET'&&path==='/api/notification-channels')return ok(await notificationSettingsV15(env,actor),request,env);if(method==='PATCH'&&path==='/api/notification-channels')return ok({channel:await updateNotificationSettingsV15(request,env,actor)},request,env);if(method==='POST'&&path==='/api/notification-queue')return ok({notification:await queueNotificationV15(request,env,actor)},request,env);if(method==='POST'&&path==='/api/notification-queue/dispatch')return ok(await dispatchNotificationsV15(env,actor),request,env);if(method==='GET'&&path==='/api/notifications')return ok({notifications:await listNotificationsV13(env,actor)},request,env);
  if(method==='GET'&&path==='/api/billing')return ok(await billingStateV15(env,actor),request,env);if(method==='POST'&&path==='/api/billing/checkout')return ok(await createCheckoutV15(request,env,actor),request,env);
  if(method==='GET'&&path==='/api/backups')return ok({backups:await listBackupsV15(env,actor)},request,env);if(method==='POST'&&path==='/api/backups')return ok({backup:await createBackupV15(request,env,actor)},request,env);if(method==='POST'&&path==='/api/backups/restore')return ok(await restoreBackupV15(request,env,actor),request,env);if(method==='GET'&&path==='/api/backups/export')return ok({backup:await exportWorkspaceV13(request,env,actor)},request,env);if(method==='POST'&&path==='/api/storage/migrate-r2')return ok(await migrateFilesToR2V15(env,actor),request,env);if(method==='GET'&&path==='/api/monitoring')return ok(await monitoringSummaryV15(env,actor),request,env);if(method==='GET'&&path==='/api/exports/executive')return executiveExportV15(request,env,actor,url);if(method==='POST'&&path==='/api/telemetry/client')return ok(await recordClientEventV13(request,env,actor),request,env);if(method==='GET'&&path==='/api/telemetry/diagnostics')return ok({diagnostics:await getDiagnosticsV13(env,actor)},request,env);if(method==='GET'&&path==='/api/account/readiness')return ok({account:await getAccountReadinessV13(env,actor)},request,env);
  if(method==='GET'&&path==='/api/users')return ok({users:await listUsers(env,actor)},request,env);if(method==='POST'&&path==='/api/users')return ok({user:await createUser(request,env,actor)},request,env);const profileParams=routeMatch(path,'/api/users/:id/profile');if(profileParams&&method==='PATCH')return ok({user:await updateUserProfile(request,env,actor,profileParams.id)},request,env);const userParams=routeMatch(path,'/api/users/:id');if(userParams&&method==='PATCH')return ok({user:await updateUser(request,env,actor,userParams.id)},request,env);const passwordParams=routeMatch(path,'/api/users/:id/password');if(passwordParams&&method==='POST')return ok(await changePassword(request,env,actor,passwordParams.id),request,env);if(method==='GET'&&path==='/api/sessions')return ok({sessions:await listSessions(env,actor)},request,env);const sessionParams=routeMatch(path,'/api/sessions/:id/revoke');if(sessionParams&&method==='POST')return ok(await revokeSession(request,env,actor,sessionParams.id),request,env);if(method==='GET'&&path==='/api/audit')return ok({events:await auditLog(env,actor,url)},request,env);throw new HttpError(404,'Ruta no encontrada','not_found');
}
export default{async fetch(request,env,ctx){const requestId=crypto.randomUUID(),startedAt=Date.now();try{return addPlatformHeaders(await handleRequest(request,env,ctx),request,env,requestId,startedAt)}catch(error){if(Number(error?.status||500)>=500)console.error('request_failed',{requestId,path:new URL(request.url).pathname,error});return addPlatformHeaders(errorResponse(error,request,env),request,env,requestId,startedAt)}}};
