'use strict';
function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result,tx=request.transaction;let store;if(!db.objectStoreNames.contains('orders'))store=db.createObjectStore('orders',{keyPath:'folio'});else store=tx.objectStore('orders');if(!store.indexNames.contains('createdAt'))store.createIndex('createdAt','createdAt');if(!db.objectStoreNames.contains('invoices'))store=db.createObjectStore('invoices',{keyPath:'id',autoIncrement:true});else store=tx.objectStore('invoices');if(!store.indexNames.contains('folio'))store.createIndex('folio','folio');if(!store.indexNames.contains('provider'))store.createIndex('provider','provider');if(!db.objectStoreNames.contains('prices'))store=db.createObjectStore('prices',{keyPath:'id'});else store=tx.objectStore('prices');if(!store.indexNames.contains('productId'))store.createIndex('productId','productId');if(!store.indexNames.contains('createdAt'))store.createIndex('createdAt','createdAt');if(!db.objectStoreNames.contains('assets'))db.createObjectStore('assets',{keyPath:'key'});if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('La base local está bloqueada. Cierra la app y vuelve a abrirla.'))});return dbPromise}
async function dbGet(store,key){const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function dbAll(store){const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function dbPut(store,value){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite'),r=tx.objectStore(store).put(value);r.onsuccess=()=>{if(value.id==null)value.id=r.result};tx.oncomplete=()=>res(value);tx.onerror=()=>rej(tx.error)})}
async function dbDelete(store,key){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function dbDeleteWhere(store,predicate){for(const row of await dbAll(store))if(predicate(row))await dbDelete(store,row.id??row.folio??row.key)}
const assetKey=(type,name='')=>`${type}:${norm(name)}`;
async function getAsset(type,name=''){return dbGet('assets',assetKey(type,name))}
async function putAsset(type,name,data,extra={}){return dbPut('assets',{key:assetKey(type,name),type,name,data,updatedAt:new Date().toISOString(),...extra})}
async function removeAsset(type,name=''){return dbDelete('assets',assetKey(type,name))}
const dataUrlFromFile=file=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)});
async function optimizeImage(file,max=1000){const raw=await dataUrlFromFile(file),img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=raw}),scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/png')}
async function legacyProviderAssets(){return new Promise(resolve=>{let upgraded=false;const request=indexedDB.open('pedidos-proveedores-assets');request.onupgradeneeded=()=>{upgraded=true;request.transaction.abort()};request.onerror=()=>resolve([]);request.onsuccess=()=>{const db=request.result;if(upgraded||!db.objectStoreNames.contains('providerLogos')){db.close();return resolve([])}const r=db.transaction('providerLogos').objectStore('providerLogos').getAll();r.onsuccess=()=>{db.close();resolve(r.result||[])};r.onerror=()=>{db.close();resolve([])}}})}
async function migrateAssets(){const candidates=[['company-primary','',legacyRaw?.profile?.logo],['company-secondary','',legacyRaw?.profile?.logo2]];for(const provider of state.catalog.providers){const old=(legacyRaw?.catalog?.providers||[]).find(x=>norm(x.name)===norm(provider.name))?.logo||legacyRaw?.providerLogos?.[provider.name];candidates.push(['provider',provider.name,old])}for(const old of await legacyProviderAssets())candidates.push(['provider',old.name,old.data]);for(const [type,name,data]of candidates){if(data&&!await getAsset(type,name))await putAsset(type,name,data)}persistState()}
const categories=()=>state.catalog.categories.filter(x=>x.enabled!==false).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name,'es'));
const providers=()=>state.catalog.providers.filter(x=>x.enabled!==false).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name,'es'));
const categoryRank=name=>{const i=categories().findIndex(x=>norm(x.name)===norm(name));return i<0?999:i};
const qty=id=>Number(state.order[id]?.qty||0);
const packSizeFromUnit=unit=>{const m=String(unit||'').match(/\((\d+)\)/);return m?Number(m[1]):1};
const orderRows=()=>state.items.filter(x=>x.enabled&&qty(x.id)>0).sort((a,b)=>categoryRank(a.category)-categoryRank(b.category)||a.sortOrder-b.sortOrder).map(x=>({...x,qty:qty(x.id),unit:state.order[x.id]?.unit||x.unit}));
const groupedOrder=rows=>rows.reduce((acc,row)=>((acc[row.provider]??=[]).push(row),acc),{});
function orderStatus(order){const rows=order.rows||[];if(!rows.length)return'pending';if(rows.every(row=>Number(row.receivedBaseQty||row.receivedQty||0)>=Number(row.orderedBaseQty||row.orderedQty||0)))return'complete';return rows.some(row=>Number(row.receivedBaseQty||row.receivedQty||0)>0)?'partial':'pending'}
function normalizedOrderRow(row,old={}){const orderedQty=Number(row.qty??row.orderedQty)||0,unit=row.unit||old.unit||'UNIDAD',orderedBaseQty=orderedQty*packSizeFromUnit(unit);return{...old,id:row.id||row.productId,productId:row.productId||row.id,description:row.description,provider:row.provider,category:row.category,unit,orderedQty,orderedBaseQty,receivedBaseQty:Number(old.receivedBaseQty??old.receivedQty)||0,receivedQty:Number(old.receivedBaseQty??old.receivedQty)||0,unitPriceGross:Number(old.unitPriceGross??old.unitPrice)||0}}
async function allocateFolio(){const explicit=clean(state.profile.folioPrefix||'').replaceAll('_','').slice(0,4),derived=clean(state.profile.location||'MDR').split('_').filter(Boolean).map(x=>x[0]).join('').slice(0,4),prefix=explicit||derived||'PDD',day=new Date().toISOString().slice(2,10).replaceAll('-',''),used=new Set((await dbAll('orders')).filter(x=>x.folio?.startsWith(`${prefix}-${day}-`)).map(x=>Number(x.folio.split('-').at(-1))));let seq=1;while(used.has(seq))seq++;return`${prefix}-${day}-${String(seq).padStart(3,'0')}`}
async function saveCurrentOrder(){const rows=orderRows();if(!rows.length)return null;if(!state.currentFolio)state.currentFolio=await allocateFolio();const existing=await dbGet('orders',state.currentFolio),oldMap=new Map((existing?.rows||[]).map(x=>[String(x.productId||x.id),x])),normalized=rows.map(row=>normalizedOrderRow(row,oldMap.get(String(row.id))||{})),order={...(existing||{}),folio:state.currentFolio,createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),company:state.profile.location,rows:normalized,providers:[...new Set(normalized.map(x=>x.provider))],totalItems:normalized.length};order.status=orderStatus(order);await dbPut('orders',order);persistState();return order}
