'use strict';
function applyTheme(){const theme=state.settings.theme==='dark'?'dark':'light';document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;const color=theme==='dark'?'#090e16':'#f4f7fb';$('#themeColorMeta').content=color;document.body.style.backgroundColor=color}
function fillSelectors(){const pOptions=providers().map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join(''),cOptions=categories().map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');for(const id of ['providerFilter','dbProvider']){const el=$('#'+id),old=el.value;el.innerHTML='<option value="">Todos los proveedores</option>'+pOptions;if([...el.options].some(x=>x.value===old))el.value=old}for(const id of ['categoryFilter','dbCategory']){const el=$('#'+id),old=el.value;el.innerHTML='<option value="">Todas las categorías</option>'+cOptions;if([...el.options].some(x=>x.value===old))el.value=old}$('#itemCategory').innerHTML=cOptions;$('#itemProvider').innerHTML=pOptions;$('#itemUnit').innerHTML=UNITS.map(x=>`<option>${x}</option>`).join('')}
function renderOrder(){const query=$('#search').value.trim().toLowerCase(),provider=$('#providerFilter').value,category=$('#categoryFilter').value,items=state.items.filter(x=>x.enabled&&(!provider||x.provider===provider)&&(!category||x.category===category)&&(!query||`${x.description} ${x.provider} ${x.category}`.toLowerCase().includes(query))).sort((a,b)=>categoryRank(a.category)-categoryRank(b.category)||a.sortOrder-b.sortOrder),groups={};for(const item of items)(groups[item.category||'OTROS']??=[]).push(item);$('#hero').classList.toggle('compact',!!query);$('#orderList').innerHTML=Object.entries(groups).sort(([a],[b])=>categoryRank(a)-categoryRank(b)).map(([name,rows])=>`<section class="card" data-category="${esc(name)}"><div class="categoryhead"><h3>${esc(name)}</h3><span class="pill">${rows.filter(x=>qty(x.id)>0).length} seleccionados</span></div>${rows.map(item=>`<div class="row"><div class="desc">${esc(item.description)}<small>${esc(item.provider)}</small></div><input class="qty" inputmode="decimal" enterkeyhint="next" value="${qty(item.id)||''}" placeholder="0" data-qty="${esc(item.id)}" aria-label="Cantidad ${esc(item.description)}"><select data-unit="${esc(item.id)}">${UNITS.map(unit=>`<option ${unit===(state.order[item.id]?.unit||item.unit)?'selected':''}>${unit}</option>`).join('')}</select></div>`).join('')}</section>`).join('')||'<div class="card empty">No hay productos para este filtro.</div>';renderMetrics()}
function renderMetrics(){const rows=orderRows();$('#metricItems').textContent=rows.length;$('#metricProviders').textContent=new Set(rows.map(x=>x.provider)).size}
function renderFiles(){const groups=groupedOrder(orderRows());$('#filesList').innerHTML=Object.entries(groups).map(([provider,rows])=>`<article class="card file-card"><div><h3>${esc(provider)}</h3><span class="muted">${rows.length} ítems · ${state.currentFolio||'folio al exportar'}</span></div><div class="file-actions"><button class="btn" data-current-preview="${esc(provider)}">Vista previa</button><button class="btn primary" data-current-download="${esc(provider)}">Descargar PDF</button><button class="btn" data-current-share="${esc(provider)}">Compartir</button></div></article>`).join('')||'<div class="card empty">Aún no hay productos con cantidad.</div>'}
function renderProducts(){const q=$('#dbSearch').value.trim().toLowerCase(),p=$('#dbProvider').value,c=$('#dbCategory').value,rows=state.items.filter(x=>(!p||x.provider===p)&&(!c||x.category===c)&&(!q||`${x.description} ${x.provider} ${x.category}`.toLowerCase().includes(q))).sort((a,b)=>categoryRank(a.category)-categoryRank(b.category)||a.sortOrder-b.sortOrder);$('#productsList').innerHTML=rows.map(x=>`<div class="dbrow"><div><b>${esc(x.description)}</b><div class="dbmeta">${esc(x.category)} · ${esc(x.provider)} · ${esc(x.unit)} · ${x.enabled?'Habilitado':'Deshabilitado'}</div></div><div class="inline-actions"><button class="iconbtn" data-toggle-product="${esc(x.id)}">${x.enabled?'◉':'○'}</button><button class="iconbtn" data-edit-product="${esc(x.id)}">✎</button><button class="iconbtn" data-delete-product="${esc(x.id)}">⌫</button></div></div>`).join('')||'<div class="empty">Sin resultados.</div>'}
function renderCategories(){const rows=categories();$('#categoriesList').innerHTML=rows.map(x=>`<div class="catalog-row" data-category-name="${encodeURIComponent(x.name)}"><input value="${esc(x.name)}"><button class="iconbtn" data-delete-category="${encodeURIComponent(x.name)}">⌫</button></div>`).join('')}
async function renderProviders(){const rows=providers(),assets=await Promise.all(rows.map(x=>getAsset('provider',x.name)));$('#providersList').innerHTML=rows.map((x,i)=>`<div class="provider-row"><div class="provider-logo-preview">${assets[i]?.data?`<img src="${assets[i].data}" alt="Logo ${esc(x.name)}">`:'Sin logo'}</div><div class="provider-controls"><b>${esc(x.name)}</b><label>Tamaño en PDF: <span>${x.logoSize||24}</span> mm<input type="range" min="10" max="48" value="${x.logoSize||24}" data-provider-size="${encodeURIComponent(x.name)}"></label></div><div class="provider-actions"><button class="btn small" data-provider-logo="${encodeURIComponent(x.name)}">${assets[i]?.data?'Cambiar logo':'Agregar logo'}</button>${assets[i]?.data?`<button class="btn small danger" data-remove-provider-logo="${encodeURIComponent(x.name)}">Quitar logo</button>`:''}<button class="btn small" data-rename-provider="${encodeURIComponent(x.name)}">Renombrar</button><button class="btn small danger" data-delete-provider="${encodeURIComponent(x.name)}">Eliminar</button></div><input hidden type="file" accept="image/*" data-provider-file="${encodeURIComponent(x.name)}"></div>`).join('')}
async function renderProfile(){const p=state.profile;$('#company').value=p.companyName||'';$('#rut').value=p.rut||'';$('#address').value=p.address||'';$('#location').value=p.location||'';$('#folioPrefix').value=p.folioPrefix||'MDR';$('#logoPosition').value=p.logoPosition||'left';$('#logoSize').value=p.logoSize||42;$('#logo2Size').value=p.logo2Size||28;$('#logoSizeValue').textContent=p.logoSize||42;$('#logo2SizeValue').textContent=p.logo2Size||28;$('#theme').value=state.settings.theme||'light';$('#tableHeaderColor').value=p.tableHeaderColor||'#48484c';const a=await getAsset('company-primary'),b=await getAsset('company-secondary');for(const [id,asset]of [['primaryLogoPreview',a],['secondaryLogoPreview',b]]){const img=$('#'+id);img.src=asset?.data||'';img.classList.toggle('hidden',!asset?.data)}$('#removePrimaryLogo').classList.toggle('hidden',!a?.data);$('#removeSecondaryLogo').classList.toggle('hidden',!b?.data);renderHeaderPreview(a?.data,b?.data)}
function renderHeaderPreview(primary,secondary){const p=state.profile,logos=[primary,secondary].filter(Boolean).map((src,i)=>`<img src="${src}" style="max-width:${i?(p.logo2Size||28)*1.7:(p.logoSize||42)*1.7}px;height:70px;object-fit:contain">`).join(''),rows=[['RAZÓN SOCIAL',p.companyName],['RUT',p.rut],['DIRECCIÓN',p.address],['LOCAL',p.location],['FOLIO','MDR-260716-001']];$('#headerPreview').innerHTML=`<div style="background:#fff;color:#111;border:1px solid #222;padding:10px;display:grid;grid-template-columns:${p.logoPosition==='left'?'34% 66%':p.logoPosition==='right'?'66% 34%':'1fr'};gap:8px">${p.logoPosition==='right'?table():''}<div style="display:flex;gap:8px;align-items:center;justify-content:center;${p.logoPosition==='top'||p.logoPosition==='bottom'?'grid-column:1/-1':''}">${logos||'<span style="color:#777">Sin logos</span>'}</div>${p.logoPosition!=='right'?table():''}</div><div style="background:${p.tableHeaderColor};color:#fff;padding:8px 12px;font-weight:800">DESCRIPCIÓN · CANTIDAD · UNIDAD</div>`;function table(){return`<table style="width:100%;border-collapse:collapse;font-size:10px">${rows.map(([a,b])=>`<tr><th style="border:1px solid #222;text-align:left;padding:3px">${a}</th><td style="border:1px solid #222;padding:3px">${esc(b||'')}</td></tr>`).join('')}</table>`}}
function renderAll(){applyTheme();fillSelectors();renderOrder();renderFiles();renderProducts();renderCategories();renderProviders();renderProfile();$('#buildVersion').textContent=`v${VERSION}`}
function switchView(view){currentView=view;$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const titles={order:['PEDIDO ACTUAL','Preparar pedido'],files:['DOCUMENTOS','Archivos PDF'],data:['CATÁLOGO','Base de datos'],management:['COMPRAS','Gestión'],profile:['CONFIGURACIÓN','Perfil']};$('#eyebrow').textContent=titles[view][0];$('#pageTitle').textContent=titles[view][1];window.scrollTo({top:0,behavior:'smooth'});if(view==='management')renderManagement();if(view==='profile')renderProfile();if(view==='data')renderProviders()}
function showDataPanel(name){$$('[data-data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.dataTab===name));$$('#view-data .panel').forEach(x=>x.classList.toggle('active',x.id===`data-${name}`));if(name==='providers')renderProviders()}
function showManagementPanel(name){activeManagement=name;$$('[data-management-tab]').forEach(x=>x.classList.toggle('active',x.dataset.managementTab===name));$$('#view-management .panel').forEach(x=>x.classList.toggle('active',x.id===`management-${name}`));if(name==='dashboard')renderDashboard();if(name==='history')renderHistory();if(name==='prices')renderPrices();if(name==='receipt')renderReceipt()}
async function companyAssets(){const [primary,secondary]=await Promise.all([getAsset('company-primary'),getAsset('company-secondary')]);return{primary:primary?.data||null,secondary:secondary?.data||null}}
function contrast(hex){const [r,g,b]=ProfessionalPDF.hexRgb(hex);return(r*299+g*587+b*114)/1000>145?'#111111':'#ffffff'}
async function drawPdfHeader(doc,folio){
 const p=state.profile,{primary,secondary}=await companyAssets(),logos=[{src:primary,size:p.logoSize||42},{src:secondary,size:p.logo2Size||28}].filter(x=>x.src),x=15,w=180,rowH=6.2,tableH=rowH*6,pos=p.logoPosition||'left',info=[['RAZÓN SOCIAL',p.companyName],['RUT',p.rut],['DIRECCIÓN',p.address],['LOCAL',p.location],['FECHA DE EMISIÓN',new Date().toLocaleDateString('es-CL',{dateStyle:'full'})],['FOLIO',folio]];
 const table=async(tx,ty,tw)=>{const labelW=Math.min(36,tw*.3);for(let i=0;i<info.length;i++){doc.setStroke('#222').rect(tx,ty+i*rowH,labelW,rowH).rect(tx+labelW,ty+i*rowH,tw-labelW,rowH);doc.text(info[i][0],tx+1.2,ty+i*rowH+4.25,{size:6.5,bold:true});let size=7;while(ProfessionalPDF.estimateWidth(info[i][1]||'',size)>((tw-labelW-3)*72/25.4)&&size>4.6)size-=.2;doc.text(info[i][1]||'',tx+labelW+1.3,ty+i*rowH+4.25,{size})}return ty+tableH};
 const logoBox=async(lx,ly,lw,lh,horizontal)=>{if(!logos.length)return;const gap=3;if(horizontal){let cursor=lx+4;for(const logo of logos){const width=Math.min(logo.size,lw/logos.length-5);await doc.image(logo.src,cursor,ly+2,width,lh-4);cursor+=lw/logos.length}}else{let cursor=ly+2;for(const logo of logos){const height=(lh-4-(logos.length-1)*gap)/logos.length;await doc.image(logo.src,lx+2,cursor,lw-4,height);cursor+=height+gap}}};
 if(!logos.length){await table(x,10,w);return 10+tableH}
 if(pos==='top'||pos==='bottom'){const logoH=26;doc.setStroke('#222').rect(x,10,w,tableH+logoH);if(pos==='top'){await logoBox(x,10,w,logoH,true);doc.line(x,10+logoH,x+w,10+logoH);await table(x,10+logoH,w)}else{await table(x,10,w);doc.line(x,10+tableH,x+w,10+tableH);await logoBox(x,10+tableH,w,logoH,true)}return 10+tableH+logoH}
 const logoW=55,tableW=w-logoW;doc.setStroke('#222').rect(x,10,w,tableH);if(pos==='left'){await logoBox(x,10,logoW,tableH,false);doc.line(x+logoW,10,x+logoW,10+tableH);await table(x+logoW,10,tableW)}else{await table(x,10,tableW);doc.line(x+tableW,10,x+tableW,10+tableH);await logoBox(x+tableW,10,logoW,tableH,false)}return 10+tableH;
}
async function buildProviderPdf(order,provider){
 const rows=(order.rows||[]).filter(x=>x.provider===provider),doc=new ProfessionalPDF.Document().setMeta({title:`Pedido ${provider}`}),providerMeta=state.catalog.providers.find(x=>norm(x.name)===norm(provider)),providerLogo=await getAsset('provider',provider);let y=await drawPdfHeader(doc,order.folio)+6;doc.text(`PROVEEDOR: ${provider}`,105,y+6,{size:15,bold:true,align:'center',maxWidth:135});if(providerLogo?.data)await doc.image(providerLogo.data,165,y,Math.min(30,providerMeta?.logoSize||24),15);y+=18;const headerColor=state.profile.tableHeaderColor||'#48484c',headerText=contrast(headerColor);
 const tableHeader=()=>{doc.setFill(headerColor).rect(15,y,180,8,'F');doc.text('DESCRIPCIÓN',18,y+5.5,{size:8,bold:true,color:headerText});doc.text('CANTIDAD',154,y+5.5,{size:8,bold:true,align:'center',color:headerText});doc.text('UNIDAD',169,y+5.5,{size:8,bold:true,color:headerText});y+=8};tableHeader();
 for(const row of rows){const lines=ProfessionalPDF.wrapText(row.description,122*72/25.4,8),unitLines=ProfessionalPDF.wrapText(row.unit,25*72/25.4,8),h=Math.max(7,Math.max(lines.length,unitLines.length)*3.6+2);if(y+h>285){doc.addPage();y=15;tableHeader()}doc.setStroke('#222').rect(15,y,128,h).rect(143,y,22,h).rect(165,y,30,h);doc.text(lines.join('\n'),18,y+4.8,{size:8});doc.text(String(row.orderedQty??row.qty),161,y+4.8,{size:8,align:'right'});doc.text(unitLines.join('\n'),168,y+4.8,{size:8});y+=h}
 return doc.blob();
}
async function exportProvider(order,provider,mode='download'){try{const blob=await buildProviderPdf(order,provider),name=`${clean(order.folio)}_${clean(provider)}.pdf`;if(mode==='preview')return showDocument(blob,`${order.folio} · ${provider}`,name);if(mode==='share'&&navigator.share&&navigator.canShare?.({files:[new File([blob],name,{type:'application/pdf'})]})){await navigator.share({title:`Pedido ${provider}`,files:[new File([blob],name,{type:'application/pdf'})]});return}downloadBlob(blob,name)}catch(error){console.error(error);toast(error.message||'No se pudo generar el PDF',4000)}}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000)}
function showDocument(blob,title,name){const dialog=$('#documentDialog');if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);$('#documentTitle').textContent=title;$('#documentFrame').src=previewUrl;$('#documentDownload').onclick=()=>downloadBlob(blob,name);dialog.showModal()}
