(function(root){
  'use strict';
  const State=root.PedidosState,DB=root.PedidosDB,Orders=root.PedidosOrders,Core=root.PedidosCore,PDF=root.PedidosPDF,Invoice=root.PedidosInvoice;
  const VERSION='8.0.0';
  const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const number=value=>Core.numberFrom(value);
  const money=value=>Number(value||0).toLocaleString('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0});
  const date=value=>new Date(value).toLocaleDateString('es-CL');
  const state=()=>State.value;
  let currentView='order',managementTab='dashboard',dataTab='products',activeReception=null,toastTimer=null,keyboardInput=null,pdfUrl='',fileUrl='';
  const assetUrls=new Map();

  function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),2600)}
  function statusText(value){return value==='complete'?'Completo':value==='partial'?'Parcial':'Pendiente'}
  function providerName(id,fallback=''){return State.provider(id)?.name||fallback||'Proveedor'}
  function categoryName(id,fallback='OTROS'){return State.category(id)?.name||fallback}
  function itemById(id){return State.item(id)}
  function uniqueId(prefix){return`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}

  async function assetUrl(key){
    if(assetUrls.has(key))return assetUrls.get(key);
    const asset=await DB.getAsset(key);if(!asset?.blob)return'';
    const url=URL.createObjectURL(asset.blob);assetUrls.set(key,url);return url;
  }
  async function assetData(key){return DB.assetDataUrl(key)}
  function clearAssetUrl(key){const url=assetUrls.get(key);if(url)URL.revokeObjectURL(url);assetUrls.delete(key)}

  function applyTheme(){
    const theme=state().settings.theme==='dark'?'dark':'light';document.documentElement.dataset.theme=theme;document.documentElement.style.background=theme==='dark'?'#090e16':'#f3f6fb';
    const meta=$('#themeColorMeta');if(meta)meta.content=theme==='dark'?'#090e16':'#f3f6fb';
  }
  function updateOnline(){const badge=$('#offlineBadge');badge.classList.toggle('hidden',navigator.onLine);badge.textContent='Modo offline'}

  function switchView(view){
    currentView=view;$$('.view').forEach(node=>node.classList.toggle('active',node.id===`view-${view}`));$$('.nav-btn').forEach(button=>button.classList.toggle('active',button.dataset.view===view));
    const titles={order:['PEDIDO ACTUAL','Preparar pedido'],files:['DOCUMENTOS','Archivos PDF'],management:['COMPRAS','Gestión profesional'],data:['CATÁLOGOS','Base de datos'],profile:['CONFIGURACIÓN','Perfil']};
    $('#eyebrow').textContent=titles[view][0];$('#pageHeading').textContent=titles[view][1];
    const showOrderActions=view==='order'||view==='files';$('#clearDraft').classList.toggle('hidden',!showOrderActions);$('#generateOrder').classList.toggle('hidden',!showOrderActions);
    window.scrollTo({top:0,behavior:'instant'});
    if(view==='files')renderFiles();if(view==='management')renderManagement();if(view==='data')renderData();if(view==='profile')renderProfile();
  }

  function draftQty(id){return Number(state().draft[id]?.qty)||0}
  function groupedProducts(items){
    const groups=new Map();for(const item of items){const key=item.categoryId;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(item)}
    return[...groups.entries()].sort(([a],[b])=>(State.category(a)?.sortOrder??999)-(State.category(b)?.sortOrder??999));
  }

  function fillOrderFilters(){
    const providerSelect=$('#orderProviderFilter'),categorySelect=$('#orderCategoryFilter'),oldProvider=providerSelect.value,oldCategory=categorySelect.value;
    providerSelect.innerHTML='<option value="">Todos los proveedores</option>'+State.enabledProviders().map(entry=>`<option value="${esc(entry.id)}">${esc(entry.name)}</option>`).join('');
    categorySelect.innerHTML='<option value="">Todas las categorías</option>'+State.enabledCategories().map(entry=>`<option value="${esc(entry.id)}">${esc(entry.name)}</option>`).join('');
    providerSelect.value=[...providerSelect.options].some(option=>option.value===oldProvider)?oldProvider:'';categorySelect.value=[...categorySelect.options].some(option=>option.value===oldCategory)?oldCategory:'';
  }

  function renderOrder(){
    fillOrderFilters();const query=Core.normalizeText($('#orderSearch').value),providerId=$('#orderProviderFilter').value,categoryId=$('#orderCategoryFilter').value;
    const items=state().items.filter(item=>item.enabled!==false&&(!providerId||item.providerId===providerId)&&(!categoryId||item.categoryId===categoryId)&&(!query||Core.normalizeText(`${item.description} ${providerName(item.providerId)} ${categoryName(item.categoryId)}`).includes(query))).sort((a,b)=>(State.category(a.categoryId)?.sortOrder??999)-(State.category(b.categoryId)?.sortOrder??999)||a.sortOrder-b.sortOrder);
    $('#orderSummary').classList.toggle('hidden',!!query);
    $('#orderList').innerHTML=groupedProducts(items).map(([categoryId,rows])=>`<section class="card category-card" data-category-card="${esc(categoryId)}"><div class="category-head"><h3>${esc(categoryName(categoryId))}</h3><span class="pill">${rows.filter(item=>draftQty(item.id)>0).length} seleccionados</span></div>${rows.map(item=>`<div class="product-row"><div class="product-name">${esc(item.description)}<small>${esc(providerName(item.providerId))}</small></div><input class="qty-input" inputmode="decimal" enterkeyhint="next" autocomplete="off" data-qty="${esc(item.id)}" value="${draftQty(item.id)||''}" placeholder="0" aria-label="Cantidad ${esc(item.description)}"><select data-unit="${esc(item.id)}">${State.UNITS.map(unit=>`<option ${unit===(state().draft[item.id]?.unit||item.unit)?'selected':''}>${unit}</option>`).join('')}</select></div>`).join('')}</section>`).join('')||'<div class="card empty">No hay productos para este filtro.</div>';
    updateDraftSummary();
  }
  function updateDraftSummary(){const rows=State.draftRows();$('#summaryItems').textContent=rows.length;$('#summaryProviders').textContent=new Set(rows.map(row=>row.providerId)).size;$('#summaryUnits').textContent=Math.round(rows.reduce((sum,row)=>sum+row.orderedQty*Core.packFromUnit(row.unit),0))}

  function visibleQtyInputs(){return $$('#orderList [data-qty]').filter(input=>input.offsetParent!==null)}
  function focusQty(step){
    const inputs=visibleQtyInputs();if(!inputs.length)return;let index=inputs.indexOf(document.activeElement);if(index<0)index=Math.max(0,inputs.indexOf(keyboardInput));const target=inputs[Math.max(0,Math.min(inputs.length-1,index+step))];if(!target||target===document.activeElement)return;
    keyboardInput=target;target.focus({preventScroll:true});target.select?.();requestAnimationFrame(()=>target.scrollIntoView({block:'center',behavior:'smooth'}));
  }
  function positionKeyboardBar(){
    const bar=$('#keyboardBar'),viewport=window.visualViewport,active=document.activeElement?.matches?.('#orderList [data-qty]');if(!active||!viewport||viewport.height>=window.innerHeight*.86){hideKeyboardBar();return}
    document.body.classList.add('keyboard-open');bar.classList.remove('hidden');bar.style.top=`${Math.max(8,viewport.offsetTop+viewport.height-bar.offsetHeight-8)}px`;bar.style.bottom='auto';
  }
  function showKeyboardBar(input){keyboardInput=input;setTimeout(positionKeyboardBar,40)}
  function hideKeyboardBar(){const bar=$('#keyboardBar');bar.classList.add('hidden');document.body.classList.remove('keyboard-open')}

  async function generateOrder(){
    try{const order=await Orders.saveDraft();toast(`Pedido ${order.folio} actualizado`);await renderFiles();switchView('files');await renderManagement()}
    catch(error){toast(error.message||'No se pudo guardar el pedido')}
  }
  async function clearDraft(){if(!confirm('¿Limpiar las cantidades del pedido actual? El historial guardado no se eliminará.'))return;state().draft={};state().currentOrderFolio=null;State.persist();renderOrder();await renderFiles();toast('Pedido actual limpio')}

  async function currentOrder(){const folio=state().currentOrderFolio;return folio?Orders.get(folio):null}
  async function providerPdfOptions(order,providerId){
    const fallback=order.rows.find(row=>row.providerId===providerId)?.providerName||'',provider=State.provider(providerId)||{id:providerId,name:fallback,logoSize:24};
    return{order,provider:{...provider,logo:await assetData(`provider:${providerId}`)},profile:state().profile,logos:{logo1:await assetData('profile:logo1'),logo2:await assetData('profile:logo2'),logo1Size:state().profile.logoSize,logo2Size:state().profile.logo2Size}};
  }
  async function handlePdf(order,providerId,mode){
    const provider=State.provider(providerId)||{id:providerId,name:order.rows.find(row=>row.providerId===providerId)?.providerName||'Proveedor'};
    const name=PDF.fileName(order,provider);
    try{
      if(mode==='preview')openPdfModal(`${order.folio} · ${provider.name}`,'Cargando documento…');
      const blob=await PDF.blob(await providerPdfOptions(order,providerId));
      if(mode==='preview'){if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=URL.createObjectURL(blob);$('#pdfFrame').src=pdfUrl;return}
      if(mode==='share'){const shared=await PDF.share(blob,name,`Pedido ${provider.name}`);if(shared)return}
      PDF.download(blob,name);
    }catch(error){closeDialog('#pdfDialog');toast(error.message||'No se pudo generar el PDF')}
  }
  function openPdfModal(title,message=''){const dialog=$('#pdfDialog');$('#pdfTitle').textContent=title;$('#pdfFrame').src=message?`data:text/html;charset=utf-8,${encodeURIComponent(`<style>body{font-family:system-ui;display:grid;place-items:center;height:100vh;margin:0;background:#eee;color:#333}</style><b>${esc(message)}</b>`)}`:'about:blank';dialog.showModal()}

  async function renderFiles(){
    const order=await currentOrder();if(!order){$('#filesList').innerHTML='<div class="card empty">Genera el pedido para crear los PDF por proveedor.</div>';return}
    const providerIds=order.providerIds?.length?order.providerIds:[...new Set(order.rows.map(row=>row.providerId))];
    $('#filesFolio').textContent=order.folio;$('#filesList').innerHTML=providerIds.map(providerId=>{const name=providerName(providerId,order.rows.find(row=>row.providerId===providerId)?.providerName),count=order.rows.filter(row=>row.providerId===providerId).length;return`<article class="card file-card"><div><h3>${esc(name)}</h3><span class="muted">${count} ítems · ${esc(order.folio)}</span></div><div class="file-actions"><button class="btn" data-pdf-preview="${esc(providerId)}">Vista previa</button><button class="btn primary" data-pdf-download="${esc(providerId)}">Descargar</button><button class="btn" data-pdf-share="${esc(providerId)}">Compartir</button></div></article>`}).join('')||'<div class="card empty">Este pedido no tiene proveedores.</div>';
  }

  function setManagementTab(tab){managementTab=tab;$$('[data-management-tab]').forEach(button=>button.classList.toggle('active',button.dataset.managementTab===tab));$$('.management-panel').forEach(panel=>panel.classList.toggle('active',panel.id===`management-${tab}`));if(tab==='dashboard')renderDashboard();if(tab==='history')renderHistory();if(tab==='reception')renderReception();if(tab==='prices')renderPrices()}
  async function renderManagement(){setManagementTab(managementTab)}

  async function renderHistory(){
    const query=Core.normalizeText($('#historySearch').value),filter=$('#historyStatus').value;let orders=await Orders.list();
    orders=orders.filter(order=>(!filter||order.status===filter)&&(!query||Core.normalizeText(`${order.folio} ${(order.providers||[]).join(' ')} ${(order.rows||[]).map(row=>row.description).join(' ')}`).includes(query)));
    $('#historyList').innerHTML=orders.map(order=>{
      const providerIds=order.providerIds?.length?order.providerIds:[...new Set((order.rows||[]).map(row=>row.providerId))];
      const providers=providerIds.map(providerId=>{const name=providerName(providerId,order.rows.find(row=>row.providerId===providerId)?.providerName),count=order.rows.filter(row=>row.providerId===providerId).length;return`<div class="provider-order-row"><div><b>${esc(name)}</b><small>${count} ítems</small></div><div class="provider-order-actions"><button class="btn small" data-history-edit="${esc(order.folio)}" data-provider="${esc(providerId)}">Editar</button><button class="btn small" data-history-reception="${esc(order.folio)}" data-provider="${esc(providerId)}">Recepción</button><button class="btn small" data-history-pdf="${esc(order.folio)}" data-provider="${esc(providerId)}">PDF</button></div></div>`}).join('');
      return`<article class="card order-card"><div class="order-top"><div><div class="folio">${esc(order.folio)}</div><div>${date(order.createdAt)} · ${order.totalItems||order.rows?.length||0} productos</div></div><span class="status ${esc(order.status||'pending')}">${statusText(order.status)}</span></div><div class="provider-order-list">${providers||'<div class="muted">Sin proveedores</div>'}</div><div class="manage-actions"><button class="btn small" data-history-add-provider="${esc(order.folio)}">Agregar proveedor</button><button class="btn small" data-history-load="${esc(order.folio)}">Cargar como pedido actual</button><button class="btn small danger" data-history-delete="${esc(order.folio)}">Eliminar pedido</button></div></article>`;
    }).join('')||'<div class="card empty">No hay pedidos que coincidan.</div>';
  }

  async function openProviderEditor(folio,providerId){
    const order=await Orders.get(folio);if(!order)return toast('Pedido no encontrado');
    const provider=State.provider(providerId)||{id:providerId,name:order.rows.find(row=>row.providerId===providerId)?.providerName||'Proveedor'};
    const rows=structuredClone(order.rows.filter(row=>row.providerId===providerId));
    const dialog=$('#providerEditorDialog');dialog.dataset.folio=folio;dialog.dataset.providerId=providerId;dialog._rows=rows;$('#providerEditorTitle').textContent=`${order.folio} · ${provider.name}`;renderProviderEditorRows();renderProviderAddResults();dialog.showModal();
  }
  function renderProviderEditorRows(){
    const dialog=$('#providerEditorDialog'),rows=dialog._rows||[];$('#providerEditorRows').innerHTML=rows.map((row,index)=>`<div class="edit-row" data-edit-index="${index}"><div><b>${esc(row.description)}</b><small class="muted">${esc(row.category||'')}</small></div><input inputmode="decimal" data-edit-qty value="${Number(row.orderedQty)||''}" aria-label="Cantidad"><select data-edit-unit>${State.UNITS.map(unit=>`<option ${unit===row.unit?'selected':''}>${unit}</option>`).join('')}</select><button class="icon-btn danger" data-edit-remove="${index}" type="button">⌫</button></div>`).join('')||'<div class="empty">Este proveedor aún no tiene ítems.</div>';
  }
  function renderProviderAddResults(){
    const dialog=$('#providerEditorDialog'),providerId=dialog.dataset.providerId,query=Core.normalizeText($('#providerProductSearch').value),used=new Set((dialog._rows||[]).map(row=>row.productId));
    const items=state().items.filter(item=>item.enabled!==false&&item.providerId===providerId&&!used.has(item.id)&&(!query||Core.normalizeText(`${item.description} ${categoryName(item.categoryId)}`).includes(query))).slice(0,80);
    $('#providerProductResults').innerHTML=items.map(item=>`<div class="result-row"><div><b>${esc(item.description)}</b><small class="muted">${esc(categoryName(item.categoryId))} · ${esc(item.unit)}</small></div><button class="btn small" data-add-product="${esc(item.id)}" type="button">Agregar</button></div>`).join('')||'<div class="empty">Sin productos disponibles.</div>';
  }
  function collectProviderEditorRows(){
    const dialog=$('#providerEditorDialog');$$('#providerEditorRows [data-edit-index]').forEach(element=>{const row=dialog._rows[Number(element.dataset.editIndex)];if(row){row.orderedQty=number(element.querySelector('[data-edit-qty]').value);row.unit=element.querySelector('[data-edit-unit]').value}});return(dialog._rows||[]).filter(row=>row.orderedQty>0)
  }
  async function saveProviderEditor(exportAfter=false){
    const dialog=$('#providerEditorDialog'),folio=dialog.dataset.folio,providerId=dialog.dataset.providerId,rows=collectProviderEditorRows();
    try{const order=await Orders.updateProviderRows(folio,providerId,rows);dialog.close();await renderHistory();await renderFiles();toast('Pedido actualizado');if(exportAfter)await handlePdf(order,providerId,'download')}
    catch(error){toast(error.message||'No se pudo guardar el pedido')}
  }

  async function openAddProvider(folio){
    const order=await Orders.get(folio),used=new Set(order.providerIds||[]),available=State.enabledProviders().filter(provider=>!used.has(provider.id));
    $('#addProviderSelect').innerHTML=available.map(provider=>`<option value="${esc(provider.id)}">${esc(provider.name)}</option>`).join('');$('#addProviderDialog').dataset.folio=folio;$('#addProviderDialog').showModal();
  }

  async function renderDashboard(){
    const days=Number($('#dashboardPeriod').value||30),cut=Date.now()-days*86400000,orders=(await Orders.list()).filter(order=>new Date(order.createdAt).getTime()>=cut),prices=await Orders.priceHistory();
    const rows=orders.flatMap(order=>order.rows||[]),received=rows.filter(row=>row.receivedQty>0),spend=received.reduce((sum,row)=>sum+Number(row.grossValue||0),0),missing=rows.filter(row=>Number(row.receivedQty)<Number(row.orderedQty)).length;
    $('#dashboardMetrics').innerHTML=`<div class="metric-card"><span>Pedidos</span><b>${orders.length}</b></div><div class="metric-card"><span>Recepcionados</span><b>${orders.filter(order=>order.status==='complete').length}</b></div><div class="metric-card"><span>Gasto registrado</span><b>${money(spend)}</b></div><div class="metric-card"><span>Ítems faltantes</span><b>${missing}</b></div>`;
    const products=new Map();for(const row of received){const entry=products.get(row.productId)||{name:row.description,units:0,value:0};entry.units+=Number(row.receivedUnits||row.receivedQty||0);entry.value+=Number(row.grossValue||0);products.set(row.productId,entry)}
    const top=[...products.values()].sort((a,b)=>b.units-a.units).slice(0,10),max=Math.max(1,...top.map(item=>item.units));$('#dashboardProducts').innerHTML=top.map(item=>`<div class="chart-row"><div class="chart-label"><span>${esc(item.name)}</span><b>${item.units.toFixed(item.units%1?1:0)} un · ${money(item.value)}</b></div><div class="chart-track"><div class="chart-fill" style="width:${item.units/max*100}%"></div></div></div>`).join('')||'<div class="empty">Aún no hay recepciones en este período.</div>';
    const providerTotals=new Map();for(const row of received){const entry=providerTotals.get(row.providerId)||{name:row.providerName,value:0};entry.value+=Number(row.grossValue||0);providerTotals.set(row.providerId,entry)}
    const providers=[...providerTotals.values()].sort((a,b)=>b.value-a.value),maxProvider=Math.max(1,...providers.map(item=>item.value));$('#dashboardProviders').innerHTML=providers.map(item=>`<div class="chart-row"><div class="chart-label"><span>${esc(item.name)}</span><b>${money(item.value)}</b></div><div class="chart-track"><div class="chart-fill" style="width:${item.value/maxProvider*100}%"></div></div></div>`).join('')||'<div class="empty">Sin gastos por proveedor.</div>';
    $('#dashboardPriceCount').textContent=`${prices.length} registros de precio`;
  }

  async function renderPrices(){
    const history=await Orders.priceHistory(),groups=new Map();for(const row of history){const key=`${row.productId}|${row.providerId}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}
    const entries=[...groups.values()].map(rows=>{rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const latest=rows[0],previous=rows[1],variation=previous?.grossUnitPrice?((latest.grossUnitPrice-previous.grossUnitPrice)/previous.grossUnitPrice*100):null;return{latest,previous,variation}}).sort((a,b)=>a.latest.description.localeCompare(b.latest.description,'es'));
    $('#priceHistoryList').innerHTML=`<div class="card reception-table"><table class="data-table"><thead><tr><th>Producto</th><th>Proveedor</th><th>Precio botella/unidad</th><th>Anterior</th><th>Variación</th><th>Factura</th><th>Fecha</th></tr></thead><tbody>${entries.map(({latest,previous,variation})=>`<tr><td>${esc(latest.description)}</td><td>${esc(latest.provider)}</td><td><b>${money(latest.grossUnitPrice)}</b></td><td>${previous?money(previous.grossUnitPrice):'—'}</td><td>${variation==null?'—':`${variation>=0?'+':''}${variation.toFixed(1)}%`}</td><td>${esc(latest.invoiceNumber||'—')}</td><td>${date(latest.createdAt)}</td></tr>`).join('')}</tbody></table>${entries.length?'':'<div class="empty">Aún no hay precios históricos.</div>'}</div>`;
  }

  async function openReception(folio,providerId){activeReception={folio,providerId};managementTab='reception';switchView('management');setManagementTab('reception')}
  async function renderReception(){
    if(!activeReception){$('#receptionContent').innerHTML='<div class="card empty">Selecciona “Recepción” desde un proveedor del historial.</div>';return}
    const order=await Orders.get(activeReception.folio);if(!order){activeReception=null;return renderReception()}
    const providerIds=order.providerIds?.length?order.providerIds:[...new Set(order.rows.map(row=>row.providerId))];if(!providerIds.includes(activeReception.providerId))activeReception.providerId=providerIds[0];const providerId=activeReception.providerId,name=providerName(providerId,order.rows.find(row=>row.providerId===providerId)?.providerName),rows=order.rows.filter(row=>row.providerId===providerId),invoices=await Orders.invoiceList(order.folio,providerId);
    $('#receptionContent').innerHTML=`<div class="card"><div class="section-head"><div><h3>${esc(order.folio)}</h3><span class="muted">Recepción separada por proveedor</span></div><span class="status ${esc(order.status)}">${statusText(order.status)}</span></div><div class="receipt-provider-tabs">${providerIds.map(id=>{const providerRows=order.rows.filter(row=>row.providerId===id),received=providerRows.filter(row=>row.receivedQty>0).length;return`<button class="provider-tab ${id===providerId?'active':''}" data-reception-provider="${esc(id)}"><b>${esc(providerName(id,providerRows[0]?.providerName))}</b><small>${received}/${providerRows.length} recibidos</small></button>`}).join('')}</div></div><div class="card"><div class="section-head"><div><h3>Facturas de ${esc(name)}</h3><span class="muted">Acepta varias facturas para el mismo proveedor.</span></div></div><label class="upload-box"><input id="invoiceInput" type="file" accept="image/*,application/pdf" multiple><b>Tomar foto o seleccionar facturas</b><span>La lectura calcula cajas, unidades y precios finales con IVA.</span></label><div id="invoiceProgress"></div><div id="invoiceList">${invoices.map(invoice=>invoiceCard(invoice)).join('')||'<div class="empty">Sin facturas asignadas.</div>'}</div></div><div class="card"><div class="section-head"><div><h3>Resumen recibido</h3><span class="muted">Lo recibido se suma desde todas las facturas revisadas.</span></div></div><div class="reception-table"><table class="data-table"><thead><tr><th>Producto</th><th>Pedido</th><th>Recibido</th><th>Faltante</th><th>Unidades</th><th>Precio final unidad</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row.description)}</td><td>${row.orderedQty} ${esc(row.unit)}</td><td>${Number(row.receivedQty||0).toFixed(row.receivedQty%1?1:0)}</td><td>${Math.max(0,Number(row.orderedQty)-Number(row.receivedQty||0)).toFixed(1).replace('.0','')}</td><td>${Number(row.receivedUnits||0).toFixed(row.receivedUnits%1?1:0)}</td><td>${row.unitPrice?money(row.unitPrice):'—'}</td></tr>`).join('')}</tbody></table></div></div>`;
  }
  function invoiceCard(invoice){return`<div class="invoice-row"><div><b>${esc(invoice.displayName||invoice.originalName||'Factura')}</b><small>${invoice.status==='processing'?'Procesando':invoice.status==='error'?'Requiere revisión':`${(invoice.lines||[]).length} ítems · ${invoice.invoiceNumber?'N° '+invoice.invoiceNumber:'sin número detectado'}`}</small></div><div class="invoice-actions"><button class="btn small" data-invoice-view="${invoice.id}">Ver</button><button class="btn small" data-invoice-review="${invoice.id}">Revisar resumen</button><button class="icon-btn danger" data-invoice-delete="${invoice.id}">⌫</button></div></div>`}
  function showProgress(label,percent){const box=$('#invoiceProgress');if(!box)return;box.innerHTML=`<div class="progress"><div class="progress-head"><b>${esc(label)}</b><span>${Math.round(percent)}%</span></div><div class="progress-track"><i style="width:${percent}%"></i></div></div>`}
  async function processInvoices(files){
    if(!activeReception)return;const order=await Orders.get(activeReception.folio),providerId=activeReception.providerId,provider=State.provider(providerId)||{name:order.rows.find(row=>row.providerId===providerId)?.providerName||'Proveedor'},products=order.rows.filter(row=>row.providerId===providerId).map(row=>({productId:row.productId,description:row.description,unit:row.unit}));
    for(const file of files){
      const invoice={folio:order.folio,providerId,providerName:provider.name,originalName:file.name,file,createdAt:new Date().toISOString(),status:'processing',lines:[]};await Orders.saveInvoice(invoice);await renderReception();
      try{const result=await Invoice.analyze(file,products,update=>showProgress(update.label,update.percent));invoice.ocrText=result.text;invoice.invoiceNumber=result.summary.invoiceNumber||'';invoice.taxTotals=result.summary.totals;invoice.lines=result.summary.lines||[];invoice.status='read';invoice.displayName=Core.invoiceDisplayName(provider.name,invoice.invoiceNumber||`SIN-${invoice.id}`,file.name);await Orders.saveInvoice(invoice);await Orders.recomputeReception(order.folio,providerId);toast(`${invoice.displayName}: ${invoice.lines.length} coincidencias`)}
      catch(error){invoice.status='error';invoice.error=String(error.message||error);invoice.displayName=Core.invoiceDisplayName(provider.name,`SIN-${invoice.id}`,file.name);await Orders.saveInvoice(invoice);toast('Factura guardada; revisa los ítems manualmente')}
      await renderReception();
    }
    $('#invoiceProgress').innerHTML='';await renderHistory();await renderDashboard();
  }

  async function viewInvoice(id){
    const invoice=await DB.get('invoices',Number(id));if(!invoice?.file)return toast('El archivo de esta factura no está disponible');if(fileUrl)URL.revokeObjectURL(fileUrl);fileUrl=URL.createObjectURL(invoice.file);$('#filePreviewTitle').textContent=invoice.displayName||invoice.originalName||'Factura';const content=$('#filePreviewContent');content.innerHTML=invoice.file.type==='application/pdf'?`<iframe src="${fileUrl}" title="Factura"></iframe>`:`<img src="${fileUrl}" alt="Factura">`;$('#filePreviewDialog').showModal();
  }
  async function openInvoiceReview(id){
    const invoice=await DB.get('invoices',Number(id)),order=invoice&&await Orders.get(invoice.folio);if(!invoice||!order)return toast('Factura no encontrada');const products=order.rows.filter(row=>row.providerId===invoice.providerId),lines=(invoice.lines?.length?structuredClone(invoice.lines):products.map((row,index)=>({id:`manual-${index}`,sourceLine:'',productId:row.productId,packageQty:0,packSize:Core.packFromUnit(row.unit),units:0,grossUnitPrice:0,grossLineTotal:0,receivedOrderQty:0})));
    const dialog=$('#invoiceReviewDialog');dialog.dataset.invoiceId=invoice.id;dialog._products=products;dialog._lines=lines;$('#invoiceReviewName').value=invoice.invoiceNumber||'';$('#invoiceReviewTitle').textContent=invoice.displayName||invoice.originalName;$('#invoiceTaxInfo').textContent=`Neto ${money(invoice.taxTotals?.net||0)} · IVA ${money(invoice.taxTotals?.tax||0)} · Total ${money(invoice.taxTotals?.total||0)} · Factor ${Number(invoice.taxTotals?.taxFactor||1.19).toFixed(3)}`;renderInvoiceReviewRows();dialog.showModal();
  }
  function reviewProductOptions(selected){const products=$('#invoiceReviewDialog')._products||[];return'<option value="">Sin vincular</option>'+products.map(product=>`<option value="${esc(product.productId)}" ${product.productId===selected?'selected':''}>${esc(product.description)}</option>`).join('')}
  function renderInvoiceReviewRows(){const dialog=$('#invoiceReviewDialog');$('#invoiceReviewRows').innerHTML=(dialog._lines||[]).map((line,index)=>`<div class="invoice-review-row" data-review-index="${index}"><textarea data-review-source placeholder="Texto leído">${esc(line.sourceLine||'')}</textarea><select data-review-product>${reviewProductOptions(line.productId)}</select><input data-review-packages inputmode="decimal" value="${Number(line.packageQty)||''}" placeholder="Cajas"><input data-review-pack inputmode="numeric" value="${Number(line.packSize)||1}" placeholder="x un"><input data-review-total inputmode="decimal" value="${Number(line.grossLineTotal)||''}" placeholder="$ total final"><input data-review-unit-price inputmode="decimal" value="${Number(line.grossUnitPrice)||''}" placeholder="$ por unidad"></div>`).join('')||'<div class="empty">Agrega una línea para registrar productos.</div>'}
  function collectReviewLines(){
    const dialog=$('#invoiceReviewDialog'),products=dialog._products||[];return $$('#invoiceReviewRows [data-review-index]').map(element=>{const source=dialog._lines[Number(element.dataset.reviewIndex)]||{},productId=element.querySelector('[data-review-product]').value,product=products.find(row=>row.productId===productId),packageQty=number(element.querySelector('[data-review-packages]').value),packSize=Math.max(1,number(element.querySelector('[data-review-pack]').value)||1),units=packageQty*packSize,grossTotal=number(element.querySelector('[data-review-total]').value),grossUnit=number(element.querySelector('[data-review-unit-price]').value)||(units&&grossTotal?Math.round(grossTotal/units):0),grossPack=packageQty&&grossTotal?Math.round(grossTotal/packageQty):grossUnit*packSize,orderPack=Core.packFromUnit(product?.unit),receivedOrderQty=orderPack>1?units/orderPack:units;return{...source,sourceLine:element.querySelector('[data-review-source]').value,productId,description:product?.description||'',packageQty,packSize,units,grossLineTotal:grossTotal||Math.round(grossUnit*units),grossUnitPrice:grossUnit,grossPackPrice:grossPack,receivedOrderQty:Number(receivedOrderQty.toFixed(3))}}).filter(line=>line.productId&&(line.units>0||line.grossUnitPrice>0))
  }
  async function saveInvoiceReview(){
    const dialog=$('#invoiceReviewDialog'),invoice=await DB.get('invoices',Number(dialog.dataset.invoiceId));if(!invoice)return;const invoiceNumber=$('#invoiceReviewName').value.trim(),lines=collectReviewLines();invoice.invoiceNumber=invoiceNumber;invoice.displayName=Core.invoiceDisplayName(invoice.providerName,invoiceNumber||`SIN-${invoice.id}`,invoice.originalName);await Orders.reviewInvoice(invoice.id,lines,{invoiceNumber,displayName:invoice.displayName});dialog.close();await renderReception();await renderHistory();await renderPrices();await renderDashboard();toast('Factura y precios actualizados')
  }

  function setDataTab(tab){dataTab=tab;$$('[data-data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.dataTab===tab));$$('.data-panel').forEach(panel=>panel.classList.toggle('active',panel.id===`data-${tab}`));renderData()}
  async function renderData(){if(dataTab==='products')renderProducts();if(dataTab==='categories')renderCategories();if(dataTab==='providers')await renderProviders()}
  function fillDataFilters(){const p=$('#dataProviderFilter'),c=$('#dataCategoryFilter'),oldP=p.value,oldC=c.value;p.innerHTML='<option value="">Todos los proveedores</option>'+State.enabledProviders().map(row=>`<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('');c.innerHTML='<option value="">Todas las categorías</option>'+State.enabledCategories().map(row=>`<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('');p.value=[...p.options].some(o=>o.value===oldP)?oldP:'';c.value=[...c.options].some(o=>o.value===oldC)?oldC:''}
  function renderProducts(){
    fillDataFilters();const query=Core.normalizeText($('#dataSearch').value),providerId=$('#dataProviderFilter').value,categoryId=$('#dataCategoryFilter').value,items=state().items.filter(item=>(!providerId||item.providerId===providerId)&&(!categoryId||item.categoryId===categoryId)&&(!query||Core.normalizeText(`${item.description} ${providerName(item.providerId)} ${categoryName(item.categoryId)}`).includes(query))).sort((a,b)=>(State.category(a.categoryId)?.sortOrder??999)-(State.category(b.categoryId)?.sortOrder??999)||a.sortOrder-b.sortOrder);
    $('#productDatabase').innerHTML=groupedProducts(items).map(([catId,rows])=>`<section class="card db-group"><h3>${esc(categoryName(catId))}</h3>${rows.map(item=>`<div class="db-row ${item.enabled===false?'off':''}"><div><b>${esc(item.description)}</b><div class="db-meta">${esc(providerName(item.providerId))} · ${esc(item.unit)} · ${item.enabled===false?'Deshabilitado':'Habilitado'}</div></div><div><button class="icon-btn" data-product-toggle="${esc(item.id)}">${item.enabled===false?'○':'◉'}</button> <button class="icon-btn" data-product-edit="${esc(item.id)}">✎</button> <button class="icon-btn danger" data-product-delete="${esc(item.id)}">⌫</button></div></div>`).join('')}</section>`).join('')||'<div class="card empty">Sin resultados.</div>';
  }
  function renderCategories(){
    const rows=[...state().catalog.categories].sort((a,b)=>a.sortOrder-b.sortOrder);$('#categoryDatabase').innerHTML=`<div class="card"><div class="section-head"><div><h3>Categorías</h3><span class="muted">Los nombres se guardan al salir del campo.</span></div></div><div class="catalog-list">${rows.map(row=>`<div class="catalog-row" data-category-id="${esc(row.id)}"><input value="${esc(row.name)}" data-category-name><div class="catalog-actions"><button class="btn small" data-category-toggle>${row.enabled===false?'Habilitar':'Deshabilitar'}</button>${row.name==='OTROS'?'':`<button class="icon-btn danger" data-category-delete>⌫</button>`}</div></div>`).join('')}</div><div class="manage-actions"><input id="newCategory" placeholder="Nueva categoría"><button class="btn primary" id="addCategory">Agregar categoría</button></div></div>`;
  }
  async function renderProviders(){
    const rows=[...state().catalog.providers].sort((a,b)=>a.sortOrder-b.sortOrder),logos=await Promise.all(rows.map(row=>assetUrl(`provider:${row.id}`)));$('#providerDatabase').innerHTML=`<div class="card"><div class="section-head"><div><h3>Proveedores</h3><span class="muted">Nombre, estado y logo del PDF se guardan automáticamente.</span></div></div><div class="catalog-list">${rows.map((row,index)=>`<div class="catalog-row catalog-provider" data-provider-id="${esc(row.id)}"><div>${logos[index]?`<img class="provider-logo-preview" src="${logos[index]}" alt="Logo">`:'<div class="provider-logo-preview empty">Sin logo</div>'}</div><div><input value="${esc(row.name)}" data-provider-name><label class="field"><span>Tamaño logo: <b>${Number(row.logoSize)||24}</b> mm</span><input type="range" min="10" max="48" value="${Number(row.logoSize)||24}" data-provider-logo-size></label></div><div class="catalog-actions"><input type="file" accept="image/*" hidden data-provider-logo-file><button class="btn small" data-provider-choose-logo>${logos[index]?'Reemplazar logo':'Elegir logo'}</button>${logos[index]?'<button class="btn small danger" data-provider-remove-logo>Eliminar logo</button>':''}<button class="btn small" data-provider-toggle>${row.enabled===false?'Habilitar':'Deshabilitar'}</button><button class="icon-btn danger" data-provider-delete>⌫</button></div></div>`).join('')}</div><div class="manage-actions"><input id="newProvider" placeholder="Nuevo proveedor"><button class="btn primary" id="addProvider">Agregar proveedor</button></div></div>`;
  }

  function openProductModal(id=''){
    const item=id?itemById(id):null;$('#productModalTitle').textContent=item?'Editar ítem':'Nuevo ítem';$('#productId').value=item?.id||'';$('#productDescription').value=item?.description||'';$('#productCategory').innerHTML=State.enabledCategories().map(row=>`<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('');$('#productProvider').innerHTML=State.enabledProviders().map(row=>`<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('');$('#productUnit').innerHTML=State.UNITS.map(unit=>`<option>${unit}</option>`).join('');$('#productCategory').value=item?.categoryId||State.enabledCategories()[0]?.id||'';$('#productProvider').value=item?.providerId||State.enabledProviders()[0]?.id||'';$('#productUnit').value=item?.unit||'UNIDAD';$('#productEnabled').checked=item?.enabled!==false;$('#productDialog').showModal();
  }
  function saveProduct(){const id=$('#productId').value,data={description:$('#productDescription').value.trim(),categoryId:$('#productCategory').value,providerId:$('#productProvider').value,unit:$('#productUnit').value,enabled:$('#productEnabled').checked};if(!data.description||!data.providerId||!data.categoryId)return toast('Completa producto, categoría y proveedor');const existing=id&&itemById(id);if(existing)Object.assign(existing,data);else state().items.push({id:uniqueId('item'),sortOrder:Math.max(-1,...state().items.map(item=>Number(item.sortOrder)||0))+1,...data});State.persist();$('#productDialog').close();renderProducts();renderOrder();toast('Ítem guardado')}

  async function renderProfile(){
    const profile=state().profile;$('#companyName').value=profile.companyName||'';$('#companyRut').value=profile.rut||'';$('#companyAddress').value=profile.address||'';$('#companyLocation').value=profile.location||'';$('#folioPrefix').value=profile.folioPrefix||'MDR';$('#logoPosition').value=profile.logoPosition||'left';$('#companyLogoSize').value=profile.logoSize||42;$('#companyLogo2Size').value=profile.logo2Size||28;$('#themeSelect').value=state().settings.theme||'light';$('#headerColor').value=profile.tableHeaderColor||'#48484c';$('#companyLogoSizeValue').textContent=profile.logoSize||42;$('#companyLogo2SizeValue').textContent=profile.logo2Size||28;
    const logo1=await assetUrl('profile:logo1'),logo2=await assetUrl('profile:logo2');renderLogoBox('companyLogo1Preview',logo1,'removeCompanyLogo1');renderLogoBox('companyLogo2Preview',logo2,'removeCompanyLogo2');renderHeaderPreview(logo1,logo2);$$('[data-header-color]').forEach(button=>button.classList.toggle('active',button.dataset.headerColor.toLowerCase()===(profile.tableHeaderColor||'').toLowerCase()));
  }
  function renderLogoBox(id,url,removeId){const image=$(`#${id}`),remove=$(`#${removeId}`);image.src=url||'';image.classList.toggle('hidden',!url);remove.classList.toggle('hidden',!url)}
  function renderHeaderPreview(logo1,logo2){const profile=state().profile;$('#headerPreview').innerHTML=`<div style="border:1px solid #222;background:#fff;color:#111;padding:12px;display:grid;grid-template-columns:${profile.logoPosition==='right'?'1fr 110px':'110px 1fr'};gap:10px;align-items:center"><div style="${profile.logoPosition==='right'?'grid-column:2':'grid-column:1'};text-align:center">${logo1?`<img src="${logo1}" style="max-width:100%;max-height:55px;object-fit:contain">`:''}${logo2?`<img src="${logo2}" style="max-width:100%;max-height:40px;object-fit:contain">`:''}</div><table style="${profile.logoPosition==='right'?'grid-column:1;grid-row:1':'grid-column:2'};width:100%;border-collapse:collapse;font-size:10px"><tr><th style="border:1px solid #222;text-align:left">RAZÓN SOCIAL</th><td style="border:1px solid #222">${esc(profile.companyName)}</td></tr><tr><th style="border:1px solid #222;text-align:left">RUT</th><td style="border:1px solid #222">${esc(profile.rut)}</td></tr><tr><th style="border:1px solid #222;text-align:left">DIRECCIÓN</th><td style="border:1px solid #222">${esc(profile.address)}</td></tr><tr><th style="border:1px solid #222;text-align:left">LOCAL</th><td style="border:1px solid #222">${esc(profile.location)}</td></tr></table></div><div style="background:${profile.tableHeaderColor};color:${contrastCss(profile.tableHeaderColor)};padding:9px 12px;font-weight:800;margin-top:8px;border-radius:8px">DESCRIPCIÓN　 CANTIDAD　 UNIDAD</div>`}
  function contrastCss(hex){const clean=String(hex).replace('#',''),r=parseInt(clean.slice(0,2),16),g=parseInt(clean.slice(2,4),16),b=parseInt(clean.slice(4,6),16);return(r*299+g*587+b*114)/1000>155?'#111':'#fff'}
  function saveProfileFromInputs(){const profile=state().profile;Object.assign(profile,{companyName:$('#companyName').value.trim(),rut:$('#companyRut').value.trim(),address:$('#companyAddress').value.trim(),location:$('#companyLocation').value.trim(),folioPrefix:Core.sanitizePrefix($('#folioPrefix').value),logoPosition:$('#logoPosition').value,logoSize:Number($('#companyLogoSize').value)||42,logo2Size:Number($('#companyLogo2Size').value)||28,tableHeaderColor:$('#headerColor').value});state().settings.theme=$('#themeSelect').value==='dark'?'dark':'light';State.persist();applyTheme();$('#companyLogoSizeValue').textContent=profile.logoSize;$('#companyLogo2SizeValue').textContent=profile.logo2Size;renderProfile()}

  function closeDialog(selector){const dialog=$(selector);if(dialog?.open)dialog.close()}
  async function deleteOrder(folio){if(!confirm(`¿Eliminar el pedido ${folio}? También se eliminarán sus facturas y precios. El número quedará disponible para reutilizarse.`))return;await Orders.remove(folio);await renderHistory();await renderDashboard();await renderFiles();toast('Pedido eliminado y folio liberado')}

  function bindEvents(){
    $$('.nav-btn').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));$('#generateOrder').addEventListener('click',generateOrder);$('#clearDraft').addEventListener('click',clearDraft);
    $('#orderSearch').addEventListener('input',renderOrder);$('#orderProviderFilter').addEventListener('change',renderOrder);$('#orderCategoryFilter').addEventListener('change',renderOrder);
    $('#orderList').addEventListener('input',event=>{const id=event.target.dataset.qty;if(!id)return;const qty=Math.max(0,number(event.target.value)),item=itemById(id);if(qty>0)state().draft[id]={qty,unit:state().draft[id]?.unit||item?.unit||'UNIDAD'};else delete state().draft[id];State.persist();updateDraftSummary();const card=event.target.closest('[data-category-card]');if(card){const categoryId=card.dataset.categoryCard,items=state().items.filter(item=>item.categoryId===categoryId&&item.enabled!==false);card.querySelector('.pill').textContent=`${items.filter(item=>draftQty(item.id)>0).length} seleccionados`}});
    $('#orderList').addEventListener('change',event=>{const id=event.target.dataset.unit;if(id){const item=itemById(id);state().draft[id]={qty:draftQty(id),unit:event.target.value||item?.unit||'UNIDAD'};State.persist()}});
    $('#orderList').addEventListener('focusin',event=>{if(event.target.matches('[data-qty]'))showKeyboardBar(event.target)});$('#orderList').addEventListener('focusout',()=>setTimeout(()=>{if(!document.activeElement?.matches?.('#orderList [data-qty]'))hideKeyboardBar()},180));$('#orderList').addEventListener('keydown',event=>{if(event.target.matches('[data-qty]')&&event.key==='Enter'){event.preventDefault();event.stopImmediatePropagation();keyboardInput=event.target;focusQty(1)}});
    $('#keyboardPrev').addEventListener('pointerdown',event=>{event.preventDefault();focusQty(-1)});$('#keyboardNext').addEventListener('pointerdown',event=>{event.preventDefault();focusQty(1)});$('#keyboardDone').addEventListener('click',()=>{keyboardInput?.blur();hideKeyboardBar()});window.visualViewport?.addEventListener('resize',positionKeyboardBar);window.visualViewport?.addEventListener('scroll',positionKeyboardBar);

    $('#filesList').addEventListener('click',async event=>{const button=event.target.closest('[data-pdf-preview],[data-pdf-download],[data-pdf-share]');if(!button)return;const order=await currentOrder();if(!order)return;const providerId=button.dataset.pdfPreview||button.dataset.pdfDownload||button.dataset.pdfShare,mode=button.dataset.pdfPreview?'preview':button.dataset.pdfShare?'share':'download';handlePdf(order,providerId,mode)});
    $$('[data-management-tab]').forEach(button=>button.addEventListener('click',()=>setManagementTab(button.dataset.managementTab)));$('#historySearch').addEventListener('input',renderHistory);$('#historyStatus').addEventListener('change',renderHistory);$('#dashboardPeriod').addEventListener('change',renderDashboard);
    $('#historyList').addEventListener('click',async event=>{const button=event.target.closest('[data-history-edit],[data-history-reception],[data-history-pdf],[data-history-add-provider],[data-history-load],[data-history-delete]');if(!button)return;const folio=button.dataset.historyEdit||button.dataset.historyReception||button.dataset.historyPdf||button.dataset.historyAddProvider||button.dataset.historyLoad||button.dataset.historyDelete,providerId=button.dataset.provider;if(button.dataset.historyEdit)openProviderEditor(folio,providerId);else if(button.dataset.historyReception)openReception(folio,providerId);else if(button.dataset.historyPdf){const order=await Orders.get(folio);handlePdf(order,providerId,'download')}else if(button.dataset.historyAddProvider)openAddProvider(folio);else if(button.dataset.historyLoad){const order=await Orders.get(folio);Orders.loadIntoDraft(order);renderOrder();switchView('order');toast(`${folio} cargado como pedido actual`)}else deleteOrder(folio)});
    $('#providerEditorRows').addEventListener('click',event=>{const button=event.target.closest('[data-edit-remove]');if(!button)return;collectProviderEditorRows();$('#providerEditorDialog')._rows.splice(Number(button.dataset.editRemove),1);renderProviderEditorRows();renderProviderAddResults()});$('#providerProductSearch').addEventListener('input',renderProviderAddResults);$('#providerProductResults').addEventListener('click',event=>{const button=event.target.closest('[data-add-product]');if(!button)return;collectProviderEditorRows();const item=itemById(button.dataset.addProduct),dialog=$('#providerEditorDialog');dialog._rows.push({id:uniqueId('row'),productId:item.id,description:item.description,providerId:item.providerId,providerName:providerName(item.providerId),category:categoryName(item.categoryId),categoryId:item.categoryId,unit:item.unit,orderedQty:1,receivedQty:0,receivedUnits:0,reception:'pending',unitPrice:0,grossValue:0});renderProviderEditorRows();renderProviderAddResults()});$('#saveProviderChanges').addEventListener('click',()=>saveProviderEditor(false));$('#saveAndExportProvider').addEventListener('click',()=>saveProviderEditor(true));$('#confirmAddProvider').addEventListener('click',()=>{const folio=$('#addProviderDialog').dataset.folio,providerId=$('#addProviderSelect').value;$('#addProviderDialog').close();openProviderEditor(folio,providerId)});

    $('#receptionContent').addEventListener('click',async event=>{const provider=event.target.closest('[data-reception-provider]'),view=event.target.closest('[data-invoice-view]'),review=event.target.closest('[data-invoice-review]'),remove=event.target.closest('[data-invoice-delete]');if(provider){activeReception.providerId=provider.dataset.receptionProvider;renderReception()}else if(view)viewInvoice(view.dataset.invoiceView);else if(review)openInvoiceReview(review.dataset.invoiceReview);else if(remove&&confirm('¿Eliminar esta factura y sus precios asociados?')){await Orders.deleteInvoice(remove.dataset.invoiceDelete);renderReception();renderPrices();renderDashboard();toast('Factura eliminada')}});$('#receptionContent').addEventListener('change',event=>{if(event.target.id==='invoiceInput')processInvoices([...event.target.files])});
    $('#addInvoiceLine').addEventListener('click',()=>{const dialog=$('#invoiceReviewDialog');dialog._lines.push({id:uniqueId('line'),sourceLine:'',productId:'',packageQty:1,packSize:1,units:1,grossUnitPrice:0,grossLineTotal:0});renderInvoiceReviewRows()});$('#saveInvoiceReview').addEventListener('click',saveInvoiceReview);

    $$('[data-data-tab]').forEach(button=>button.addEventListener('click',()=>setDataTab(button.dataset.dataTab)));$('#dataSearch').addEventListener('input',renderProducts);$('#dataProviderFilter').addEventListener('change',renderProducts);$('#dataCategoryFilter').addEventListener('change',renderProducts);$('#newProduct').addEventListener('click',()=>openProductModal());$('#saveProduct').addEventListener('click',saveProduct);
    $('#productDatabase').addEventListener('click',event=>{const toggle=event.target.closest('[data-product-toggle]'),edit=event.target.closest('[data-product-edit]'),remove=event.target.closest('[data-product-delete]'),id=toggle?.dataset.productToggle||edit?.dataset.productEdit||remove?.dataset.productDelete;if(!id)return;const item=itemById(id);if(toggle){item.enabled=!item.enabled;State.persist();renderProducts();renderOrder()}else if(edit)openProductModal(id);else if(confirm('¿Eliminar este ítem de la base de datos?')){state().items=state().items.filter(row=>row.id!==id);delete state().draft[id];State.persist();renderProducts();renderOrder()}});
    $('#categoryDatabase').addEventListener('change',event=>{const row=event.target.closest('[data-category-id]');if(!row)return;const category=State.category(row.dataset.categoryId);if(event.target.matches('[data-category-name]')){const value=event.target.value.trim();if(value)category.name=value;State.persist();renderOrder();renderCategories()}});$('#categoryDatabase').addEventListener('click',event=>{const row=event.target.closest('[data-category-id]');if(!row)return;const category=State.category(row.dataset.categoryId);if(event.target.closest('[data-category-toggle]')){category.enabled=!category.enabled;State.persist();renderCategories();renderOrder()}else if(event.target.closest('[data-category-delete]')){const linked=state().items.filter(item=>item.categoryId===category.id),other=state().catalog.categories.find(item=>item.name==='OTROS');if(confirm(linked.length?`Se moverán ${linked.length} ítems a OTROS. ¿Continuar?`:'¿Eliminar categoría?')){linked.forEach(item=>item.categoryId=other.id);state().catalog.categories=state().catalog.categories.filter(item=>item.id!==category.id);State.persist();renderCategories();renderProducts();renderOrder()}}else if(event.target.id==='addCategory'){}});$('#categoryDatabase').addEventListener('click',event=>{if(event.target.id!=='addCategory')return;const value=$('#newCategory').value.trim();if(!value)return;state().catalog.categories.push({id:uniqueId('cat'),name:value,enabled:true,sortOrder:state().catalog.categories.length});State.persist();renderCategories();renderOrder()});
    $('#providerDatabase').addEventListener('input',event=>{if(event.target.matches('[data-provider-logo-size]')){const row=event.target.closest('[data-provider-id]'),provider=State.provider(row.dataset.providerId);provider.logoSize=Number(event.target.value)||24;row.querySelector('label b').textContent=provider.logoSize;State.persist()}});$('#providerDatabase').addEventListener('change',async event=>{const row=event.target.closest('[data-provider-id]');if(!row)return;const provider=State.provider(row.dataset.providerId);if(event.target.matches('[data-provider-name]')){const old=provider.name,value=event.target.value.trim();if(value){provider.name=value;State.persist();renderProviders();renderOrder();if(old!==value)toast('Proveedor actualizado')}}else if(event.target.matches('[data-provider-logo-file]')&&event.target.files[0]){await DB.setAsset(`provider:${provider.id}`,event.target.files[0],{name:provider.name,logoSize:provider.logoSize});clearAssetUrl(`provider:${provider.id}`);renderProviders();toast('Logo guardado')}});$('#providerDatabase').addEventListener('click',async event=>{if(event.target.id==='addProvider'){const value=$('#newProvider').value.trim();if(!value)return;state().catalog.providers.push({id:uniqueId('prov'),name:value,enabled:true,sortOrder:state().catalog.providers.length,logoSize:24});State.persist();renderProviders();renderOrder();return}const row=event.target.closest('[data-provider-id]');if(!row)return;const provider=State.provider(row.dataset.providerId);if(event.target.closest('[data-provider-choose-logo]'))row.querySelector('[data-provider-logo-file]').click();else if(event.target.closest('[data-provider-remove-logo]')){await DB.remove('assets',`provider:${provider.id}`);clearAssetUrl(`provider:${provider.id}`);renderProviders();toast('Logo eliminado')}else if(event.target.closest('[data-provider-toggle]')){provider.enabled=!provider.enabled;State.persist();renderProviders();renderOrder()}else if(event.target.closest('[data-provider-delete]')){const linked=state().items.filter(item=>item.providerId===provider.id);if(linked.length)return toast('El proveedor tiene ítems. Deshabilítalo o reasigna sus productos antes de eliminarlo.');if(confirm('¿Eliminar proveedor?')){await DB.remove('assets',`provider:${provider.id}`);state().catalog.providers=state().catalog.providers.filter(item=>item.id!==provider.id);State.persist();renderProviders();renderOrder()}}});

    $('#profileForm').addEventListener('input',event=>{if(event.target.type!=='file')saveProfileFromInputs()});$('#profileForm').addEventListener('change',event=>{if(event.target.type!=='file')saveProfileFromInputs()});$('#companyLogo1').addEventListener('change',async event=>{if(event.target.files[0]){await DB.setAsset('profile:logo1',event.target.files[0],{name:'logo-principal'});clearAssetUrl('profile:logo1');renderProfile();toast('Logo principal guardado')}});$('#companyLogo2').addEventListener('change',async event=>{if(event.target.files[0]){await DB.setAsset('profile:logo2',event.target.files[0],{name:'logo-secundario'});clearAssetUrl('profile:logo2');renderProfile();toast('Logo secundario guardado')}});$('#removeCompanyLogo1').addEventListener('click',async()=>{await DB.remove('assets','profile:logo1');clearAssetUrl('profile:logo1');renderProfile()});$('#removeCompanyLogo2').addEventListener('click',async()=>{await DB.remove('assets','profile:logo2');clearAssetUrl('profile:logo2');renderProfile()});$('#colorPalette').addEventListener('click',event=>{const button=event.target.closest('[data-header-color]');if(button){$('#headerColor').value=button.dataset.headerColor;saveProfileFromInputs()}});

    $$('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));$('#pdfDialog').addEventListener('close',()=>{if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl='';$('#pdfFrame').src='about:blank'});$('#filePreviewDialog').addEventListener('close',()=>{if(fileUrl)URL.revokeObjectURL(fileUrl);fileUrl='';$('#filePreviewContent').innerHTML='' });
    window.addEventListener('online',updateOnline);window.addEventListener('offline',updateOnline);
  }

  async function registerServiceWorker(){
    if(!('serviceWorker'in navigator))return;
    try{const registration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await registration.update();if(registration.waiting)registration.waiting.postMessage({type:'SKIP_WAITING'});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!sessionStorage.getItem('v12-reloaded')){sessionStorage.setItem('v12-reloaded','1');location.reload()}});setTimeout(()=>navigator.serviceWorker.controller?.postMessage({type:'CACHE_OCR'}),5000)}catch(error){console.warn('Service worker no disponible',error)}
  }

  async function boot(){
    try{await State.init();applyTheme();bindEvents();renderOrder();await renderFiles();await renderManagement();await renderData();await renderProfile();$('#buildVersion').textContent=`v${VERSION}`;updateOnline();switchView('order');registerServiceWorker()}
    catch(error){console.error(error);document.body.innerHTML=`<main class="app-main"><div class="card"><h2>No se pudo iniciar la app</h2><p>${esc(error.message||error)}</p><button class="btn primary" onclick="location.reload()">Reintentar</button></div></main>`}
  }
  boot();
})(globalThis);
