(function(root){
  'use strict';
  const core=()=>root.PedidosCore;
  const URLS={tesseract:'https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js',pdf:'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js',pdfWorker:'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'};
  const loaders=new Map();
  function progress(callback,label,percent){if(typeof callback==='function')callback({label,percent:Math.max(0,Math.min(100,Number(percent)||0))})}
  function loadScript(url,test){if(test())return Promise.resolve();if(loaders.has(url))return loaders.get(url);const promise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=url;script.crossOrigin='anonymous';script.onload=()=>test()?resolve():reject(new Error('La biblioteca no se inició'));script.onerror=()=>reject(new Error('No se pudo descargar el lector'));document.head.appendChild(script)}).catch(error=>{loaders.delete(url);throw error});loaders.set(url,promise);return promise}
  async function ensureTesseract(){await loadScript(URLS.tesseract,()=>!!root.Tesseract);return root.Tesseract}
  async function ensurePdf(){await loadScript(URLS.pdf,()=>!!root.pdfjsLib);root.pdfjsLib.GlobalWorkerOptions.workerSrc=URLS.pdfWorker;return root.pdfjsLib}
  const loadImage=source=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('No se pudo abrir la imagen'));image.src=source});
  function enhanceCanvas(canvas){const context=canvas.getContext('2d',{willReadFrequently:true}),image=context.getImageData(0,0,canvas.width,canvas.height),data=image.data;let min=255,max=0;for(let i=0;i<data.length;i+=4){const gray=data[i]*.299+data[i+1]*.587+data[i+2]*.114;min=Math.min(min,gray);max=Math.max(max,gray)}const range=Math.max(35,max-min);for(let i=0;i<data.length;i+=4){let gray=data[i]*.299+data[i+1]*.587+data[i+2]*.114;gray=(gray-min)*255/range;gray=gray<170?gray*.72:180+(gray-170)*1.3;gray=Math.max(0,Math.min(255,gray));data[i]=data[i+1]=data[i+2]=gray;data[i+3]=255}context.putImageData(image,0,0)}
  async function imageFileToCanvas(file){const source=URL.createObjectURL(file);try{const image=await loadImage(source),max=2600,scale=Math.min(1,max/Math.max(image.naturalWidth||1,image.naturalHeight||1)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext('2d',{willReadFrequently:true});context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);enhanceCanvas(canvas);return canvas}finally{URL.revokeObjectURL(source)}}
  async function recognizeCanvas(canvas,onProgress){const Tesseract=await ensureTesseract(),result=await Tesseract.recognize(canvas,'spa+eng',{logger:message=>{if(message.status==='recognizing text')progress(onProgress,'Reconociendo texto',20+message.progress*75);else if(message.status)progress(onProgress,message.status,12)}});return result?.data?.text||''}
  async function readPdf(file,onProgress){const pdfjs=await ensurePdf(),pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise,textParts=[],pages=Math.min(pdf.numPages,8);for(let pageNumber=1;pageNumber<=pages;pageNumber++){progress(onProgress,`Leyendo página ${pageNumber} de ${pages}`,5+(pageNumber-1)/pages*70);const page=await pdf.getPage(pageNumber),content=await page.getTextContent(),plain=content.items.map(item=>item.str).join(' ');if(plain.replace(/\s/g,'').length>100){textParts.push(plain);continue}const viewport=page.getViewport({scale:1.8}),canvas=document.createElement('canvas');canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;enhanceCanvas(canvas);textParts.push(await recognizeCanvas(canvas,onProgress))}return textParts.join('\n')}
  async function readFile(file,onProgress){if(!file)throw new Error('Selecciona una factura');progress(onProgress,`Preparando ${file.name}`,2);let text='';if(file.type==='application/pdf'||/\.pdf$/i.test(file.name))text=await readPdf(file,onProgress);else text=await recognizeCanvas(await imageFileToCanvas(file),onProgress);progress(onProgress,'Cotejando productos y precios',95);return text}
  async function analyze(file,products,onProgress){const text=await readFile(file,onProgress),summary=core().matchInvoice(text,products||[]);progress(onProgress,'Lectura terminada',100);return{text,summary}}
  root.PedidosInvoice={readFile,analyze,enhanceCanvas};
})(globalThis);
