import {$,state,toast,setBusy} from './app-core.js';

let initialized=false,attempted=false;
function injectStyles(){if($('#ssoV20Styles'))return;const style=document.createElement('style');style.id='ssoV20Styles';style.textContent=`.sso-v20{display:grid;gap:9px;margin-top:12px;padding-top:12px;border-top:1px solid var(--line)}.sso-v20-divider{display:flex;align-items:center;gap:9px;color:var(--muted);font-size:9px}.sso-v20-divider:before,.sso-v20-divider:after{content:'';height:1px;flex:1;background:var(--line)}.sso-v20-button{min-height:49px;border:1px solid var(--line);border-radius:12px;background:var(--card);color:var(--text);font-weight:850}.sso-v20-button span{display:inline-grid;place-items:center;width:23px;height:23px;margin-right:8px;border-radius:7px;background:#fff;color:#4285f4;font-weight:950}.sso-v20-note{color:var(--muted);font-size:8px;line-height:1.45;text-align:center}`;document.head.append(style)}
async function health(){const response=await fetch('/platform/health',{cache:'no-store'});if(!response.ok)return null;return response.json().catch(()=>null)}
async function accessLogin(button=null){if(button)setBusy(button,true,'Validando con Google…');try{const response=await fetch('/api/auth/access',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),payload=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(payload.error||'No se pudo iniciar sesión con Google'),{code:payload.code,status:response.status});state.token=payload.token;localStorage.setItem('pp:token',state.token);toast('Sesión de Google validada');location.reload()}catch(error){if(error.code!=='access_login_required'&&error.code!=='access_not_configured')toast(error.message,'error')}finally{if(button)setBusy(button,false)}}
function mount(){const form=$('#loginForm');if(!form||$('#ssoV20'))return;form.insertAdjacentHTML('afterend',`<section class="sso-v20 hidden" id="ssoV20"><div class="sso-v20-divider">o</div><button class="sso-v20-button" id="ssoV20Button" type="button"><span>G</span>Continuar con Google</button><div class="sso-v20-note">Identidad protegida por Cloudflare Access. El correo debe estar creado previamente en la plataforma.</div></section>`);$('#ssoV20Button').onclick=()=>accessLogin($('#ssoV20Button'))}
async function refresh(){mount();const payload=await health().catch(()=>null),configured=Boolean(payload?.cloudflareAccessSso);$('#ssoV20')?.classList.toggle('hidden',!configured);if(configured&&!state.token&&!attempted){attempted=true;await accessLogin().catch(()=>{})}}
export function initializeSsoV20(){if(initialized)return;initialized=true;injectStyles();mount();refresh();window.addEventListener('pageshow',()=>refresh())}
