import {$,state,toast} from './app-core.js';
import {registerRouteRenderer,openRoute} from './app-router-v14.js';
import {renderDashboardV40} from './app-v40-operations.js';
import {renderOperationsAdmin} from './app-experience-admin.js';

let initialized=false,loadingTimer=null,slowTimer=null;
const iconPath={orders:'M6 5h12M6 9h12M6 13h8M5 3h14v18H5z',receiving:'M5 12l4 4L19 6',history:'M4 12a8 8 0 1 0 2.3-5.7M4 4v5h5M12 8v5l3 2',invoices:'M6 3h9l3 3v15H6zM15 3v4h4M9 12h6M9 16h6',finance:'M4 7h16M5 7v12h14V7M8 11h8M8 15h5',approvals:'M5 12l4 4L19 6',catalog:'M5 5h6v6H5zM13 5h6v6h-6zM5 13h6v6H5zM13 13h6v6h-6z',operations:'M4 7h16M4 12h16M4 17h16M8 5v4M15 10v4M11 15v4',suppliers:'M4 8h16v10H4zM7 8V5h10v3M8 13h8',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7M19 12l2-1-2-3-2 .5-1-2.5-2-1-2 1-3-.5-2 3-2 1 1 3-1 2 .5 1 2.5',team:'M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6M16 10a2.5 2.5 0 1 0 0-5M3 20c0-4 2-6 5-6s5 2 5 6M13 15c3 0 5 1.5 5 5',audit:'M12 8v5l3 2M4 12a8 8 0 1 0 8-8M4 4v5h5'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="${iconPath[name]||iconPath.settings}"/></svg>`;
function injectStyles(){if($('#v61RuntimeStyles'))return;const style=document.createElement('style');style.id='v61RuntimeStyles';style.textContent=`.v57-more-backdrop{position:fixed;z-index:11980;inset:0;background:rgba(5,10,20,.2);backdrop-filter:blur(2px)}.v57-more-sheet{position:fixed;z-index:11990;right:max(12px,env(safe-area-inset-right));bottom:calc(92px + env(safe-area-inset-bottom));width:min(390px,calc(100vw - 24px));max-height:min(72dvh,680px);overflow:auto;padding:10px;border:1px solid var(--line);border-radius:20px;background:color-mix(in srgb,var(--card) 97%,transparent);box-shadow:0 24px 70px rgba(0,0,0,.25)}.v57-more-group{display:grid;gap:4px;padding:7px}.v57-more-group+.v57-more-group{border-top:1px solid var(--line)}.v57-more-group>span{padding:5px;color:var(--muted);font-size:10px;font-weight:850;letter-spacing:.08em;text-transform:uppercase}.v57-more-item{display:grid;grid-template-columns:36px minmax(0,1fr) 18px;gap:9px;align-items:center;min-height:54px;padding:8px 10px;border:0;border-radius:12px;background:transparent;color:var(--text);text-align:left}.v57-more-item:active{background:var(--soft)}.v57-more-item i{display:grid;place-items:center;width:34px;height:34px;border-radius:9px;background:var(--soft);font-style:normal}.v57-more-item i svg{width:20px;height:20px}.v57-more-item strong,.v57-more-item small{display:block}.v57-more-item strong{font-size:14px}.v57-more-item small{margin-top:2px;color:var(--muted);font-size:11px}.v57-more-item>b{font-size:20px;font-weight:400;color:var(--muted)}.v57-nav-section{display:block;padding:12px 12px 5px;color:var(--muted);font-size:10px;font-weight:850;letter-spacing:.09em;text-transform:uppercase}.v57-loading-note{margin:10px 0;padding:10px 12px;border-radius:12px;background:var(--soft);color:var(--muted);font-size:12px}.v57-loading-card{min-height:220px;display:grid;place-items:center;padding:24px;border:1px solid var(--line);border-radius:18px;background:var(--card);text-align:center}.v57-loading-card p{color:var(--muted);font-size:13px}.bottom-item[data-v57-more] svg{width:22px;height:22px}
`;document.head.append(style)}
function navItem(view,label,help){return`<button class="v57-more-item" type="button" data-v57-go="${view}"><i>${icon(view)}</i><span><strong>${label}</strong><small>${help}</small></span><b>›</b></button>`}
function openMore(){document.querySelector('.v57-more-backdrop')?.remove();document.querySelector('.v57-more-sheet')?.remove();const role=state.me?.user?.role||'readonly',admin=['owner','admin'].includes(role),canBuy=['owner','admin','purchaser','approver'].includes(role),backdrop=document.createElement('div'),sheet=document.createElement('section');backdrop.className='v57-more-backdrop';sheet.className='v57-more-sheet';sheet.innerHTML=`<div class="v57-more-group"><span>Operación</span>${navItem('receiving','Recepción','Control de lo recibido')}${navItem('invoices','Facturas','Documentos y conciliación')}${navItem('approvals','Aprobaciones','Pendientes por autorizar')}</div><div class="v57-more-group"><span>Datos</span>${navItem('catalog','Productos','Catálogo y proveedores')}${navItem('suppliers','Proveedores','Condiciones e identidad')}${canBuy?navItem('operations','Estructura de compras','Centros, bodegas y recorrido'):''}</div><div class="v57-more-group"><span>Administración</span>${navItem('settings','Configuración','Empresa, locales y apariencia')}${admin?navItem('team','Usuarios','Roles y accesos'):''}${admin?navItem('audit','Auditoría','Cambios y trazabilidad'):''}</div>`;document.body.append(backdrop,sheet);const close=()=>{backdrop.remove();sheet.remove()};backdrop.onclick=close;sheet.querySelectorAll('[data-v57-go]').forEach(button=>button.onclick=()=>{const view=button.dataset.v57Go;close();openRoute(view,view==='operations'?'home':'').catch(error=>toast(error.message,'error'))})}
function organizeNavigation(){const nav=$('.side-nav[aria-label="Navegación principal"]');if(nav&&!nav.dataset.v61){nav.dataset.v61='1';const groups=[['COMPRAS',['dashboard','orders','receiving','history']],['GESTIÓN',['invoices','approvals','finance']],['DATOS',['catalog','suppliers','operations']]];for(const[label,views]of groups){const marker=document.createElement('span');marker.className='v57-nav-section';marker.textContent=label;nav.append(marker);for(const view of views){const item=nav.querySelector(`[data-view="${view}"]`);if(item)nav.append(item)}}const operations=nav.querySelector('[data-view="operations"]');const text=operations?.querySelector('span:last-child');if(text)text.textContent='Estructura de compras'}const bottom=$('.bottom-nav');if(!bottom)return;const more=bottom.querySelector('.bottom-item[data-view="settings"],.bottom-item[data-v57-more]');if(more&&!more.dataset.v57More){const clone=more.cloneNode(true);clone.removeAttribute('data-view');clone.dataset.v57More='1';clone.innerHTML=`<span>${icon('settings')}</span><small>Más</small>`;clone.onclick=event=>{event.preventDefault();event.stopPropagation();openMore()};more.replaceWith(clone)}}
function loadingWatch(){clearTimeout(loadingTimer);clearTimeout(slowTimer);document.querySelector('.v57-loading-note')?.remove();const root=$('#mainContent');if(!root||!/Cargando información|Cargando indicadores|Actualizando indicadores/i.test(root.textContent||''))return;const view=state.view,subview=state.subview;slowTimer=setTimeout(()=>{const current=$('#mainContent');if(!current||state.view!==view||state.subview!==subview)return;const note=document.createElement('div');note.className='v57-loading-note';note.textContent='Está demorando más de lo habitual. Nuvasto seguirá intentando sin cerrar la vista.';current.prepend(note)},5000);loadingTimer=setTimeout(()=>{const current=$('#mainContent');if(!current||state.view!==view||state.subview!==subview||!/Cargando información|Cargando indicadores|Actualizando indicadores/i.test(current.textContent||''))return;current.innerHTML='<div class="v57-loading-card"><div><h3>No se pudo completar la carga</h3><p>Puedes reintentar sin salir de Nuvasto.</p><button class="btn primary" id="v57RetryView">Reintentar</button></div></div>';$('#v57RetryView').onclick=()=>openRoute(view,subview||'',{replace:true}).catch(error=>toast(error.message,'error'))},12000)}
async function renderOperations(route={}){await renderOperationsAdmin(route.subview||'home')}
export function initializeRuntimeV57(){if(initialized)return;initialized=true;injectStyles();registerRouteRenderer('dashboard',renderDashboardV40);registerRouteRenderer('operations',renderOperations);organizeNavigation();window.addEventListener('pedidos:view-rendered',()=>{organizeNavigation();loadingWatch()})}
