import {$} from './app-core.js';
let initialized=false;
const documents={
  privacy:{eyebrow:'PRIVACIDAD',title:'Política de privacidad',version:'Versión 2.0 · agosto de 2026',sections:[
    ['Información utilizada','Nuvasto trata los datos necesarios para prestar el servicio: cuenta, empresa, locales, roles, pedidos, proveedores, facturas, recepciones, archivos, configuraciones, sesiones y registros de auditoría.'],
    ['Finalidad','Los datos se utilizan para autenticar usuarios, gestionar compras y abastecimiento, mantener trazabilidad, procesar documentos, generar reportes, prevenir errores y prestar soporte.'],
    ['Biometría y passkeys','Cuando activas acceso biométrico, Face ID, Touch ID, Windows Hello o el mecanismo equivalente es verificado localmente por tu dispositivo. Nuvasto no recibe ni almacena tu rostro, huella u otro dato biométrico; conserva únicamente una credencial criptográfica pública asociada a tu cuenta.'],
    ['Sesiones recordadas','Si eliges mantener la sesión iniciada, el dispositivo conserva el identificador de sesión para restaurar el acceso en aperturas posteriores. Puedes cerrar sesión o revocar sesiones y credenciales desde los controles disponibles.'],
    ['Inteligencia artificial','Cuando una función con IA está habilitada, ciertos documentos o datos operativos pueden procesarse por el proveedor configurado para extraer, clasificar o comparar información. Las decisiones operativas relevantes deben ser revisadas por una persona.'],
    ['Infraestructura y terceros','La plataforma puede utilizar servicios de infraestructura, almacenamiento, seguridad e inteligencia artificial, incluidos Cloudflare y Google/Gemini, según la configuración vigente de la organización.'],
    ['Conservación y acceso','La organización administradora define la vigencia de usuarios, documentos y registros conforme a sus necesidades operativas y obligaciones aplicables. Los accesos deben limitarse a personas autorizadas.']
  ]},
  terms:{eyebrow:'CONDICIONES',title:'Términos y condiciones de uso',version:'Versión 2.0 · agosto de 2026',sections:[
    ['Objeto del servicio','Nuvasto es una plataforma de apoyo para compras, abastecimiento, proveedores, recepción, documentos, pagos, reportes y trazabilidad operacional. El uso de la plataforma supone la aceptación de estas condiciones y de las políticas de la organización que administra la cuenta.'],
    ['Cuentas individuales y autorización','Cada usuario debe utilizar su propia cuenta, mantener sus medios de acceso bajo control y operar únicamente dentro de los roles, locales, centros de costo y permisos que le hayan sido asignados. Las acciones realizadas con una sesión válida se registran para fines de trazabilidad.'],
    ['Sesiones y dispositivos recordados','La opción “Mantener sesión iniciada” es voluntaria. Al activarla, el acceso puede permanecer disponible en ese dispositivo hasta que el usuario cierre sesión, un administrador revoque el acceso o cambien las condiciones de seguridad. No debe utilizarse en equipos públicos o compartidos.'],
    ['Acceso biométrico','El acceso biométrico mediante passkeys es opcional y depende de que el dispositivo y navegador sean compatibles. La verificación biométrica ocurre localmente en el dispositivo; Nuvasto valida una prueba criptográfica y no almacena información biométrica. La contraseña permanece como mecanismo de respaldo mientras la cuenta siga habilitada.'],
    ['Pedidos, pagos y documentos','Los usuarios son responsables de revisar cantidades, proveedores, fechas, folios, facturas, pagos, cheques, conciliaciones y demás información antes de emitir, aprobar o cerrar una operación. La plataforma facilita el proceso, pero no sustituye los controles internos de la organización.'],
    ['Inteligencia artificial','Las funciones de IA son herramientas de asistencia. La extracción y conciliación automática puede contener errores, especialmente frente a documentos incompletos, ilegibles o ambiguos. El usuario debe confirmar la información antes de incorporarla a registros definitivos o ejecutar decisiones de pago o compra.'],
    ['Disponibilidad y continuidad','La plataforma puede verse afectada por conectividad, mantenimiento, actualizaciones, servicios de terceros o eventos fuera del control razonable del operador. Se aplican medidas de continuidad y almacenamiento según la arquitectura disponible, sin garantía de operación ininterrumpida en todo momento.'],
    ['Uso adecuado y seguridad','No se permite intentar eludir controles de acceso, alterar registros de terceros, utilizar credenciales ajenas, automatizar abuso del servicio ni cargar contenido ilícito o ajeno a la operación autorizada. Los accesos comprometidos deben revocarse tan pronto como sea posible.'],
    ['Cambios y vigencia','Estas condiciones pueden actualizarse cuando cambien funcionalidades, requisitos de seguridad o condiciones operativas. La versión vigente se muestra dentro de Nuvasto. Acuerdos comerciales o contractuales específicos de una organización prevalecen cuando establezcan condiciones distintas.']
  ]},
  security:{eyebrow:'SEGURIDAD',title:'Seguridad y acceso',version:'Controles de seguridad · agosto de 2026',sections:[
    ['Acceso protegido','Las conexiones utilizan HTTPS y cada cuenta opera mediante sesiones individuales. Los roles y alcances por empresa o local limitan las acciones disponibles.'],
    ['Passkeys y biometría','Cuando el dispositivo lo permite, puedes registrar una passkey vinculada a Face ID, Touch ID, Windows Hello o al mecanismo de desbloqueo equivalente. La clave privada permanece protegida por el dispositivo y Nuvasto solo guarda la clave pública necesaria para verificar el acceso.'],
    ['Sesiones recordadas','Mantener sesión iniciada es opcional. Actívalo únicamente en dispositivos personales o controlados. Si pierdes el equipo, cierra o revoca la sesión desde otro dispositivo autorizado tan pronto como sea posible.'],
    ['Permisos y auditoría','Roles, organizaciones, locales y centros de costo delimitan el acceso. Operaciones sensibles generan trazabilidad para facilitar revisión y control administrativo.'],
    ['Archivos y documentos','Facturas, imágenes y archivos se almacenan en el repositorio configurado para la organización y se sirven mediante controles de acceso de la plataforma.'],
    ['Buenas prácticas','Usa una contraseña única, protege el desbloqueo del dispositivo, no compartas sesiones y elimina credenciales biométricas de equipos que ya no estén bajo tu control.']
  ]}
};
function injectStyles(){if($('#nuvastoLegalStyles'))return;const style=document.createElement('style');style.id='nuvastoLegalStyles';style.textContent='.auth-assurance{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:17px}.auth-assurance span{display:flex;align-items:center;justify-content:center;min-height:35px;padding:6px 8px;border:1px solid var(--line);border-radius:10px;background:var(--soft);color:var(--muted);font-size:8px;font-weight:800;text-align:center}.auth-legal{display:grid;gap:9px;margin-top:16px;padding-top:15px;border-top:1px solid var(--line);text-align:center}.auth-legal p{margin:0;color:var(--muted);font-size:8px;line-height:1.5}.auth-legal-links{display:flex;justify-content:center;flex-wrap:wrap;gap:6px 12px}.auth-legal-links button{border:0;background:transparent;color:var(--primary);font-size:8px;font-weight:850;text-decoration:underline}.public-legal-modal{width:min(720px,calc(100vw - 24px));max-height:82dvh;padding:0;border:1px solid var(--line);border-radius:22px;background:var(--card);color:var(--text)}.public-legal-modal::backdrop{background:rgba(3,8,18,.72);backdrop-filter:blur(8px)}.public-legal-frame{display:grid;grid-template-rows:auto minmax(0,1fr) auto;max-height:82dvh}.public-legal-head,.public-legal-foot{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 20px;border-bottom:1px solid var(--line)}.public-legal-foot{border-top:1px solid var(--line);border-bottom:0}.public-legal-body{display:grid;gap:10px;padding:16px 20px;overflow:auto}.public-legal-section{padding:14px;border:1px solid var(--line);border-radius:13px;background:var(--soft)}.public-legal-section h3{margin:0 0 6px;font-size:11px}.public-legal-section p{margin:0;color:var(--muted);font-size:10px;line-height:1.6}.public-legal-close{width:40px;height:40px;border:1px solid var(--line);border-radius:12px;background:var(--card);color:var(--text)}@media(max-width:520px){.auth-assurance{grid-template-columns:1fr}}';document.head.append(style)}
function ensureUi(){const card=$('#authScreen .auth-card');if(card&&!card.querySelector('.auth-assurance')){const assurance=document.createElement('div');assurance.className='auth-assurance';assurance.innerHTML='<span>Sesión cifrada</span><span>Acceso individual</span><span>Biometría local opcional</span>';const legal=document.createElement('div');legal.className='auth-legal';legal.innerHTML='<p>Al ingresar confirmas que estás autorizado por tu organización y aceptas las condiciones vigentes.</p><div class="auth-legal-links"><button type="button" data-public-legal="privacy">Privacidad</button><button type="button" data-public-legal="terms">Términos</button><button type="button" data-public-legal="security">Seguridad</button></div>';card.append(assurance,legal)}if(!$('#publicLegalModal')){const dialog=document.createElement('dialog');dialog.id='publicLegalModal';dialog.className='public-legal-modal';dialog.innerHTML='<article class="public-legal-frame"><header class="public-legal-head"><div><span class="eyebrow" id="publicLegalEyebrow"></span><h2 id="publicLegalTitle"></h2></div><button class="public-legal-close" type="button" data-public-legal-close aria-label="Cerrar">×</button></header><div class="public-legal-body" id="publicLegalBody"></div><footer class="public-legal-foot"><span id="publicLegalVersion"></span><button class="btn" type="button" data-public-legal-close>Entendido</button></footer></article>';document.body.append(dialog);dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});dialog.querySelectorAll('[data-public-legal-close]').forEach(button=>button.onclick=()=>dialog.close())}}
export function initializeLegalExperience(){if(initialized)return;initialized=true;injectStyles();ensureUi();document.addEventListener('click',event=>{const trigger=event.target.closest?.('[data-public-legal]');if(!trigger)return;const content=documents[trigger.dataset.publicLegal];if(!content)return;ensureUi();$('#publicLegalEyebrow').textContent=content.eyebrow;$('#publicLegalTitle').textContent=content.title;$('#publicLegalVersion').textContent=content.version;$('#publicLegalBody').innerHTML=content.sections.map(([title,text])=>`<section class="public-legal-section"><h3>${title}</h3><p>${text}</p></section>`).join('');$('#publicLegalModal').showModal()})}
