import {$,$$,state,api,toast} from './app-core.js';
import {ensureOrderDocument,shareDocument} from './app-file-actions.js';
import {openRoute} from './app-router-v14.js';

let initialized=false,queued=false,editingHydration='';
const selected=new Set();
const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const orderMap=()=>new Map((state.cache.orders||[]).map(order=>[order.id,order]));

function injectStyles(){if($('#r51Styles'))return;const style=document.createElement('style');style.id='r51Styles';style.textContent=`
.r51-bulkbar{position:sticky;top:8px;z-index:40;display:grid;grid-template-columns:minmax(0,1fr) repeat(3,auto);gap:7px;align-items:center;margin:0 0 10px;padding:9px;border:1px solid var(--line);border-radius:14px;background:color-mix(in srgb,var(--card) 94%,transparent);box-shadow:0 8px 28px rgba(15,23,42,.08);backdrop-filter:blur(16px)}.r51-bulkbar strong{font-size:10px}.r51-bulkbar small{display:block;color:var(--muted);font-size:7px;margin-top:2px}.r51-select{display:flex;align-items:center;justify-content:center;position:absolute;left:9px;top:9px;z-index:3;width:30px;height:30px;border:1px solid var(--line);border-radius:9px;background:var(--card)}.r51-select input{width:18px;height:18px;accent-color:var(--primary)}.history-order-row,.history-v18-card,.editable-supplier-row,.simple-order-card{position:relative}.history-order-row.r51-selectable,.editable-supplier-row.r51-selectable,.simple-order-card.r51-selectable{padding-left:48px!important}.history-v18-card.r51-selectable .history-v18-card-head{padding-left:52px}.r51-center-filter{min-width:160px}.r51-remove-line{margin-top:8px;width:100%;min-height:40px}.v30-item-card.r51-existing{border-color:color-mix(in srgb,var(--primary) 45%,var(--line))}.v30-item-card.r51-existing:before{content:'EN EL PEDIDO';display:inline-block;margin:9px 10px 0;padding:4px 7px;border-radius:999px;background:color-mix(in srgb,var(--primary) 10%,var(--card));color:var(--primary);font-size:7px;font-weight:950;letter-spacing:.08em}.r51-hidden{display:none!important}@media(max-width:620px){.r51-bulkbar{grid-template-columns:1fr 1fr}.r51-bulkbar>div{grid-column:1/-1}.r51-bulkbar .btn{min-height:42px}.r51-center-filter{width:100%}}
`;document.head.append(style)}

function fixBottomNav(){const nav=$('.bottom-nav');if(!nav)return;const receiving=nav.querySelector('[data-experience-view="receiving"]');if(receiving){const label=receiving.querySelector('small');if(label)label.textContent='Por emitir'}const history=nav.querySelector('[data-experience-view="history"]');if(history){const label=history.querySelector('small');if(label)label.textContent='Historial'}const items=[...nav.querySelectorAll('.bottom-item')];const historyItems=items.filter(item=>item.querySelector('small')?.textContent.trim()==='Historial');if(historyItems.length>1){const duplicate=historyItems.find(item=>item!==history);if(duplicate){duplicate.dataset.experienceView='receiving';delete duplicate.dataset.view;duplicate.querySelector('small').textContent='Por emitir'}}}

function orderIdFromNode(node){return node.querySelector?.('[data-order-id]')?.dataset.orderId||node.querySelector?.('[data-open-order]')?.dataset.openOrder||node.dataset?.v18Card||''}
function selectControl(node,id){if(!id||node.querySelector('.r51-select'))return;node.classList.add('r51-selectable');const label=document.createElement('label');label.className='r51-select';label.title='Seleccionar pedido';label.innerHTML=`<input type="checkbox" data-r51-order="${id}" ${selected.has(id)?'checked':''}>`;node.prepend(label);label.querySelector('input').onchange=event=>{event.stopPropagation();event.target.checked?selected.add(id):selected.delete(id);updateBulkBar()};label.onclick=event=>event.stopPropagation()}
function selectableNodes(){return [...$$('.history-order-row,.history-v18-card,.editable-supplier-row,.simple-order-card')].filter(node=>orderIdFromNode(node))}

function ensureBulkBar(){if(!['history','receiving'].includes(state.view)){$('#r51BulkBar')?.remove();selected.clear();return}const host=$('#mainContent');if(!host)return;let bar=$('#r51BulkBar');if(!bar){bar=document.createElement('section');bar.id='r51BulkBar';bar.className='r51-bulkbar';bar.innerHTML='<div><strong id="r51BulkCount">0 seleccionados</strong><small>Acciones agrupadas sobre pedidos visibles.</small></div><button class="btn" id="r51BulkShare" type="button">Compartir</button><button class="btn primary" id="r51BulkEmit" type="button">Emitir</button><button class="btn danger" id="r51BulkDelete" type="button">Eliminar</button>';const header=host.querySelector('.view-header')||host.firstElementChild;header?.insertAdjacentElement('afterend',bar);$('#r51BulkShare').onclick=()=>bulkShare();$('#r51BulkEmit').onclick=()=>bulkEmit();$('#r51BulkDelete').onclick=()=>bulkDelete()}selectableNodes().forEach(node=>selectControl(node,orderIdFromNode(node)));updateBulkBar()}
function updateBulkBar(){const count=$('#r51BulkCount');if(count)count.textContent=`${selected.size} seleccionado${selected.size===1?'':'s'}`;for(const id of ['r51BulkShare','r51BulkEmit','r51BulkDelete']){const button=$(`#${id}`);if(button)button.disabled=!selected.size}}
function selectedOrders(){const map=orderMap();return [...selected].map(id=>map.get(id)).filter(Boolean)}
async function bulkShare(){const orders=selectedOrders();if(!orders.length)return toast('Selecciona al menos un pedido','error');const button=$('#r51BulkShare');button.disabled=true;try{for(const order of orders){const document=await ensureOrderDocument(order);if(document?.key)await shareDocument(document.key,document.name)}toast(`${orders.length} pedido${orders.length===1?'':'s'} preparado${orders.length===1?'':'s'} para compartir`)}catch(error){toast(error.message,'error')}finally{button.disabled=false}}
async function bulkDelete(){const orders=selectedOrders();if(!orders.length)return;if(!confirm(`¿Eliminar ${orders.length} pedido${orders.length===1?'':'s'} seleccionado${orders.length===1?'':'s'}?`))return;const button=$('#r51BulkDelete');button.disabled=true;try{for(const order of orders){const force=order.publicState&&order.publicState!=='editing'?'?force=1':'';await api(`/api/orders/${encodeURIComponent(order.id)}${force}`,{method:'DELETE'})}selected.clear();state.cache.orders=[];toast('Pedidos eliminados');await openRoute(state.view==='receiving'?'receiving':'history','',{replace:true})}catch(error){toast(error.message,'error')}finally{button.disabled=false}}
async function bulkEmit(){const orders=selectedOrders().filter(order=>order.publicState==='editing');if(!orders.length)return toast('Selecciona pedidos que estén en edición','error');const batchIds=[...new Set(orders.map(order=>order.batchId).filter(Boolean))];if(!batchIds.length)return toast('Los pedidos seleccionados no pertenecen a un archivo emitible','error');if(!confirm(`¿Emitir ${orders.length} pedido${orders.length===1?'':'s'} seleccionado${orders.length===1?'':'s'}?`))return;const button=$('#r51BulkEmit');button.disabled=true;try{for(const batchId of batchIds)await api(`/api/order-batches/${encodeURIComponent(batchId)}/emit`,{method:'POST',json:{}});selected.clear();state.cache.orders=[];toast('Pedidos emitidos');await openRoute('receiving','',{replace:true})}catch(error){toast(error.message,'error')}finally{button.disabled=false}}

function receivingCenterFilter(){if(state.view!=='receiving')return;const toolbar=$('.ops-toolbar');if(!toolbar||$('#r51CenterFilter'))return;const centers=[...new Map((state.cache.orders||[]).map(order=>[order.costCenterId,{id:order.costCenterId,name:order.costCenterName||'Centro'}]).filter(([id])=>id)).values()];if(centers.length<2)return;const label=document.createElement('label');label.className='field r51-center-filter';label.innerHTML=`<span>Centro de costo</span><select id="r51CenterFilter"><option value="">Todos</option>${centers.map(center=>`<option value="${center.id}">${center.name}</option>`).join('')}</select>`;toolbar.append(label);$('#r51CenterFilter').onchange=filterReceivingByCenter}
function filterReceivingByCenter(){const value=$('#r51CenterFilter')?.value||'',map=orderMap();for(const node of $$('.editable-supplier-row,.simple-order-card')){const id=orderIdFromNode(node),order=map.get(id);node.classList.toggle('r51-hidden',Boolean(value&&order?.costCenterId!==value))}for(const batch of $$('.editable-batch-card')){const visible=[...batch.querySelectorAll('.editable-supplier-row')].some(row=>!row.classList.contains('r51-hidden'));batch.classList.toggle('r51-hidden',!visible)}}

async function hydrateEditOrder(){const title=$('#modalTitle')?.textContent?.trim()||'',subtitle=$('#modalSubtitle')?.textContent?.trim()||'';if(!title||!subtitle.includes('BORRADOR-')||!$('#v30EditProducts'))return;const key=`${title}|${subtitle}`;if(editingHydration===key)return;editingHydration=key;let summary=(state.cache.orders||[]).find(order=>subtitle.includes(order.folio));if(!summary){const payload=await api('/api/orders');state.cache.orders=payload.orders||[];summary=state.cache.orders.find(order=>subtitle.includes(order.folio))}if(!summary)return;const full=(await api(`/api/orders/${encodeURIComponent(summary.id)}`)).order||summary;const byName=new Map((full.items||[]).map(item=>[normalize(item.description),item]));for(const card of $$('#v30EditProducts [data-product]')){const name=card.querySelector('h4')?.textContent?.trim(),item=byName.get(normalize(name));if(!item)continue;card.classList.add('r51-existing');const qty=card.querySelector('[name=quantity]'),unit=card.querySelector('[name=unit]'),pack=card.querySelector('[name=pack]');if(qty&&!String(qty.value).trim())qty.value=String(item.quantityOrdered??item.quantity??'');if(unit&&item.orderUnit)unit.value=String(item.orderUnit).toUpperCase();if(pack&&item.unitsPerOrderUnit)pack.value=String(item.unitsPerOrderUnit);if(!card.querySelector('.r51-remove-line')){const remove=document.createElement('button');remove.type='button';remove.className='btn danger r51-remove-line';remove.textContent='Eliminar del pedido';remove.onclick=()=>{qty.value='0';qty.dispatchEvent(new Event('input',{bubbles:true}));card.classList.remove('r51-existing');card.style.opacity='.5';toast(`${name} marcado para eliminar`)};card.append(remove)}}}

function keyboardSafety(){for(const input of $$('[data-core-quantity]')){if(input.dataset.r51Keyboard)return;input.dataset.r51Keyboard='1';input.readOnly=false;input.disabled=false;input.type='text';input.inputMode='decimal';input.enterKeyHint='next';input.setAttribute('pattern','[0-9.,]*');input.addEventListener('pointerdown',()=>{input.readOnly=false;setTimeout(()=>{if(document.activeElement!==input)input.focus({preventScroll:true})},0)},{passive:true})}}

function enhance(){fixBottomNav();keyboardSafety();ensureBulkBar();receivingCenterFilter();filterReceivingByCenter();hydrateEditOrder().catch(error=>console.warn('r51_edit_hydration_failed',error))}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}
export function initializeR51UX(){if(initialized)return;initialized=true;injectStyles();window.addEventListener('pedidos:view-rendered',()=>{selected.clear();editingHydration='';schedule()});new MutationObserver(records=>{if(records.some(record=>record.addedNodes.length))schedule()}).observe(document.body,{subtree:true,childList:true});document.addEventListener('focusin',event=>{if(event.target?.matches?.('[data-core-quantity]'))keyboardSafety()});setTimeout(schedule,250)}
