import {$,$$,state,api,toast,setBusy,setTheme,syncMutations,updateSyncChip,showAuth,showApp,logoutLocal,isAdmin} from './app-core.js';
import {openBootstrap,openOrder,openWorkspaceSwitcher,handleAction} from './app-actions.js';
import {refreshBranding} from './app-branding.js';
import {openInitialRouteV14,openRoute} from './app-navigation-v14.js';
import {initializePlatform} from './app-bootstrap.js';

const CLIENT_RELEASE='2026.08.13.71';
const OFFLINE_WARM_KEY='nuvasto:offline-warm-v71';
document.documentElement.dataset.clientRelease=CLIENT_RELEASE;
const releaseFetch=window.fetch.bind(window);
initializePlatform();

let startupFinished=false,startupWatchdog=null;
function finishStartup(){startupFinished=true;if(startupWatchdog){clearTimeout(startupWatchdog);startupWatchdog=null}}
function recoverStartup(message='No pudimos restaurar la sesión automáticamente. Ingresa nuevamente para continuar.'){if(startupFinished)return;finishStartup();showAuth();const email=localStorage.getItem('nuvasto:last-email')||'';if($('#loginEmail')&&!$('#loginEmail').value)$('#loginEmail').value=email;toast(message,'error')}
startupWatchdog=setTimeout(()=>recoverStartup(navigator.onLine?'La restauración tardó demasiado. Mostramos el acceso para que puedas continuar.':'No hay datos offline suficientes para restaurar esta sesión. Conéctate una vez para actualizar Nuvasto.'),9000);
let releaseCheckPromise=null;
async function verifyClientRelease(){if(releaseCheckPromise)return releaseCheckPromise;releaseCheckPromise=(async()=>{try{const response=await releaseFetch(`/platform/release?client=${encodeURIComponent(CLIENT_RELEASE)}&ts=${Date.now()}`,{cache:'no-store'});if(!response.ok)return;const serverRelease=response.headers.get('X-Nuvasto-Release')||response.headers.get('X-Pedidos-Pro-Release')||'';if(!serverRelease||serverRelease===CLIENT_RELEASE){sessionStorage.removeItem('nuvasto:release-reload');return}if(sessionStorage.getItem('nuvasto:release-reload')===serverRelease)return;sessionStorage.setItem('nuvasto:release-reload',serverRelease);const registration=await navigator.serviceWorker?.getRegistration?.();await registration?.update?.().catch(()=>{});registration?.waiting?.postMessage?.({type:'SKIP_WAITING'});setTimeout(()=>location.reload(),420)}catch(error){console.warn('release_check_failed',error)}finally{setTimeout(()=>{releaseCheckPromise=null},30000)}})();return releaseCheckPromise}
function warmOfflineSnapshot(){if(!navigator.onLine||!state.token)return;const last=Number(localStorage.getItem(OFFLINE_WARM_KEY)||0);if(Date.now()-last<6*60*60*1000)return;localStorage.setItem(OFFLINE_WARM_KEY,String(Date.now()));const paths=['/api/locations','/api/cost-centers','/api/categories','/api/products','/api/suppliers','/api/settings'];Promise.allSettled(paths.map(path=>api(path,{persist:true,timeout:12000}))).then(results=>{if(results.every(result=>result.status==='rejected'))localStorage.removeItem(OFFLINE_WARM_KEY)}).catch(()=>localStorage.removeItem(OFFLINE_WARM_KEY))}

$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;if(!navigator.onLine){toast('Para iniciar una sesión nueva necesitas conexión. Las sesiones ya abiertas sí pueden restaurarse offline.','error');return}setBusy(button,true,'Ingresando…');try{const email=$('#loginEmail').value.trim();const response=await api('/api/auth/login',{method:'POST',timeout:15000,json:{email,password:$('#loginPassword').value}});state.token=response.token;localStorage.setItem('pp:token',state.token);localStorage.setItem('nuvasto:last-email',email);state.me=await api('/api/me',{fresh:true,persist:true,timeout:8000});try{await refreshBranding(true)}catch(error){console.warn('branding_load_failed',error)}showApp();finishStartup();warmOfflineSnapshot();verifyClientRelease();await openRoute('dashboard','',{replace:true});toast('Sesión iniciada')}catch(error){if(!error?.silent)toast(error.message,'error')}finally{setBusy(button,false)}});
$('#openBootstrap').onclick=openBootstrap;
$('#logoutButton').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST',json:{}})}catch{}logoutLocal()};
$('#primaryAction').onclick=()=>handleAction(state.view==='invoices'?'analyze-invoice':state.view==='catalog'?'new-product':state.view==='suppliers'?'new-supplier':state.view==='team'?'new-user':'new-order');
$('#mobileCreate').onclick=()=>openOrder();
$('#themeButton').onclick=()=>{const current=document.documentElement.dataset.theme;setTheme(current==='system'?'light':current==='light'?'dark':'system')};
$('#syncChip').onclick=syncMutations;
$('#workspaceCard').addEventListener('click',openWorkspaceSwitcher);$('#mobileWorkspaceButton').addEventListener('click',openWorkspaceSwitcher);$('#mobileUserButton').addEventListener('click',openWorkspaceSwitcher);
$('#globalSearch').addEventListener('focus',openCommand);$('#globalSearch').addEventListener('keydown',event=>{if(event.key==='Enter')openCommand()});
function openCommand(){$('#commandMenu').classList.remove('hidden');$('#commandInput').value='';renderCommands();setTimeout(()=>$('#commandInput').focus(),0)}
function renderCommands(){const query=$('#commandInput').value.toLowerCase(),commands=[['dashboard','Ir a Resumen'],['orders','Abrir pedidos'],['invoices','Ir a Documentos'],['history','Abrir historial'],['receiving','Abrir recepción'],['operations','Abrir Estructura de compras'],...(isAdmin()?[['professional','Control profesional Nuvasto'],['enterprise','Centro profesional y SaaS'],['team','Administrar usuarios'],['audit','Ver auditoría']]:[]),['settings','Abrir configuración']].filter(([,label])=>label.toLowerCase().includes(query));$('#commandResults').innerHTML=commands.map(([view,label])=>`<button class="command-result" data-command="${view}"><span>${label}</span><span>↵</span></button>`).join('');$$('[data-command]').forEach(node=>node.onclick=()=>{$('#commandMenu').classList.add('hidden');openRoute(node.dataset.command,node.dataset.command==='operations'?'home':'').catch(error=>{if(!error?.silent)toast(error.message,'error')})})}
$('#commandInput').addEventListener('input',renderCommands);$('#commandMenu').addEventListener('click',event=>{if(event.target===$('#commandMenu'))$('#commandMenu').classList.add('hidden')});document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();openCommand()}if(event.key==='Escape')$('#commandMenu').classList.add('hidden')});
window.addEventListener('online',()=>{state.online=true;updateSyncChip().catch(error=>console.warn('sync_chip_online_failed',error));syncMutations().catch(error=>console.warn('sync_recovery_failed',error));warmOfflineSnapshot();toast('Conexión recuperada')});window.addEventListener('offline',()=>{state.online=false;updateSyncChip().catch(()=>{});toast('Modo offline · usando datos guardados','error')});
if('serviceWorker'in navigator){navigator.serviceWorker.register(`./sw.js?release=${encodeURIComponent(CLIENT_RELEASE)}`,{updateViaCache:'none'}).catch(console.warn);navigator.serviceWorker.addEventListener('controllerchange',()=>{console.info('service_worker_updated');const key='nuvasto:controller-release';if(sessionStorage.getItem(key)!==CLIENT_RELEASE){sessionStorage.setItem(key,CLIENT_RELEASE);setTimeout(()=>location.reload(),80)}});navigator.serviceWorker.addEventListener('message',event=>{if(event.data?.type==='NUVASTO_SW_UPDATED'){console.info('nuvasto_assets_updated',event.data.version);verifyClientRelease()}})}
async function initialize(){updateSyncChip().catch(error=>console.warn('sync_chip_startup_failed',error));$('#openBootstrap').classList.add('hidden');if(!state.token){const email=localStorage.getItem('nuvasto:last-email')||'';if($('#loginEmail'))$('#loginEmail').value=email;showAuth();finishStartup();if(!navigator.onLine)toast('Offline disponible después de iniciar sesión al menos una vez con conexión y conservar la sesión.','error');return}try{state.me=await api('/api/me',{fresh:true,persist:true,timeout:7000})}catch(error){console.warn('session_restore_failed',error);if(error.status===401)logoutLocal();else recoverStartup(!navigator.onLine||error.code==='offline_cache_miss'?'No hay una sesión offline guardada para este dispositivo. Conéctate una vez para actualizarla.':error.code==='request_timeout'?'No fue posible validar la sesión a tiempo. Ingresa nuevamente para continuar.':'No se pudo restaurar la sesión. Ingresa nuevamente para continuar.');finishStartup();return}try{await refreshBranding(true)}catch(error){console.warn('branding_load_failed',error)}showApp();finishStartup();warmOfflineSnapshot();if(!navigator.onLine)toast('Modo offline · mostrando la última información disponible');verifyClientRelease();try{await openInitialRouteV14()}catch(error){if(!error?.silent){console.warn('initial_route_failed',error);await openRoute('dashboard','',{replace:true}).catch(()=>{});toast(navigator.onLine?'La sesión sigue activa. Reintenta cargar el panel.':'Esta vista todavía no tiene datos guardados para uso offline.','error')}}syncMutations().catch(error=>console.warn('sync_startup_failed',error))}
initialize().catch(error=>{console.error('startup_failed',error);recoverStartup('Ocurrió un error al iniciar Nuvasto. Ingresa nuevamente para continuar.')});