const VERSION='nuvasto-v69-offline-data';
const DATA_CACHE=`${VERSION}-data`;
const PRECACHE=['./','./styles.css','./pro-ui.css','./experience.css','./design-system-v13.css','./design-system-v14.css','./brand-v21.css','./native-performance.css','./app.js','./app-core.js','./app-data-worker.js','./app-bootstrap.js','./app-screen-state.js','./app-actions.js','./app-branding.js','./app-order-core.js','./app-company-logo.js','./app-procurement-settings.js','./app-procurement-entry.js','./app-file-actions.js','./app-settings-panels-v13.js','./app-telemetry-v13.js','./app-navigation-v14.js','./app-router-v14.js','./app-import-preview-v17.js','./app-sso-v20.js','./app-professional-v20.js','./app-nuvasto-v21.js','./app-checkout-invoice-v29.js','./app-legal.js','./app-professional.js','./app-ui-foundation.js','./app-orders.js','./app-catalog.js','./app-ui-enhancements.js','./app-documents.js','./app-ui-polish.js','./app-multi-invoice.js','./app-invoice-review.js','./app-enterprise.js','./app-procurement.js','./app-master-edit.js','./app-reception.js','./app-runtime.js','./app-mobile-runtime.js','./app-modal.js','./app-order-detail.js','./app-order-detail-v30.js','./app-v32-base.js','./manifest.webmanifest','./icon.svg','./nuvasto-mark.svg','./nuvasto-logo.svg'];
const RELEASE_ASSET=/\.(?:js|css|webmanifest)$/i;
const networkWithTimeout=(request,ms=7000)=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);return fetch(request,{cache:'no-store',signal:controller.signal}).finally(()=>clearTimeout(timer))};
function apiNetworkTimeout(request){const path=new URL(request.url).pathname;if(path==='/api/orders/advanced'||path.startsWith('/api/dashboard/analytics')||path.startsWith('/api/receptions/work-queue')||path.startsWith('/api/global-search'))return 32000;return 18000}
function safeResponse(response){return new Response(response.body,{status:response.status,statusText:response.statusText,headers:new Headers(response.headers)})}
function offlineResponse(response){const headers=new Headers(response.headers);headers.set('X-Nuvasto-Offline','1');headers.set('X-Nuvasto-Cache','offline-data');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
async function store(cache,request,response){if(response?.ok&&!response.redirected)await cache.put(request,response.clone());return response}
async function warmCriticalShell(){const cache=await caches.open(VERSION);await Promise.allSettled(PRECACHE.map(async path=>store(cache,path,await networkWithTimeout(path,12000))))}
async function sessionCacheKey(request){const auth=request.headers.get('Authorization')||'';if(!auth)return null;const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(auth));const suffix=[...new Uint8Array(bytes)].slice(0,10).map(value=>value.toString(16).padStart(2,'0')).join('');const url=new URL(request.url);url.searchParams.set('__nuvasto_session',suffix);return new Request(url.toString(),{method:'GET'})}
async function apiDataResponse(request){const key=await sessionCacheKey(request);if(!key)return networkWithTimeout(request,apiNetworkTimeout(request));const cache=await caches.open(DATA_CACHE);try{const response=await networkWithTimeout(request,apiNetworkTimeout(request));const type=response.headers.get('Content-Type')||'';if(response.ok&&type.includes('application/json'))await cache.put(key,response.clone());if(response.ok||response.status<500)return response;const cached=await cache.match(key);return cached?offlineResponse(cached):response}catch(error){const cached=await cache.match(key);if(cached)return offlineResponse(cached);const timedOut=error?.name==='AbortError',payload=timedOut?{ok:false,error:'La consulta tardó demasiado. Reintenta en unos segundos.',code:'request_timeout'}:{ok:false,error:'Sin conexión y sin datos guardados para esta vista',code:'offline_cache_miss'},headers={'Content-Type':'application/json; charset=utf-8'};if(!timedOut){headers['X-Nuvasto-Offline']='1';headers['X-Nuvasto-Cache']='miss'}return new Response(JSON.stringify(payload),{status:timedOut?504:503,headers})}}
async function releaseAssetResponse(cache,request){try{return await store(cache,request,await networkWithTimeout(request,9000))}catch{const cached=await cache.match(request,{ignoreSearch:true});return cached?safeResponse(cached):new Response('',{status:504})}}
self.addEventListener('install',event=>{event.waitUntil(warmCriticalShell().then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key!==VERSION&&key!==DATA_CACHE).map(key=>caches.delete(key)));await self.clients.claim();const windows=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of windows)client.postMessage({type:'NUVASTO_SW_UPDATED',version:VERSION})})())});
self.addEventListener('fetch',event=>{const request=event.request,url=new URL(request.url);if(request.method!=='GET')return;if(url.origin===self.location.origin&&url.pathname.startsWith('/api/')&&!url.pathname.startsWith('/api/files/')){event.respondWith(apiDataResponse(request));return}if(url.pathname==='/health'||url.pathname.startsWith('/platform/'))return;if(request.mode==='navigate'){event.respondWith(caches.open(VERSION).then(async cache=>{try{const response=await networkWithTimeout(request);if(!response.ok)return response;const safe=safeResponse(response);event.waitUntil(cache.put('./',safe.clone()));return safe}catch{const cached=await cache.match('./');return cached?safeResponse(cached):new Response('Sin conexión',{status:503})}}));return}if(url.origin!==self.location.origin)return;event.respondWith(caches.open(VERSION).then(async cache=>{if(RELEASE_ASSET.test(url.pathname))return releaseAssetResponse(cache,request);const cached=await cache.match(request,{ignoreSearch:true});if(cached)return cached;return networkWithTimeout(request,12000).then(response=>store(cache,request,response)).catch(()=>new Response('',{status:504}))}))});
self.addEventListener('push',event=>{let data={};try{data=event.data?.json?.()||{}}catch{data={message:event.data?.text?.()||'Nueva notificación'}}event.waitUntil(self.registration.showNotification(data.title||'Nuvasto',{body:data.message||data.body||'',icon:'./icon.svg',badge:'./icon.svg',data:{url:data.url||'./'}}))});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{const existing=list.find(client=>'focus'in client);if(existing){existing.navigate(event.notification.data?.url||'./');return existing.focus()}return clients.openWindow(event.notification.data?.url||'./')}))});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
