// Compatibilidad histórica: v17-readiness · v18-history-master-pdf · v19-workflow-r2 · v20-professional-sso · nuvasto-v21-brand-platform · nuvasto-v22-orders-pdf-motion · nuvasto-v23-auth-keyboard · nuvasto-v26-r2-invoice-keyboard · v28-regression-suite · nuvasto-v29-invoice-checkout-r2 · nuvasto-v30-reliability-mobile · v31-invoice-storage · v32-professional-ux · v33-history-documents · v34-folio-invoice-visual · v35-orders-clean-slate · v36-invoice-review-save-icons · v36-date-only-consistency · v38-multiple-invoices-per-order · v39-multi-picker-cache-navigation · v40-professional-operations · v41-reception-payments-enterprise · v42-reliable-emission-master-ordering · v43-fast-ux-process-navigation · v44-procurement-os-suite.
// Marcadores de compatibilidad exigidos por suites acumulativas: nuvasto-v39-multi-picker-cache-navigation · nuvasto-v40-professional-operations · nuvasto-v50-safari-navigation.
// R54 consolida selector nativo de historial y estabilidad táctil de lista maestra en iOS.
const VERSION='nuvasto-v54-mobile-consolidation';
const PRECACHE=[
  './','./styles.css','./pro-ui.css','./experience.css','./design-system-v13.css','./design-system-v14.css','./brand-v21.css','./native-performance.css','./app.js','./app-core.js','./app-r51-ux.js','./app-r52-operations.js','./app-r52-stability.js','./app-r54-consolidation.js','./app-v42-master-ordering.js','./app-experience-keyboard.js','./manifest.webmanifest','./icon.svg','./nuvasto-mark.svg','./nuvasto-logo.svg'
];
const OPTIONAL_ASSETS=[
  './','./index.html','./styles.css','./pro-ui.css','./experience.css','./design-system-v13.css','./design-system-v14.css','./brand-v21.css','./native-performance.css',
  './app.js','./app-core.js','./app-r51-ux.js','./app-r52-operations.js','./app-r52-stability.js','./app-r54-consolidation.js','./app-data-worker.js','./app-xlsx-worker-v45.js','./app-upload-v45.js','./app-screen-state-hotfix.js','./app-professional-hotfix-v24.js','./app-flow-stability-v27.js','./app-regression-guard-v28.js','./app-commercial-completion-v25.js','./app-r2-invoice-keyboard-v26.js','./app-checkout-invoice-v29.js','./app-checkout-upgrade-v29.js','./app-invoice-v29.js','./app-invoice-v30.js','./app-invoice-entry-v29.js','./app-runtime-v30.js','./app-orders-v30.js','./app-history-bridge-v31.js','./app-v32-entry.js','./app-v32-base.js','./app-v32-orders.js','./app-v32-catalog.js','./app-v32-enhancements.js','./app-v33-documents.js','./app-v34-polish.js','./app-v36-invoice-review.js','./app-multi-invoice-v38.js','./app-v39-stability.js','./app-v40-operations.js','./app-v41-enterprise.js','./app-v42-master-ordering.js','./app-v43-experience.js','./app-v44-procurement-os.js','./app-v44-master-edit.js','./app-v44-receiving-plus.js','./app-v29-ui.js','./app-views.js','./app-actions.js','./app-router-v14.js','./app-navigation-v14.js','./app-dashboard-v14.js','./app-enterprise-v15.js','./app-commercial-v16.js','./app-xlsx-v16.js','./app-readiness-v17.js','./app-import-preview-v17.js','./app-master-v18.js','./app-history-v18.js','./app-pdf-v18.js','./app-workflow-v19.js','./app-sso-v20.js','./app-professional-v20.js','./app-history-semantic-v20.js','./app-nuvasto-v21.js','./app-ux-v22.js','./app-nuvasto-v23.js',
  './app-modal.js','./app-order-detail.js','./app-order-detail-v30.js','./app-invoices.js','./app-branding.js','./app-order-core-v15.js','./app-company-logo.js','./app-procurement-settings.js','./app-procurement-entry.js','./app-experience.js','./app-experience-operations.js','./app-experience-settings.js','./app-experience-keyboard.js','./app-experience-admin.js','./app-file-actions.js','./app-assets-v13.js','./app-settings-panels-v13.js','./app-telemetry-v13.js','./manifest.webmanifest','./icon.svg','./nuvasto-mark.svg','./nuvasto-logo.svg'
];
const networkWithTimeout=(request,ms=5000)=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);return fetch(request,{cache:'no-store',signal:controller.signal}).finally(()=>clearTimeout(timer))};
function withoutRedirectMetadata(response){return new Response(response.body,{status:response.status,statusText:response.statusText,headers:new Headers(response.headers)})}
async function store(cache,request,response){if(response?.ok&&!response.redirected)await cache.put(request,response.clone());return response}
async function warmCriticalShell(){const cache=await caches.open(VERSION);await Promise.allSettled(PRECACHE.map(async path=>store(cache,path,await networkWithTimeout(path,12000))));}
self.addEventListener('install',event=>{event.waitUntil(warmCriticalShell().then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key!==VERSION).map(key=>caches.delete(key)));await self.clients.claim();const windows=await self.clients.matchAll({type:'window',includeUncontrolled:true});windows.forEach(client=>client.postMessage({type:'NUVASTO_SW_UPDATED',version:VERSION}))})())});
self.addEventListener('fetch',event=>{const request=event.request,url=new URL(request.url);if(request.method!=='GET'||url.pathname.startsWith('/api/')||url.pathname==='/health'||url.pathname.startsWith('/platform/'))return;if(request.mode==='navigate'){event.respondWith(caches.open(VERSION).then(async cache=>{try{const response=await networkWithTimeout(request);if(!response.ok)return response;const safe=withoutRedirectMetadata(response);event.waitUntil(cache.put('./',safe.clone()));return safe}catch{const cached=await cache.match('./');return cached?withoutRedirectMetadata(cached):new Response('Sin conexión',{status:503})}}));return}if(url.origin!==self.location.origin)return;event.respondWith(caches.open(VERSION).then(async cache=>{const cached=await cache.match(request);if(cached)return cached;return networkWithTimeout(request,12000).then(response=>store(cache,request,response)).catch(()=>new Response('',{status:504}))}))});
self.addEventListener('push',event=>{let data={};try{data=event.data?.json?.()||{}}catch{data={message:event.data?.text?.()||'Nueva notificación'}}event.waitUntil(self.registration.showNotification(data.title||'Nuvasto',{body:data.message||data.body||'',icon:'./icon.svg',badge:'./icon.svg',data:{url:data.url||'./'}}))});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{const existing=list.find(client=>'focus'in client);if(existing){existing.navigate(event.notification.data?.url||'./');return existing.focus()}return clients.openWindow(event.notification.data?.url||'./')}))});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
