import aiWorker from './index.js';
import platformWorker from '../../professional/worker/src/router.js';

const PLATFORM_RELEASE='2026.08.15.78';
function rewritePath(request,pathname){const url=new URL(request.url);url.pathname=pathname;return new Request(url.toString(),request)}
function isAiRoute(pathname){return pathname==='/health'||pathname.startsWith('/v1/')}
function withPlatformRelease(response){const headers=new Headers(response.headers);headers.set('X-Nuvasto-Release',PLATFORM_RELEASE);headers.set('X-Pedidos-Pro-Release',PLATFORM_RELEASE);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function releaseResponse(){return new Response(JSON.stringify({ok:true,service:'nuvasto-release',release:PLATFORM_RELEASE}),{headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
async function platformHealthResponse(request,env,ctx){const response=await platformWorker.fetch(rewritePath(request,'/health'),env,ctx),payload=await response.clone().json().catch(()=>null);if(!response.ok||!payload)return withPlatformRelease(response);const r2Configured=Boolean(env.FILES),r2Required=String(env.REQUIRE_R2||'').toLowerCase()==='true',headers=new Headers(response.headers);headers.set('Content-Type','application/json; charset=utf-8');headers.set('Cache-Control','no-store');return withPlatformRelease(new Response(JSON.stringify({...payload,r2Configured,r2Required,r2Ready:r2Configured,storageBackend:r2Configured?'r2':'unavailable',catalogMemorySafetyV81:true,productInsightsV81:true,manualPriceIntegrityV81:true,financeDashboardV81:true}),{status:response.status,statusText:response.statusText,headers}))}
export default{async fetch(request,env,ctx){const url=new URL(request.url);if(isAiRoute(url.pathname))return aiWorker.fetch(request,env,ctx);if(url.pathname==='/platform/release')return withPlatformRelease(releaseResponse());if(url.pathname==='/platform/health')return platformHealthResponse(request,env,ctx);return withPlatformRelease(await platformWorker.fetch(request,env,ctx))}};