import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const html=read('web/index.html');
const css=read('web/design-system-native-v80.css');
const mobile=read('web/app-mobile-runtime.js');
const auth=read('web/app-auth-experience.js');
assert.match(html,/viewport-fit=cover/,'PWA must opt into device safe areas');
assert.match(html,/id="modalClose"[^>]+aria-label="Cerrar"/,'modal close control needs accessible name');
assert.match(html,/aria-label="Navegación móvil"/,'mobile primary navigation needs accessible name');
assert.match(css,/min-height:44px!important/,'interactive controls must preserve at least 44px touch height');
assert.match(css,/prefers-reduced-motion:reduce/,'reduced motion must be honored');
assert.match(css,/prefers-reduced-transparency:reduce/,'reduced transparency must be honored');
assert.match(css,/safe-area-inset-bottom/,'bottom chrome must respect home indicator safe area');
assert.match(mobile,/safe-area-inset-top/,'modal chrome must respect status bar and Dynamic Island safe area');
assert.match(mobile,/safe-area-inset-left/,'landscape/notch safe area must be supported');
assert.match(auth,/aria-label=\"Ingresar con biometría\"/,'biometric icon must retain an accessible label');
assert.match(auth,/setAttribute\('aria-busy'/,'biometric busy state must be announced');
console.log('v84 accessibility + mobile chrome gate: OK');
