import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(path,'utf8');
const app=read('web/app.js');
const entry=read('web/app-professional.js');
const runtime=read('web/app-runtime.js');
const mobile=read('web/app-mobile-runtime.js');
const master=read('web/app-master-v18.js');
const files=read('web/app-file-actions.js');
const orders=read('web/app-orders.js');
const catalog=read('web/app-catalog.js');
const sw=read('web/sw.js');
assert.equal((app.match(/window\.fetch\s*=/g)||[]).length,0,'app.js must not wrap global fetch');
assert.ok(entry.includes("from './app-orders.js'")&&entry.includes("from './app-catalog.js'"),'professional bootstrap must use semantic modules');
assert.ok(runtime.includes("registerRouteRenderer('dashboard'")&&runtime.includes("registerRouteRenderer('operations'"),'canonical runtime must own dashboard and operations');
assert.ok(master.includes('v18-master-nav{display:none!important}'),'legacy custom keyboard must remain disabled');
assert.ok(!master.includes("addEventListener('focusin'")&&!master.includes("addEventListener('keydown'"),'master list must not steal native focus');
assert.ok(!files.includes('IntersectionObserver')&&!files.includes('MutationObserver'),'sharing must be explicit and must not scan DOM');
assert.ok(orders.includes("order.status==='draft'")&&orders.includes("order.status!=='draft'&&order.status!=='cancelled'"),'orders and history must be separated at source');
assert.ok(orders.includes('data-v57-order-actions')&&!orders.includes('data-v43-order-menu'),'order actions must be native and canonical');
assert.equal((catalog.match(/data-v32-photo=/g)||[]).length,1,'product card must expose one photo action');
assert.ok((mobile.match(/MutationObserver/g)||[]).length<=1&&mobile.includes("observe(body,{subtree:true,childList:true})"),'mobile observer must be modal-scoped');
assert.ok(sw.includes('nuvasto-v59-semantic-modules'),'service worker must use semantic module cache');
console.log('canonical runtime regression gate: OK');
