import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(path,'utf8');
const orders=read('web/app-orders.js'),catalog=read('web/app-catalog.js'),files=read('web/app-file-actions.js'),professional=read('web/app-professional.js'),runtime=read('web/app-runtime.js'),mobile=read('web/app-mobile-runtime.js'),bootstrap=read('web/app-bootstrap.js'),procurement=read('web/app-procurement-settings.js'),orderCore=read('web/app-order-core-v15.js'),reception=read('web/app-reception.js'),routes=read('worker/src/routes/procurement.js'),entry=read('web/app-procurement-entry.js'),invoiceEntry=read('web/app-invoice-entry-v29.js'),operations=read('worker/src/api/operations-v40.js'),folios=read('worker/src/api/folio-integrity-v34.js'),orderFile=read('worker/src/api/order-core-v4.js'),ordersQuery=read('worker/src/api/orders-query.js'),workerCore=read('worker/src/worker-core.js'),sw=read('web/sw.js'),telemetry=read('web/app-telemetry-v13.js');
assert.ok(orders.includes("new Set(['closed','cancelled'])")&&orders.includes("view:history?'history':'active'")&&orders.includes('Solo pedidos cerrados o anulados'),'Pedidos must contain active work while Historial contains terminal operations only');
assert.ok(ordersQuery.includes("view==='history'")&&ordersQuery.includes("o.status IN ('closed','cancelled')")&&ordersQuery.includes("o.status NOT IN ('closed','cancelled')"),'server query must enforce mutually exclusive operational ledgers');
assert.ok(ordersQuery.includes('cursorValue')&&ordersQuery.includes('nextCursor')&&ordersQuery.includes('limit+1'),'large order histories must use cursor pagination');
assert.ok(!ordersQuery.includes('o.cost_center_id')&&ordersQuery.includes('occ.cost_center_id'),'order reads must use the canonical order_cost_centers relation only');
assert.ok(orders.includes('data-v67-order-actions')&&orders.includes('<select'),'order action control must be a native select in operational and history views');
assert.ok(orders.includes("action.startsWith('state:')")&&orders.includes("/transition`"),'operational orders must expose canonical state transitions');
assert.ok(orders.includes("received:[['reconciled','Marcar conciliado']]")&&orders.includes("reconciled:[['closed','Cerrar pedido']]") ,'closure must follow reconciliation instead of bypassing it');
assert.ok(!orders.includes('v57BulkShare')&&orders.includes('navigator.share({title:`${files.length} pedido'),'draft bulk actions must not share and emitted batches must share independent PDF files');
assert.equal((catalog.match(/data-v32-photo=/g)||[]).length,1,'catalog product card must expose exactly one photo action');
assert.ok(!files.includes('IntersectionObserver')&&!files.includes('MutationObserver'),'PDF generation/share must never preload from the file action module or DOM observers');
assert.ok(professional.includes("from './app-orders.js'")&&professional.includes("from './app-catalog.js'")&&professional.includes("from './app-reception.js'"),'professional bootstrap must use semantic feature owners');
assert.ok(!invoiceEntry.includes('initializeOrdersV30')&&!invoiceEntry.includes("app-orders-v30.js"),'invoice entry must not register a legacy order screen');
assert.ok(!bootstrap.includes('initializeMasterV18')&&!bootstrap.includes("app-master-v18.js"),'legacy master-list DOM observer must stay out of bootstrap');
assert.ok(runtime.includes("registerRouteRenderer('dashboard'")&&runtime.includes("registerRouteRenderer('operations'")&&runtime.includes('Estructura de compras'),'runtime must own clear navigation semantics');
assert.ok((mobile.match(/MutationObserver/g)||[]).length<=1&&mobile.includes("modalObserver.observe(body,{subtree:true,childList:true})"),'the only mobile observer must be modal-scoped');
assert.ok(!mobile.includes('applyConfiguredMasterOrder')&&!mobile.includes('section.append(row)'),'mobile runtime must never reorder mounted quantity rows');
assert.ok(mobile.includes('unit.tabIndex=-1')&&mobile.includes('supplier.tabIndex=-1'),'keyboard accessory traversal must skip order format and supplier selectors');
assert.ok(mobile.includes('keepQuantityVisible')&&mobile.includes('visualViewport')&&mobile.includes('scrollIntoView'),'arrow navigation must scroll the master list with the focused quantity');
assert.ok(orderCore.includes('groupProductsByConfiguredOrder(visible,activeConfig)'),'master ordering must happen before row render');
assert.ok(orderCore.includes('if(relations.length<=1)')&&orderCore.includes('<select data-order-relation>'),'products with multiple suppliers must render a supplier select');
assert.ok(mobile.includes('.order-file-supplier:has(select[data-order-relation])')&&mobile.includes('max-width:150px!important'),'mobile layout must expose a compact multi-supplier selector');
assert.ok(mobile.includes('.order-file-category>.order-file-row:nth-of-type(even)'),'master-list readability must use alternating theme-aware rows');
assert.ok(orderCore.includes('function focusNext(current)')&&orderCore.includes('[data-core-quantity]'),'next traversal must remain quantity-based');
assert.ok(procurement.includes('mergeCanonicalProductOrder')&&procurement.includes("fresh:true")&&procurement.includes("/api/master-list-ordering?costCenterId=")&&procurement.includes("method:'PUT'")&&procurement.includes('Productos dentro del recorrido'),'configured order must be refreshed, restored, editable and persisted in one canonical flow');
assert.ok(runtime.includes('.v40-dashboard-head')&&runtime.includes('.v40-chart-line')&&runtime.includes('.v40-donut'),'dashboard must retain professional visual components and charts');
assert.ok(!entry.includes('MutationObserver'),'procurement settings entry must not observe the full app DOM');
assert.ok(!reception.includes('MutationObserver'),'reception enhancement must not observe the entire DOM');
assert.ok(routes.includes("path==='/api/master-list-ordering'"),'master ordering must expose the canonical unversioned endpoint');
assert.ok(folios.includes('CREATE TABLE IF NOT EXISTS folio_sequences')&&folios.includes('allocateScopedFoliosV66')&&folios.includes("padStart(5,'0')"),'folios must persist a five-digit monotonic sequence per scope');
assert.ok(folios.includes('order_folio_aliases')&&folios.includes('folio_migrations')&&folios.includes('migrateLegacyFoliosV67'),'legacy folios must migrate once while retaining a searchable alias');
assert.ok(!folios.includes('COALESCE(occ.cost_center_id,o.cost_center_id)')&&folios.includes('LEFT JOIN cost_centers cc ON cc.id=occ.cost_center_id'),'folio migration must use the canonical center relation');
assert.ok(operations.includes('order_cost_centers occ')&&operations.includes('cost_center_id')&&operations.includes('allocateScopedFoliosV66'),'emission must allocate folios from the local plus cost-center scope');
assert.ok(orderFile.includes('BORRADOR-')&&!orderFile.includes('getUTCFullYear'),'draft creation must not consume or embed calendar dates in emitted folio logic');
assert.ok(workerCore.includes('listOrdersCanonical')&&workerCore.includes('migrateLegacyFoliosV67'),'canonical worker must own paginated order reads and historical folio cutover');
assert.ok(workerCore.includes("url.pathname==='/api/orders'")&&workerCore.includes("url.pathname==='/api/order-batches'")&&workerCore.includes('createCanonicalBatchFromLegacy'),'legacy creation endpoints must be routed through the canonical no-date folio flow');
assert.ok(workerCore.includes('legacyDateFoliosRetired:true')&&workerCore.includes('canonicalOrderDetailV67:true'),'health must expose the canonical order cutover contract');
assert.ok(workerCore.includes('ensureReleaseDataV67')&&workerCore.includes('folioMigrationV67:migration.ready'),'production health must complete the one-time historical folio migration before declaring r67 ready');
assert.ok(workerCore.includes('canonicalOrderDetail')&&workerCore.includes('batchId:meta?.batch_id'),'order detail must expose batch identity so draft bulk emission does not need a legacy route');
assert.ok(ordersQuery.includes('payment_schedules')&&ordersQuery.includes('paymentState'),'order queue must expose payment and overdue state without extra browser requests');
assert.ok(sw.includes('RELEASE_ASSET')&&sw.includes('releaseAssetResponse'),'release assets must be network-first so iOS cannot remain pinned to an old module graph');
assert.ok(telemetry.includes('BUDGET_KEY')&&telemetry.includes('DAY_LIMIT=100000')&&telemetry.includes("status&&status!=='ok'"),'request budget diagnostics must be local, bounded and count failures correctly');
console.log('functional contracts: OK');
