import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const auth=read('worker/src/auth.js');
const procurement=read('web/app-procurement-settings.js');
const catalog=read('web/app-catalog.js');
const master=read('web/app-master-order.js');
assert.match(auth,/export async function bootstrap/,'platform must support first organization bootstrap');
assert.match(auth,/export async function createUser/,'organization admins must be able to create users');
assert.match(auth,/validateLocationScope/,'new users must receive an explicit location scope');
assert.match(procurement,/Recorrido de Lista Maestra/,'onboarding must expose one canonical procurement configuration flow');
assert.match(procurement,/Define formatos, bodegas, categorías y productos desde un único editor/,'procurement onboarding must describe the unified traversal editor');
assert.match(procurement,/api\('\/api\/locations'\)/,'procurement setup must load locations');
assert.match(procurement,/api\('\/api\/cost-centers'\)/,'procurement setup must load cost centers');
assert.match(procurement,/api\('\/api\/categories'\)/,'procurement setup must load categories');
assert.match(procurement,/api\('\/api\/products'\)/,'procurement setup must load products');
assert.match(procurement,/Guardar configuración/,'procurement setup must persist warehouse/category/product traversal');
assert.match(catalog,/supplier/i,'catalog must expose supplier relationships');
assert.match(master,/Guardar archivo/,'master order must expose a persistent save action');
console.log('v84 onboarding readiness gate: OK');
