import assert from 'node:assert/strict';

const base=(process.env.NUVASTO_BASE_URL||'https://pedidos-pro-ai.botreservasmultilocal.workers.dev').replace(/\/$/,'');
const email=process.env.NUVASTO_E2E_EMAIL||'';
const password=process.env.NUVASTO_E2E_PASSWORD||'';
if(!email||!password){console.log('production v44 synthetic journey: SKIPPED (dedicated NUVASTO_E2E_EMAIL / NUVASTO_E2E_PASSWORD not configured)');process.exit(0)}
let token='';
async function call(path,{method='GET',json,headers={}}={}){const response=await fetch(`${base}${path}`,{method,headers:{...(token?{Authorization:`Bearer ${token}`}:{ }),...(json?{'Content-Type':'application/json'}:{}),...headers},body:json?JSON.stringify(json):undefined});const payload=await response.json().catch(()=>({}));if(!response.ok||payload.ok===false)throw new Error(`${method} ${path} · ${response.status} · ${payload.error||'request failed'}`);return payload}
const today=new Date().toISOString().slice(0,10),delivery=new Date(Date.now()+86400000).toISOString().slice(0,10),stamp=Date.now().toString(36).toUpperCase();
const login=await call('/api/auth/login',{method:'POST',json:{email,password}});token=login.token;assert.ok(token,'login token');
const [me,locations,centers,products]=await Promise.all([call('/api/me'),call('/api/locations'),call('/api/cost-centers'),call('/api/products')]);assert.equal(me.ok,true);const location=(locations.locations||[]).find(item=>item.active!==false),center=(centers.costCenters||[]).find(item=>item.locationId===location?.id&&item.active!==false);assert.ok(location&&center,'dedicated E2E tenant needs an active location and cost center');
const product=(products.products||[]).find(item=>item.active!==false&&(item.costCenters||[]).some(cc=>cc.id===center.id)&&(item.suppliers||[]).some(rel=>rel.id));assert.ok(product,'dedicated E2E tenant needs one active product linked to a supplier');const relation=product.suppliers.find(rel=>rel.id);
const batch=await call('/api/order-batches/v2',{method:'POST',headers:{'Idempotency-Key':`v44-e2e-${stamp}`},json:{locationId:location.id,costCenterId:center.id,deliveryMode:'all',deliveryDate:delivery,notes:`Synthetic E2E ${stamp}`,items:[{supplierProductId:relation.id,quantity:1,orderUnit:relation.orderUnit||'UNIDAD',unitsPerOrderUnit:Number(relation.unitsPerOrderUnit||1)}]}});const order=batch.batch?.orders?.[0]||batch.orders?.[0];assert.ok(order?.id&&batch.batchId||batch.batch?.batchId,'order batch created');const batchId=batch.batchId||batch.batch?.batchId;
const emitted=await call(`/api/order-batches/${encodeURIComponent(batchId)}/emit`,{method:'POST',json:{}});assert.equal(emitted.documentsReady,true,'PDF documents must be ready before emission completes');
const orderPayload=await call(`/api/orders/${encodeURIComponent(order.id)}`),fullOrder=orderPayload.order,item=fullOrder.items?.[0];assert.ok(item?.id,'emitted order item');
const document=await call(`/api/orders/${encodeURIComponent(order.id)}/pdf`,{method:'POST',json:{}});assert.ok(document.document?.key,'order PDF archived');
const invoiceNumber=`E2E-${stamp}`;const unitPrice=Math.max(100,Number(relation.lastGrossUnitPrice||1000));const invoice=await call('/api/invoices',{method:'POST',json:{supplierId:fullOrder.supplierId,invoiceNumber,documentType:'33',invoiceDate:today,locationId:location.id,orderIds:[order.id],currency:'CLP',totals:{net:Math.round(unitPrice/1.19),vat:unitPrice-Math.round(unitPrice/1.19),total:unitPrice},lines:[{productId:product.id,sourceDescription:`E2E ${product.name}`,packageQty:1,packSize:1,units:1,netLineTotal:Math.round(unitPrice/1.19),taxLineTotal:unitPrice-Math.round(unitPrice/1.19),grossLineTotal:unitPrice,grossUnitPrice:unitPrice,confidence:1,matchMethod:'synthetic-e2e'}]}});assert.ok(invoice.invoice?.id,'invoice associated');
const reception=await call(`/api/orders/${encodeURIComponent(order.id)}/receptions`,{method:'POST',headers:{'Idempotency-Key':`v44-reception-${stamp}`},json:{receivedAt:today,deliveryNoteNumber:`E2E-${stamp}`,notes:'Synthetic production reception',expectedRevision:Number(fullOrder.revision||1),historicalDateConfirmed:false,items:[{orderItemId:item.id,quantityAccepted:1,quantityRejected:0}]}});assert.ok(reception.reception?.id,'reception recorded');
const reconciliation=await call(`/api/orders/${encodeURIComponent(order.id)}/reconcile-three-way`);assert.ok(reconciliation.reconciliation,'three-way reconciliation available');
const [master,intelligence,planning,health]=await Promise.all([call('/api/master-data-v44?entity=products&status=active'),call('/api/procurement-intelligence-v44'),call('/api/finance-planning-v44'),call('/api/procurement-os-v44/summary')]);assert.ok(Array.isArray(master.items));assert.ok(intelligence.intelligence);assert.ok(planning.planning);assert.equal(health.summary?.capabilities?.globalSearch,true);
console.log(`production v44 synthetic journey: OK · ${order.folio||order.id} · ${invoiceNumber}`);
