import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const root=path=>fs.readFileSync(new URL(`../../${path}`,import.meta.url),'utf8');
const app=read('web/app.js');
const auth=read('web/app-auth-experience.js');
const bootstrap=read('web/app-bootstrap.js');
const sw=read('web/sw.js');
const invoice=read('worker/src/invoice-pricing-matrix.js');
const normalizer=read('worker/src/invoice-normalizer.js');
const passkeys=read('worker/src/api/passkeys.js');
const router=read('worker/src/router.js');
const payments=read('web/app-payment-workflow.js');
const workerCombined=root('worker/src/combined.js');

assert.match(app,/CLIENT_RELEASE='2026\.08\.18\.90'/,'client release must identify the v90 invoice cutover');
assert.match(workerCombined,/PLATFORM_RELEASE='2026\.08\.18\.90'/,'platform release must match the v90 client release');
assert.match(app,/OFFLINE_WARM_KEY='nuvasto:offline-warm-v90'/,'v90 must refresh the offline operating snapshot after cutover');
assert.match(app,/app-session-bootstrap\.js/,'session bootstrap must remain canonical');
assert.match(auth,/isUserVerifyingPlatformAuthenticatorAvailable/,'platform biometric availability detection is required');
assert.match(auth,/biometricIcon\(\)/,'biometric login must be icon based');
assert.match(auth,/navigator\.credentials\.get/,'passkey login is required');
assert.match(auth,/navigator\.credentials\.create/,'passkey enrollment is required');
assert.doesNotMatch(auth,/location\.reload\s*\(/,'biometric login must not reload the PWA');
assert.doesNotMatch(bootstrap,/app-sso-v20\.js/,'retired Cloudflare Access SSO must stay inactive');
assert.match(passkeys,/passkey_credentials/,'passkey persistence must remain active');
assert.match(passkeys,/passkey_user_verification_required/,'passkeys must require user verification');
assert.match(router,/passkeyAuthV72:true/,'passkey capability flag must remain exposed');
assert.match(router,/adaptiveInvoicePriceMatrixV78:true/,'adaptive invoice matrix capability must remain exposed');
assert.match(router,/sessionIdleExpiryV87:true/,'idle session expiry must remain exposed');
assert.match(invoice,/printed-final-unit-column/,'supplier printed final unit price remains highest-confidence path');
assert.match(invoice,/printed-line-sum-matrix/,'v83 invoice sum inference must remain active');
assert.match(invoice,/invoice-line-component-matrix/,'component matrix fallback must remain active');
assert.match(normalizer,/reconcileInvoicePricing/,'invoice normalization must use canonical pricing reconciliation');
assert.match(sw,/CACHE_VERSION='nuvasto-v90-truthful-invoice-transition'/,'current service worker cache must rotate for v90');
assert.match(sw,/PREVIOUS_CACHE_VERSION='nuvasto-v89-brand-launch'/,'v90 must identify prior v89 cache');
assert.match(sw,/LEGACY_CACHE_VERSION_V88='nuvasto-v88-ai-reconciliation-extras'/,'v90 must preserve v88 cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V85='nuvasto-v85-self-service-readiness'/,'v90 must preserve v85 cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V84='nuvasto-v84-professional-readiness'/,'v90 must preserve v84 cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V83='nuvasto-v83-mobile-auth-invoice'/,'v90 must preserve v83 cache lineage');
assert.match(sw,/app-readiness-v85\.js/,'self-service readiness module must remain available offline');
assert.match(sw,/app-location-identity\.js/,'location identity module must be available offline');
assert.doesNotMatch(sw,/'\.\/app-procurement\.js'/,'noncritical procurement bundle must stay out of install precache');
assert.match(payments,/openPaymentDocumentComposer/,'payment document workflow must remain available');
assert.match(payments,/openCollectivePayment/,'collective payment workflow must remain available');
assert.doesNotMatch(payments,/MutationObserver/,'payment workflow must not observe the whole DOM');
console.log('v83-v90 canonical release contracts: OK');
