import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const root=path=>fs.readFileSync(new URL(`../../${path}`,import.meta.url),'utf8');
const app=read('web/app.js');
const auth=read('web/app-auth-experience.js');
const bootstrap=read('web/app-bootstrap.js');
const sw=read('web/sw.js');
const invoice=read('worker/src/invoice-pricing-matrix.js');
const normalizer=read('worker/src/invoice-normalizer.js');
const passkeys=read('worker/src/api/passkeys.js');
const router=read('worker/src/router.js');
const payments=read('web/app-payment-workflow.js');
const workerCombined=root('worker/src/combined.js');

const clientRelease=app.match(/CLIENT_RELEASE='([^']+)'/)?.[1]||'';
const platformRelease=workerCombined.match(/PLATFORM_RELEASE='([^']+)'/)?.[1]||'';
const releaseNumber=clientRelease.split('.').at(-1)||'';
assert.equal(clientRelease,'2026.08.19.96','v96 client release must be explicit');
assert.equal(platformRelease,clientRelease,'client and platform release handshake must always match');
assert.match(sw,new RegExp(`CACHE_VERSION='nuvasto-v${releaseNumber}-`),'service worker cache must rotate with the active release number');
assert.match(app,/OFFLINE_WARM_KEY='nuvasto:offline-warm-v96'/,'v96 must refresh the offline operating snapshot');
assert.match(app,/registration\.update\(\)/,'release mismatch must explicitly check for a new service worker');
assert.match(app,/controllerchange/,'client must wait for the new service worker to control the page before reloading');
assert.doesNotMatch(app,/setTimeout\(\(\)=>location\.reload\(\),420\)/,'client must not blindly reload before service worker activation');
assert.match(app,/app-session-bootstrap\.js/,'session bootstrap must remain canonical');
assert.match(auth,/isUserVerifyingPlatformAuthenticatorAvailable/,'platform biometric availability detection is required');
assert.match(auth,/biometricIcon\(\)/,'biometric login must be icon based');
assert.match(auth,/navigator\.credentials\.get/,'passkey login is required');
assert.match(auth,/navigator\.credentials\.create/,'passkey enrollment is required');
assert.doesNotMatch(auth,/location\.reload\s*\(/,'biometric login must not reload the PWA');
assert.doesNotMatch(bootstrap,/app-sso-v20\.js/,'retired Cloudflare Access SSO must stay inactive');
assert.match(passkeys,/passkey_credentials/,'passkey persistence must remain active');
assert.match(passkeys,/passkey_user_verification_required/,'passkeys must require user verification');
assert.match(router,/passkeyAuthV72:true/,'passkey capability flag must remain exposed');
assert.match(router,/adaptiveInvoicePriceMatrixV78:true/,'adaptive invoice matrix capability must remain exposed');
assert.match(router,/sessionIdleExpiryV87:true/,'idle session expiry must remain exposed');
assert.match(invoice,/printed-final-unit-column/,'supplier printed final unit price remains highest-confidence path');
assert.match(invoice,/printed-line-sum-matrix/,'v83 invoice sum inference must remain active');
assert.match(invoice,/invoice-line-component-matrix/,'component matrix fallback must remain active');
assert.match(normalizer,/reconcileInvoicePricing/,'invoice normalization must use canonical pricing reconciliation');
assert.match(sw,/CACHE_VERSION='nuvasto-v96-release-coherence'/,'current service worker cache must rotate for the v96 release-coherence cutover');
assert.match(sw,/PREVIOUS_CACHE_VERSION='nuvasto-v95-safe-area-contract'/,'v96 must identify the previous v95 cache');
assert.match(sw,/LEGACY_CACHE_VERSION_V94='nuvasto-v94-menu-information-architecture'/,'v96 must preserve the v94 menu cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V93='nuvasto-v93-branding-launch'/,'v96 must preserve the v93 branding cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V91='nuvasto-v91-production-stability'/,'v96 must preserve the v91 runtime cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V90='nuvasto-v90-truthful-invoice-transition'/,'v96 must preserve v90 cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V89='nuvasto-v89-brand-launch'/,'v96 must preserve v89 cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V88='nuvasto-v88-ai-reconciliation-extras'/,'v96 must preserve v88 cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V85='nuvasto-v85-self-service-readiness'/,'v96 must preserve v85 cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V84='nuvasto-v84-professional-readiness'/,'v96 must preserve v84 cache lineage');
assert.match(sw,/LEGACY_CACHE_VERSION_V83='nuvasto-v83-mobile-auth-invoice'/,'v96 must preserve v83 cache lineage');
assert.match(sw,/Promise\.all\(PRECACHE\.map/,'critical release assets must install atomically');
assert.match(sw,/precache_failed:/,'failed critical assets must abort activation instead of producing a mixed shell');
assert.match(sw,/client\.navigate\(client\.url\)/,'activated v96 worker must force open legacy clients onto the coherent shell');
assert.match(sw,/safe-area-v95\.css/,'safe-area contract must be available offline');
assert.match(sw,/app-navigation-v14\.js/,'canonical navigation must be available offline');
assert.match(sw,/app-suppliers-v94\.js/,'supplier workspace must be available offline');
assert.match(sw,/app-company-profile-v94\.js/,'company profile must be available offline');
assert.match(sw,/app-readiness-v85\.js/,'self-service readiness module must remain available offline');
assert.match(sw,/app-location-identity\.js/,'location profile module must be available offline');
assert.doesNotMatch(sw,/'\.\/app-procurement\.js'/,'noncritical procurement bundle must stay out of install precache');
assert.match(payments,/openPaymentDocumentComposer/,'payment document workflow must remain available');
assert.match(payments,/openCollectivePayment/,'collective payment workflow must remain available');
assert.doesNotMatch(payments,/MutationObserver/,'payment workflow must not observe the whole DOM');
console.log('v83-v96 canonical release contracts: OK · client/server/cache coherent · atomic PWA cutover');
