import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const [schema,migration,readiness,catalogV17,scoped,center,preview,enterprise,serviceWorker]=await Promise.all([
  readFile(new URL('../worker/src/schema.js',import.meta.url),'utf8'),readFile(new URL('../migrations/0007_commercial_readiness_v17.sql',import.meta.url),'utf8'),readFile(new URL('../worker/src/api/readiness-v17.js',import.meta.url),'utf8'),readFile(new URL('../worker/src/api/catalog-workbook-v17.js',import.meta.url),'utf8'),readFile(new URL('../worker/src/index-scoped.js',import.meta.url),'utf8'),readFile(new URL('../web/app-readiness-v17.js',import.meta.url),'utf8'),readFile(new URL('../web/app-import-preview-v17.js',import.meta.url),'utf8'),readFile(new URL('../web/app-enterprise-v15.js',import.meta.url),'utf8'),readFile(new URL('../web/sw.js',import.meta.url),'utf8')
]);

assert.match(schema,/SCHEMA_VERSION='(?:17|18|19|20|21|32)'/);assert.match(schema,/0007_commercial_readiness_v17\.sql/);
for(const pattern of [/CREATE TABLE IF NOT EXISTS readiness_runs/,/CREATE TABLE IF NOT EXISTS onboarding_progress/,/CREATE TABLE IF NOT EXISTS catalog_import_snapshots/,/CREATE TABLE IF NOT EXISTS support_tickets/,/CREATE TABLE IF NOT EXISTS legal_documents/,/CREATE TABLE IF NOT EXISTS legal_acceptances/])assert.match(migration,pattern);
for(const feature of ['commercialReadinessV17','recordQaRunV17','runIsolationAuditV17','runInvoiceBenchmarkV17','saveOnboardingV17','manageSubscriptionV17','verifyRecoveryV17','createSupportTicketV17','saveLegalV17','acceptLegalV17'])assert.match(readiness,new RegExp(feature));assert.match(readiness,/targetSample:100/);assert.match(readiness,/targetScore:80/);
for(const feature of ['previewCatalogWorkbookV17','commitCatalogWorkbookV17','snapshotCatalog','restoreCatalogSnapshotV17','catalog_import_snapshots'])assert.match(catalogV17,new RegExp(feature));
for(const path of ['/api/readiness/qa','/api/readiness/isolation','/api/readiness/benchmark','/api/readiness/onboarding','/api/readiness/recovery','/api/readiness/support','/api/readiness/legal','/api/catalog/import-workbook/preview'])assert.match(scoped,new RegExp(path.replaceAll('/','\\/')));assert.match(scoped,/catalogRestorePoints:true/);assert.match(scoped,/commercialReadinessCenter:true/);
for(const label of ['PRUEBA INTEGRAL','IMPORTACIÓN SEGURA','BENCHMARK IA','MULTIEMPRESA','ONBOARDING','PLANES Y COBRO','RECUPERACIÓN','SOPORTE','DOCUMENTACIÓN LEGAL'])assert.match(center,new RegExp(label,'i'));assert.match(center,/WebKit|userAgent/);assert.match(center,/14 días/);assert.match(preview,/Generar vista previa/);assert.match(preview,/Crear respaldo y aplicar/);assert.match(preview,/punto de recuperación automático/);assert.match(enterprise,/Preparación comercial/);assert.match(enterprise,/9 módulos/);assert.match(serviceWorker,/(?:v17-readiness|v18-history-master-pdf|v19-workflow-r2|v20-professional-sso|nuvasto-v21-brand-platform|nuvasto-v22-orders-pdf-motion|nuvasto-v23-auth-keyboard|nuvasto-v23-screen-state-hotfix|nuvasto-v26-r2-invoice-keyboard|nuvasto-v29-invoice-checkout-r2|nuvasto-v32-professional-ux)/);assert.match(serviceWorker,/app-readiness-v17\.js/);assert.match(serviceWorker,/app-import-preview-v17\.js/);

console.log('workflow v17 commercial readiness compatibility through schema 32: OK');
