import {HttpError,ROLES,assertMinimumRole,integer,nowIso,number,optionalText,readJson,requireText,uuid} from '../core.js';
import {writeAudit} from '../auth.js';
import {linkExistingFile,recordSnapshot} from '../storage.js';

function locationAllowed(actor,locationId){return actor.locationScope?.includes?.('*')||actor.locationScope?.includes?.(locationId)}
function freeSignal(raw={}){const description=String(raw.sourceDescription||raw.sourceLine||raw.descriptionOriginal||raw.description||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase(),explicit=raw.isFree===true||raw.isFree===1||String(raw.isFree).toLowerCase()==='true',discount=Number(raw.discountPct||0)>=99.5,zeroValue=Number(raw.units??raw.totalUnits??0)>0&&Number(raw.grossLineTotal||0)===0&&Number(raw.netLineTotal||0)===0,keyword=/\b(SIN CARGO|BONIFICACION|BONIF|GRATIS|MUESTRA|PROMOCIONAL|CORTESIA)\b/.test(description);return explicit||discount||zeroValue||keyword}
function normalizeAlias(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function safeJson(value,fallback={}){try{return JSON.parse(value||'')}catch{return fallback}}

export async function createInvoiceV2(request,env,actor){
  assertMinimumRole(actor.role,ROLES.RECEIVER);const body=await readJson(request),supplierId=String(body.supplierId||''),supplier=await env.DB.prepare('SELECT id,name FROM suppliers WHERE id=? AND org_id=? AND active=1').bind(supplierId,actor.orgId).first();if(!supplier)throw new HttpError(400,'Proveedor inválido','invalid_supplier');
  const invoiceNumber=requireText(body.invoiceNumber,'Número de documento',{max:80}),documentType=optionalText(body.documentType||'33',{max:10}),invoiceDate=requireText(body.invoiceDate,'Fecha del documento',{max:20}),duplicate=await env.DB.prepare('SELECT id FROM invoices WHERE org_id=? AND supplier_id=? AND document_type=? AND invoice_number=?').bind(actor.orgId,supplierId,documentType,invoiceNumber).first();if(duplicate)throw new HttpError(409,'Este documento ya fue registrado','duplicate_invoice');
  const sourceLines=Array.isArray(body.lines)?body.lines:[];if(!sourceLines.length)throw new HttpError(400,'El documento no contiene líneas','empty_invoice');if(sourceLines.length>1000)throw new HttpError(400,'El documento supera 1.000 líneas','too_many_items');
  const totals=body.totals||{},orderIds=[...new Set((Array.isArray(body.orderIds)?body.orderIds:[]).map(String).filter(Boolean))],locationIds=new Set();if(!orderIds.length){const locationId=String(body.locationId||''),location=await env.DB.prepare('SELECT id FROM locations WHERE id=? AND org_id=? AND active=1').bind(locationId,actor.orgId).first();if(!location||!locationAllowed(actor,location.id))throw new HttpError(400,'Selecciona un local válido','invalid_location');locationIds.add(location.id)}
  const invoiceId=uuid(),timestamp=nowIso(),currency=optionalText(body.currency||'CLP',{max:10}),organization=await env.DB.prepare('SELECT settings_json FROM organizations WHERE id=?').bind(actor.orgId).first(),orgSettings=safeJson(organization?.settings_json,{}),alertThreshold=Math.max(.1,Math.min(100,Number(orgSettings.priceAlerts?.thresholdPct||5))),statements=[env.DB.prepare(`INSERT INTO invoices(id,org_id,supplier_id,invoice_number,document_type,invoice_date,currency,net_total,tax_total,additional_tax_total,freight_total,gross_total,status,ai_model,ai_confidence,reviewed_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'review',?,?,?,?,?)`).bind(invoiceId,actor.orgId,supplierId,invoiceNumber,documentType,invoiceDate,currency,integer(totals.net,{min:0,max:9999999999}),integer(totals.vat??totals.tax,{min:0,max:9999999999}),integer(totals.additionalTax,{min:0,max:9999999999}),integer(totals.freight,{min:0,max:9999999999}),integer(totals.total,{min:0,max:9999999999}),optionalText(body.aiModel,{max:100}),number(body.aiConfidence,{min:0,max:1}),actor.userId,timestamp,timestamp)];
  let freeLineCount=0,learnedAliases=0,priceAlertCount=0;
  for(const[index,raw]of sourceLines.entries()){
    const lineId=uuid(),productId=raw.productId?String(raw.productId):null;if(productId){const product=await env.DB.prepare('SELECT id FROM products WHERE id=? AND org_id=?').bind(productId,actor.orgId).first();if(!product)throw new HttpError(400,`Producto inválido en línea ${index+1}`,'invalid_product')}
    const isFree=freeSignal(raw);if(isFree)freeLineCount++;const totalUnits=number(raw.units??raw.totalUnits,{min:0,max:10000000}),grossLineTotal=isFree?0:integer(raw.grossLineTotal,{min:0,max:9999999999}),grossUnitPrice=isFree?0:integer(raw.grossUnitPrice||(totalUnits?grossLineTotal/totalUnits:0),{min:0,max:999999999}),reviewStatus=productId?'confirmed':'unmatched',freeReason=isFree?optionalText(raw.freeReason||raw.notes||'Producto sin cargo o bonificado',{max:240}):'',sourceDescription=requireText(raw.sourceDescription||raw.sourceLine||raw.descriptionOriginal||raw.description,`Descripción línea ${index+1}`,{max:500});
    statements.push(env.DB.prepare(`INSERT INTO invoice_lines(id,invoice_id,supplier_product_id,product_id,source_description,supplier_sku,package_quantity,units_per_package,total_units,net_line_total,tax_line_total,additional_tax_line_total,gross_line_total,gross_unit_price,match_confidence,match_method,review_status,is_free,free_reason,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(lineId,invoiceId,raw.supplierProductId||null,productId,sourceDescription,optionalText(raw.supplierSku||raw.code,{max:100}),number(raw.packageQty??raw.invoiceQuantity,{min:0,max:1000000}),number(raw.packSize,{min:.001,max:100000,fallback:1}),totalUnits,isFree?0:integer(raw.netLineTotal,{min:0,max:9999999999}),isFree?0:integer(raw.vatLine??raw.taxLineTotal,{min:0,max:9999999999}),isFree?0:integer(raw.additionalTaxLine??raw.additionalTaxLineTotal,{min:0,max:9999999999}),grossLineTotal,grossUnitPrice,number(raw.confidence??raw.matchConfidence,{min:0,max:1}),optionalText(raw.matchMethod||'human-review',{max:80}),reviewStatus,isFree?1:0,freeReason,timestamp,timestamp));
    if(productId){const normalized=normalizeAlias(sourceDescription);if(normalized){learnedAliases++;statements.push(env.DB.prepare(`INSERT INTO product_aliases(id,org_id,supplier_id,product_id,alias,normalized_alias,source,confidence,usage_count,last_used_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,'invoice-review',?,1,?,?,?,?) ON CONFLICT(org_id,supplier_id,normalized_alias) DO UPDATE SET product_id=excluded.product_id,alias=excluded.alias,confidence=MAX(product_aliases.confidence,excluded.confidence),usage_count=product_aliases.usage_count+1,last_used_at=excluded.last_used_at,updated_at=excluded.updated_at`).bind(uuid(),actor.orgId,supplierId,productId,sourceDescription,normalized,number(raw.confidence??raw.matchConfidence,{min:0,max:1,fallback:1}),invoiceDate,actor.userId,timestamp,timestamp))}}
    if(productId&&grossUnitPrice>0&&!isFree){const previous=await env.DB.prepare(`SELECT gross_unit_price FROM price_history WHERE org_id=? AND supplier_id=? AND product_id=? ORDER BY observed_at DESC,created_at DESC LIMIT 1`).bind(actor.orgId,supplierId,productId).first(),previousPrice=Number(previous?.gross_unit_price||0),changePct=previousPrice?((grossUnitPrice-previousPrice)/previousPrice)*100:0;statements.push(env.DB.prepare(`INSERT INTO price_history(id,org_id,supplier_id,product_id,invoice_id,gross_unit_price,currency,observed_at,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(uuid(),actor.orgId,supplierId,productId,invoiceId,grossUnitPrice,currency,invoiceDate,timestamp));statements.push(env.DB.prepare(`UPDATE supplier_products SET last_gross_unit_price=?,last_purchased_at=?,updated_at=? WHERE org_id=? AND supplier_id=? AND product_id=?`).bind(grossUnitPrice,invoiceDate,timestamp,actor.orgId,supplierId,productId));if(previousPrice&&changePct>=alertThreshold){priceAlertCount++;statements.push(env.DB.prepare(`INSERT INTO price_alerts(id,org_id,product_id,supplier_id,invoice_id,previous_price,current_price,change_pct,threshold_pct,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,'open',?)`).bind(uuid(),actor.orgId,productId,supplierId,invoiceId,previousPrice,grossUnitPrice,changePct,alertThreshold,timestamp))}}
  }
  for(const orderId of orderIds){const order=await env.DB.prepare('SELECT id,location_id FROM orders WHERE id=? AND org_id=? AND supplier_id=?').bind(orderId,actor.orgId,supplierId).first();if(!order||!locationAllowed(actor,order.location_id))throw new HttpError(400,'Pedido relacionado inválido','invalid_order');locationIds.add(order.location_id);statements.push(env.DB.prepare('INSERT INTO invoice_order_links(id,org_id,invoice_id,order_id,created_at) VALUES(?,?,?,?,?)').bind(uuid(),actor.orgId,invoiceId,orderId,timestamp))}
  for(const locationId of locationIds)statements.push(env.DB.prepare('INSERT OR IGNORE INTO invoice_location_links(invoice_id,org_id,location_id,created_at) VALUES(?,?,?,?)').bind(invoiceId,actor.orgId,locationId,timestamp));
  await env.DB.batch(statements);if(body.sourceFileId){await env.DB.prepare('UPDATE invoices SET pdf_file_id=?,updated_at=? WHERE id=? AND org_id=?').bind(String(body.sourceFileId),nowIso(),invoiceId,actor.orgId).run();await linkExistingFile(env,actor,{fileId:String(body.sourceFileId),entityType:'invoice',entityId:invoiceId,documentKind:'invoice_original',revision:1,metadata:{invoiceNumber,documentType,freeLineCount}})}
  await recordSnapshot(env,actor,{entityType:'invoice',entityId:invoiceId,locationId:[...locationIds][0]||null,revision:1,snapshot:{...body,id:invoiceId,supplierName:supplier.name,locationIds:[...locationIds],freeLineCount,learnedAliases,priceAlertCount}});await writeAudit(env,actor,request,'invoice.create','invoice',invoiceId,{supplierId,invoiceNumber,documentType,lines:sourceLines.length,freeLineCount,learnedAliases,priceAlertCount,orderIds});return{id:invoiceId,supplierId,supplierName:supplier.name,invoiceNumber,documentType,invoiceDate,status:'review',grossTotal:integer(totals.total,{min:0}),lineCount:sourceLines.length,freeLineCount,learnedAliases,priceAlertCount};
}
