import {HttpError,ROLES,assertMinimumRole,nowIso,optionalText,readJson,uuid,sha256} from '../core.js';
import {writeAudit} from '../auth.js';
import {readStoredBytes} from '../storage.js';

const rows=result=>result?.results||[];
const safeJson=(value,fallback={})=>{try{return JSON.parse(value||'')}catch{return fallback}};
const admin=actor=>assertMinimumRole(actor.role,ROLES.ADMIN);
const clamp=value=>Math.max(0,Math.min(100,Number(value||0)));
const isoDate=value=>{const date=value?new Date(value):new Date();return Number.isNaN(date.getTime())?new Date().toISOString():date.toISOString()};

async function recordRun(env,actor,{type,status,score,result={},device={}}){
  const id=uuid(),createdAt=nowIso();
  await env.DB.prepare(`INSERT INTO readiness_runs(id,org_id,run_type,status,score,result_json,device_json,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(id,actor.orgId,type,status,clamp(score),JSON.stringify(result),JSON.stringify(device),actor.userId,createdAt).run();
  return{id,type,status,score:clamp(score),result,device,createdAt};
}

async function basicCounts(env,actor){
  const queries={
    locations:'SELECT COUNT(*) AS total FROM locations WHERE org_id=? AND active=1',
    centers:'SELECT COUNT(*) AS total FROM cost_centers WHERE org_id=? AND active=1',
    users:`SELECT COUNT(*) AS total FROM memberships WHERE org_id=? AND active=1`,
    suppliers:'SELECT COUNT(*) AS total FROM suppliers WHERE org_id=? AND active=1',
    products:'SELECT COUNT(*) AS total FROM products WHERE org_id=? AND active=1',
    orders:'SELECT COUNT(*) AS total FROM orders WHERE org_id=?',
    invoices:'SELECT COUNT(*) AS total FROM invoices WHERE org_id=?',
    aliases:'SELECT COUNT(*) AS total FROM product_aliases WHERE org_id=?',
    backups:`SELECT COUNT(*) AS total FROM workspace_backups WHERE org_id=? AND status='ready'`,
    support:`SELECT COUNT(*) AS total FROM support_tickets WHERE org_id=? AND status IN ('open','in_progress')`,
    legal:`SELECT COUNT(DISTINCT document_type) AS total FROM legal_documents WHERE org_id=? AND status='published'`
  };
  const output={};
  await Promise.all(Object.entries(queries).map(async([key,sql])=>{const row=await env.DB.prepare(sql).bind(actor.orgId).first();output[key]=Number(row?.total||0)}));
  return output;
}

async function subscriptionState(env,actor){
  const row=await env.DB.prepare('SELECT * FROM subscriptions WHERE org_id=?').bind(actor.orgId).first();
  return row?{id:row.id,provider:row.provider,plan:row.plan_code,status:row.status,amount:Number(row.amount||0),currency:row.currency||'CLP',periodStart:row.current_period_start,periodEnd:row.current_period_end,trialEndsAt:row.trial_ends_at,cancelAtPeriodEnd:Boolean(row.cancel_at_period_end)}:{id:null,provider:'manual',plan:'free',status:'active',amount:0,currency:'CLP',periodStart:null,periodEnd:null,trialEndsAt:null,cancelAtPeriodEnd:false};
}

async function latestRuns(env,actor){const result=await env.DB.prepare(`SELECT r.* FROM readiness_runs r JOIN(SELECT run_type,MAX(created_at) AS latest FROM readiness_runs WHERE org_id=? GROUP BY run_type)x ON x.run_type=r.run_type AND x.latest=r.created_at WHERE r.org_id=? ORDER BY r.created_at DESC`).bind(actor.orgId,actor.orgId).all();return rows(result).map(row=>({id:row.id,type:row.run_type,status:row.status,score:Number(row.score||0),result:safeJson(row.result_json,{}),device:safeJson(row.device_json,{}),createdAt:row.created_at}))}

async function onboardingState(env,actor){const row=await env.DB.prepare('SELECT * FROM onboarding_progress WHERE org_id=?').bind(actor.orgId).first();return row?{currentStep:Number(row.current_step||1),completed:safeJson(row.completed_json,{}),updatedAt:row.updated_at}:{currentStep:1,completed:{},updatedAt:null}}

export async function commercialReadinessV17(env,actor){
  admin(actor);
  const[counts,subscription,runs,onboarding,organization]=await Promise.all([basicCounts(env,actor),subscriptionState(env,actor),latestRuns(env,actor),onboardingState(env,actor),env.DB.prepare('SELECT name,settings_json FROM organizations WHERE id=?').bind(actor.orgId).first()]);
  const settings=safeJson(organization?.settings_json,{}),runMap=new Map(runs.map(run=>[run.type,run]));
  const modules=[
    {id:'qa',title:'Prueba integral',ready:runMap.get('qa')?.status==='passed',detail:runMap.get('qa')?`${Math.round(runMap.get('qa').score)}% · ${runMap.get('qa').status}`:'Sin ejecución registrada'},
    {id:'import',title:'Importación segura',ready:Boolean(settings.commercial?.lastImportPreviewAt),detail:settings.commercial?.lastImportPreviewAt?'Vista previa y punto de recuperación activos':'Ejecuta una vista previa de Excel'},
    {id:'benchmark',title:'Benchmark de cotejo',ready:Number(runMap.get('benchmark')?.result?.sampleSize||0)>=100&&Number(runMap.get('benchmark')?.score||0)>=80,detail:runMap.get('benchmark')?`${runMap.get('benchmark').result.sampleSize||0} líneas · ${Math.round(runMap.get('benchmark').score)}%`:'Sin benchmark'},
    {id:'isolation',title:'Aislamiento multiempresa',ready:runMap.get('isolation')?.status==='passed',detail:runMap.get('isolation')?`${Math.round(runMap.get('isolation').score)}% · ${runMap.get('isolation').status}`:'Sin auditoría'},
    {id:'onboarding',title:'Onboarding automático',ready:counts.locations>0&&counts.centers>0&&Boolean(settings.business?.legalName||settings.business?.rut),detail:`${counts.locations} locales · ${counts.centers} centros · ${counts.users} usuarios`},
    {id:'billing',title:'Planes y cobro',ready:subscription.plan!=='free'||subscription.status==='trialing',detail:`${subscription.plan} · ${subscription.status}`},
    {id:'recovery',title:'Recuperación',ready:counts.backups>0&&runMap.get('recovery')?.status==='passed',detail:`${counts.backups} respaldos listos`},
    {id:'support',title:'Soporte y observabilidad',ready:Boolean(settings.commercial?.supportEmail)&&counts.support===0,detail:counts.support?`${counts.support} tickets abiertos`:(settings.commercial?.supportEmail||'Correo de soporte pendiente')},
    {id:'legal',title:'Documentación legal',ready:counts.legal>=2,detail:`${counts.legal}/3 documentos publicados`}
  ];
  const score=Math.round(modules.filter(item=>item.ready).length/modules.length*100);
  return{score,ready:score===100,organization:{name:organization?.name||'',supportEmail:settings.commercial?.supportEmail||'',business:settings.business||{},branding:settings.branding||{}},counts,subscription,onboarding,runs,modules};
}

export async function recordQaRunV17(request,env,actor){
  admin(actor);const body=await readJson(request),manual=Array.isArray(body.checks)?body.checks:[],counts=await basicCounts(env,actor),automated=[
    {id:'location',label:'Existe un local activo',passed:counts.locations>0},
    {id:'center',label:'Existe un centro de costo activo',passed:counts.centers>0},
    {id:'catalog',label:'Catálogo cargado',passed:counts.products>0&&counts.suppliers>0},
    {id:'users',label:'Existe al menos un usuario activo',passed:counts.users>0}
  ],checks=[...automated,...manual.map(item=>({id:String(item.id||uuid()),label:optionalText(item.label,{max:180})||'Verificación manual',passed:Boolean(item.passed),note:optionalText(item.note,{max:500})}))];
  const passed=checks.filter(item=>item.passed).length,score=checks.length?passed/checks.length*100:0,status=score===100?'passed':score>=70?'warning':'failed',run=await recordRun(env,actor,{type:'qa',status,score,result:{checks,passed,total:checks.length},device:body.device||{}});await writeAudit(env,actor,request,'readiness.qa','organization',actor.orgId,{status,score,device:body.device||{}});return run;
}

export async function runIsolationAuditV17(request,env,actor){
  admin(actor);const directTables=['locations','cost_centers','categories','suppliers','products','supplier_products','orders','invoices','files','document_links','memberships','workspace_backups','support_tickets','legal_documents','legal_acceptances','readiness_runs'],checks=[];
  for(const table of directTables){try{const info=await env.DB.prepare(`PRAGMA table_info(${table})`).all(),columns=rows(info).map(column=>column.name),hasOrg=columns.includes('org_id');let scoped=true,foreignRows=0;if(hasOrg){const own=await env.DB.prepare(`SELECT COUNT(*) AS total FROM ${table} WHERE org_id=?`).bind(actor.orgId).first(),all=await env.DB.prepare(`SELECT COUNT(*) AS total FROM ${table}`).first();foreignRows=Math.max(0,Number(all?.total||0)-Number(own?.total||0));scoped=true}checks.push({table,hasOrgId:hasOrg,parentScoped:!hasOrg,foreignRows,passed:hasOrg||['order_items','invoice_lines'].includes(table)&&scoped})}catch(error){checks.push({table,passed:false,error:error.message})}}
  const passed=checks.filter(item=>item.passed).length,score=checks.length?passed/checks.length*100:0,status=score===100?'passed':score>=85?'warning':'failed',run=await recordRun(env,actor,{type:'isolation',status,score,result:{checks,tenantCount:Number((await env.DB.prepare('SELECT COUNT(*) AS total FROM organizations').first())?.total||0)}});await writeAudit(env,actor,request,'readiness.isolation','organization',actor.orgId,{status,score});return run;
}

export async function runInvoiceBenchmarkV17(request,env,actor){
  admin(actor);const result=await env.DB.prepare(`SELECT il.review_status,il.match_confidence,il.match_method,il.product_id FROM invoice_lines il JOIN invoices i ON i.id=il.invoice_id WHERE i.org_id=? ORDER BY il.created_at DESC LIMIT 5000`).bind(actor.orgId).all(),items=rows(result),sampleSize=items.length,matched=items.filter(item=>item.product_id&&item.review_status!=='unmatched').length,high=items.filter(item=>Number(item.match_confidence||0)>=.8&&item.product_id).length,medium=items.filter(item=>Number(item.match_confidence||0)>=.55&&Number(item.match_confidence||0)<.8&&item.product_id).length,unmatched=sampleSize-matched,alias=items.filter(item=>String(item.match_method||'').includes('alias')).length,coverage=sampleSize?matched/sampleSize*100:0,quality=sampleSize?(high+medium*.7)/sampleSize*100:0,score=sampleSize?coverage*.65+quality*.35:0,status=sampleSize>=100&&score>=80?'passed':sampleSize>=25&&score>=65?'warning':'failed',run=await recordRun(env,actor,{type:'benchmark',status,score,result:{sampleSize,matched,unmatched,high,medium,alias,coverage:Number(coverage.toFixed(2)),quality:Number(quality.toFixed(2)),targetSample:100,targetScore:80}});await writeAudit(env,actor,request,'readiness.benchmark','invoice_lines',actor.orgId,{status,score,sampleSize});return run;
}

export async function saveOnboardingV17(request,env,actor){
  admin(actor);const body=await readJson(request),business=body.business&&typeof body.business==='object'?body.business:{},branding=body.branding&&typeof body.branding==='object'?body.branding:{},locationInput=body.location&&typeof body.location==='object'?body.location:{},centers=Array.isArray(body.costCenters)?body.costCenters:[],timestamp=nowIso(),organization=await env.DB.prepare('SELECT name,settings_json FROM organizations WHERE id=?').bind(actor.orgId).first(),current=safeJson(organization?.settings_json,{}),name=optionalText(body.organizationName||organization?.name,{max:160})||organization?.name;
  const settings={...current,business:{...(current.business||{}),...business},branding:{...(current.branding||{}),...branding},commercial:{...(current.commercial||{}),supportEmail:optionalText(body.supportEmail||current.commercial?.supportEmail,{max:180}),onboardingCompletedAt:timestamp}};
  await env.DB.prepare('UPDATE organizations SET name=?,settings_json=?,updated_at=? WHERE id=?').bind(name,JSON.stringify(settings),timestamp,actor.orgId).run();
  let location=null;if(locationInput.name){location=locationInput.id?await env.DB.prepare('SELECT id FROM locations WHERE id=? AND org_id=?').bind(String(locationInput.id),actor.orgId).first():await env.DB.prepare('SELECT id FROM locations WHERE org_id=? AND UPPER(name)=UPPER(?)').bind(actor.orgId,String(locationInput.name)).first();if(!location){location={id:uuid()};await env.DB.prepare(`INSERT INTO locations(id,org_id,name,code,timezone,active,details_json,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?,?)`).bind(location.id,actor.orgId,optionalText(locationInput.name,{max:160}),optionalText(locationInput.code,{max:20})||'LOC',optionalText(locationInput.timezone,{max:80})||'America/Santiago',JSON.stringify(locationInput.details||{}),timestamp,timestamp).run()}else await env.DB.prepare('UPDATE locations SET name=?,code=?,timezone=?,details_json=?,active=1,updated_at=? WHERE id=? AND org_id=?').bind(optionalText(locationInput.name,{max:160}),optionalText(locationInput.code,{max:20})||'LOC',optionalText(locationInput.timezone,{max:80})||'America/Santiago',JSON.stringify(locationInput.details||{}),timestamp,location.id,actor.orgId).run()}
  if(location&&centers.length){for(const center of centers){const centerName=optionalText(center.name,{max:120});if(!centerName)continue;const code=optionalText(center.code,{max:30})||centerName.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').slice(0,30),existing=await env.DB.prepare('SELECT id FROM cost_centers WHERE org_id=? AND location_id=? AND (UPPER(name)=UPPER(?) OR UPPER(code)=UPPER(?))').bind(actor.orgId,location.id,centerName,code).first();if(existing)await env.DB.prepare('UPDATE cost_centers SET name=?,code=?,active=1,updated_at=? WHERE id=? AND org_id=?').bind(centerName,code,timestamp,existing.id,actor.orgId).run();else await env.DB.prepare('INSERT INTO cost_centers(id,org_id,location_id,name,code,active,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)').bind(uuid(),actor.orgId,location.id,centerName,code,timestamp,timestamp).run()}}
  await env.DB.prepare(`INSERT INTO onboarding_progress(id,org_id,current_step,completed_json,updated_by,created_at,updated_at) VALUES(?,?,9,?,?,?,?) ON CONFLICT(org_id) DO UPDATE SET current_step=9,completed_json=excluded.completed_json,updated_by=excluded.updated_by,updated_at=excluded.updated_at`).bind(uuid(),actor.orgId,JSON.stringify({business:true,branding:true,location:Boolean(location),centers:centers.length>0,support:true}),actor.userId,timestamp,timestamp).run();
  const subscription=await env.DB.prepare('SELECT id FROM subscriptions WHERE org_id=?').bind(actor.orgId).first();if(!subscription){const trialEnd=new Date(Date.now()+14*86400000).toISOString();await env.DB.prepare(`INSERT INTO subscriptions(id,org_id,provider,plan_code,status,amount,currency,current_period_start,current_period_end,trial_ends_at,cancel_at_period_end,created_at,updated_at) VALUES(?,?,'manual','pro','trialing',0,'CLP',?,?,?,0,?,?)`).bind(uuid(),actor.orgId,timestamp,trialEnd,trialEnd,timestamp,timestamp).run()}
  await writeAudit(env,actor,request,'readiness.onboarding','organization',actor.orgId,{locationId:location?.id||null,centers:centers.length});return{saved:true,locationId:location?.id||null,settings};
}

export async function manageSubscriptionV17(request,env,actor){
  admin(actor);const body=await readJson(request),action=String(body.action||''),subscription=await env.DB.prepare('SELECT * FROM subscriptions WHERE org_id=?').bind(actor.orgId).first();if(!subscription)throw new HttpError(404,'Suscripción no encontrada','subscription_not_found');const timestamp=nowIso();
  if(action==='cancel')await env.DB.prepare('UPDATE subscriptions SET cancel_at_period_end=1,updated_at=? WHERE org_id=?').bind(timestamp,actor.orgId).run();
  else if(action==='resume')await env.DB.prepare('UPDATE subscriptions SET cancel_at_period_end=0,status=CASE WHEN status="cancelled" THEN "active" ELSE status END,updated_at=? WHERE org_id=?').bind(timestamp,actor.orgId).run();
  else if(action==='start_trial'){const end=new Date(Date.now()+14*86400000).toISOString();await env.DB.prepare(`UPDATE subscriptions SET status='trialing',plan_code='pro',trial_ends_at=?,current_period_start=?,current_period_end=?,cancel_at_period_end=0,updated_at=? WHERE org_id=?`).bind(end,timestamp,end,timestamp,actor.orgId).run()}
  else throw new HttpError(400,'Acción de suscripción inválida','invalid_subscription_action');
  await writeAudit(env,actor,request,'billing.manage','subscription',subscription.id,{action});return subscriptionState(env,actor);
}

export async function verifyRecoveryV17(request,env,actor){
  admin(actor);const backup=await env.DB.prepare(`SELECT wb.*,f.storage_key,f.file_name FROM workspace_backups wb LEFT JOIN files f ON f.id=wb.file_id WHERE wb.org_id=? AND wb.status='ready' ORDER BY wb.created_at DESC LIMIT 1`).bind(actor.orgId).first();if(!backup){const run=await recordRun(env,actor,{type:'recovery',status:'failed',score:0,result:{error:'No existe un respaldo listo'}});return run}let parsed=null,calculated='';try{const stored=await readStoredBytes(env,actor,backup.storage_key);calculated=await sha256(stored.bytes);parsed=JSON.parse(new TextDecoder().decode(stored.bytes));const tables=Object.keys(parsed?.tables||parsed?.data||{}),valid=tables.length>0||Array.isArray(parsed?.organizations),checksumOk=!backup.checksum||backup.checksum===calculated,status=valid&&checksumOk?'passed':'warning',score=valid?(checksumOk?100:80):30,run=await recordRun(env,actor,{type:'recovery',status,score,result:{backupId:backup.id,fileName:backup.file_name,checksumExpected:backup.checksum,checksumCalculated:calculated,checksumOk,validJson:true,tableCount:tables.length,rowCount:Number(backup.row_count||0)}});await writeAudit(env,actor,request,'readiness.recovery','backup',backup.id,{status,score});return run}catch(error){const run=await recordRun(env,actor,{type:'recovery',status:'failed',score:0,result:{backupId:backup.id,error:error.message,checksumCalculated:calculated}});await writeAudit(env,actor,request,'readiness.recovery','backup',backup.id,{status:'failed',error:error.message});return run}}

export async function listSupportTicketsV17(env,actor){admin(actor);const result=await env.DB.prepare('SELECT * FROM support_tickets WHERE org_id=? ORDER BY created_at DESC LIMIT 200').bind(actor.orgId).all();return rows(result).map(row=>({id:row.id,subject:row.subject,description:row.description,severity:row.severity,status:row.status,diagnostics:safeJson(row.diagnostics_json,{}),createdAt:row.created_at,updatedAt:row.updated_at,resolvedAt:row.resolved_at}))}
export async function createSupportTicketV17(request,env,actor){const body=await readJson(request),subject=optionalText(body.subject,{max:180});if(!subject)throw new HttpError(400,'Escribe un asunto','missing_subject');const id=uuid(),timestamp=nowIso(),diagnostics=body.diagnostics&&typeof body.diagnostics==='object'?body.diagnostics:{};await env.DB.prepare(`INSERT INTO support_tickets(id,org_id,subject,description,severity,status,diagnostics_json,created_by,created_at,updated_at) VALUES(?,?,?,?,?,'open',?,?,?,?)`).bind(id,actor.orgId,subject,optionalText(body.description,{max:4000}),['low','normal','high','critical'].includes(body.severity)?body.severity:'normal',JSON.stringify(diagnostics),actor.userId,timestamp,timestamp).run();await writeAudit(env,actor,request,'support.create','support_ticket',id,{severity:body.severity||'normal'});return{id,subject,status:'open',createdAt:timestamp}}
export async function updateSupportTicketV17(request,env,actor,ticketId){admin(actor);const body=await readJson(request),status=['open','in_progress','resolved','closed'].includes(body.status)?body.status:null;if(!status)throw new HttpError(400,'Estado inválido','invalid_status');const timestamp=nowIso(),result=await env.DB.prepare('UPDATE support_tickets SET status=?,updated_at=?,resolved_at=CASE WHEN ? IN ("resolved","closed") THEN ? ELSE resolved_at END WHERE id=? AND org_id=?').bind(status,timestamp,status,timestamp,ticketId,actor.orgId).run();if(!Number(result?.meta?.changes||0))throw new HttpError(404,'Ticket no encontrado','not_found');await writeAudit(env,actor,request,'support.update','support_ticket',ticketId,{status});return{id:ticketId,status,updatedAt:timestamp}}

export async function listLegalV17(env,actor){const documents=await env.DB.prepare(`SELECT * FROM legal_documents WHERE org_id=? AND(status='published' OR ? IN ('owner','admin')) ORDER BY document_type,updated_at DESC`).bind(actor.orgId,actor.role).all(),acceptances=await env.DB.prepare('SELECT document_type,version,accepted_at FROM legal_acceptances WHERE org_id=? AND user_id=?').bind(actor.orgId,actor.userId).all();return{documents:rows(documents).map(row=>({id:row.id,type:row.document_type,version:row.version,title:row.title,content:row.content,status:row.status,publishedAt:row.published_at,updatedAt:row.updated_at})),acceptances:rows(acceptances).map(row=>({type:row.document_type,version:row.version,acceptedAt:row.accepted_at}))}}
export async function saveLegalV17(request,env,actor){admin(actor);const body=await readJson(request),type=['terms','privacy','data_processing'].includes(body.type)?body.type:null,version=optionalText(body.version,{max:30}),title=optionalText(body.title,{max:180}),content=optionalText(body.content,{max:50000}),status=body.publish?'published':'draft';if(!type||!version||!title||!content)throw new HttpError(400,'Completa tipo, versión, título y contenido','invalid_legal_document');const timestamp=nowIso(),existing=await env.DB.prepare('SELECT id FROM legal_documents WHERE org_id=? AND document_type=? AND version=?').bind(actor.orgId,type,version).first(),id=existing?.id||uuid();await env.DB.prepare(`INSERT INTO legal_documents(id,org_id,document_type,version,title,content,status,published_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(org_id,document_type,version) DO UPDATE SET title=excluded.title,content=excluded.content,status=excluded.status,published_at=excluded.published_at,updated_at=excluded.updated_at`).bind(id,actor.orgId,type,version,title,content,status,status==='published'?timestamp:null,actor.userId,timestamp,timestamp).run();await writeAudit(env,actor,request,'legal.save','legal_document',id,{type,version,status});return{id,type,version,status,updatedAt:timestamp}}
export async function acceptLegalV17(request,env,actor){const body=await readJson(request),type=String(body.type||''),version=String(body.version||''),document=await env.DB.prepare(`SELECT id FROM legal_documents WHERE org_id=? AND document_type=? AND version=? AND status='published'`).bind(actor.orgId,type,version).first();if(!document)throw new HttpError(404,'Documento legal no encontrado','not_found');const acceptedAt=nowIso();await env.DB.prepare(`INSERT OR IGNORE INTO legal_acceptances(id,org_id,user_id,document_type,version,accepted_at,user_agent) VALUES(?,?,?,?,?,?,?)`).bind(uuid(),actor.orgId,actor.userId,type,version,acceptedAt,optionalText(request.headers.get('User-Agent'),{max:500})).run();await writeAudit(env,actor,request,'legal.accept','legal_document',document.id,{type,version});return{accepted:true,type,version,acceptedAt}}
