from pathlib import Path
import re


def read(path): return Path(path).read_text()
def write(path,text): Path(path).write_text(text)
def must_replace(text, old, new, label, count=1):
    if old not in text: raise SystemExit(f'missing replacement: {label}')
    return text.replace(old,new,count)

def must_regex(text, pattern, repl, label, count=1):
    out,n=re.subn(pattern,repl,text,count=count,flags=re.S)
    if n!=count: raise SystemExit(f'regex {label}: expected {count}, got {n}')
    return out

# Enterprise finance route + authenticated Gemini analysis.
p='professional/worker/src/routes/enterprise.js'; t=read(p)
t=must_replace(t,"'/api/finance/payment-candidates'","'/api/finance/payment-candidates','/api/finance/payment-proof-analysis'",'enterprise route')
write(p,t)

p='professional/worker/src/worker-enterprise.js'; t=read(p)
t=must_replace(t,"import {createPaymentDocumentCanonical,createPaymentDocumentFromInvoiceCanonical,getPaymentDocumentCanonical,listCollectiveChequeScheduleCanonical,listPaymentCandidatesCanonical,listPaymentDocumentsCanonical,updatePaymentDocumentCanonical} from './api/payment-documents.js';","import {createPaymentDocumentCanonical,createPaymentDocumentFromInvoiceCanonical,getPaymentDocumentCanonical,listCollectiveChequeScheduleCanonical,listPaymentCandidatesCanonical,listPaymentDocumentsCanonical,updatePaymentDocumentCanonical} from './api/payment-documents.js';\nimport {analyzePaymentProofCanonical} from './api/payment-proof-ai.js';",'payment proof import')
t=must_replace(t,"if(method==='GET'&&path==='/api/finance/payment-candidates'){const actor=await auth(request,env);return decorate(ok(await listPaymentCandidatesCanonical(env,actor,url),request,env),request,env)}","if(method==='GET'&&path==='/api/finance/payment-candidates'){const actor=await auth(request,env);return decorate(ok(await listPaymentCandidatesCanonical(env,actor,url),request,env),request,env)}\n    if(method==='POST'&&path==='/api/finance/payment-proof-analysis'){const actor=await auth(request,env),body=await request.json().catch(()=>({}));return decorate(ok({analysis:await analyzePaymentProofCanonical(env,actor,body.fileId)},request,env),request,env)}",'payment proof handler')
write(p,t)

# Order detail: first-class payment action, lazy loaded only when used.
p='professional/web/app-order-detail-v30.js'; t=read(p)
t=must_replace(t,"latest=documents.sort((a,b)=>Number(b.revision||0)-Number(a.revision||0))[0],actions=[];","latest=documents.sort((a,b)=>Number(b.revision||0)-Number(a.revision||0))[0],actions=[],paymentRole=['owner','admin','finance'].includes(String(state.me?.user?.role||''));",'detail payment role')
needle="if(!editing&&cap.invoices?.upload&&Number(summary.invoiceCount||0)===0)actions.push('<button class=\"btn primary\" id=\"v30AttachInvoice\">Subir factura</button>');"
t=must_replace(t,needle,needle+"if(!editing&&paymentRole)actions.push('<button class=\"btn primary\" id=\"v30Payment\">Registrar pago</button>');",'detail payment action')
needle="$('#v30AttachInvoice')?.addEventListener('click',attach);$('#v30AttachInvoiceBottom')?.addEventListener('click',attach);"
replacement=needle+"$('#v30Payment')?.addEventListener('click',()=>{if(!invoices.length)return toast('Primero vincula una factura para registrar el pago','error');closeModal('payment');setTimeout(()=>import('./app-payment-workflow.js').then(module=>module.openPaymentForOrder(order.id,{returnView:state.view==='history'?'history':'orders'})).catch(error=>toast(error.message,'error')),0)});"
t=must_replace(t,needle,replacement,'detail payment binding')
write(p,t)

# Payment UX: proof-first, Gemini prefill, manual fields as confirmation/fallback.
p='professional/web/app-payment-workflow.js'; t=read(p)
style_old=".payment-supplier-choice{width:100%;text-align:left}.payment-document-note{padding:10px 12px;border-radius:12px;background:var(--soft);font-size:12px;color:var(--muted)}@media(max-width:720px)"
style_new=".payment-supplier-choice{width:100%;text-align:left}.payment-document-note{padding:10px 12px;border-radius:12px;background:var(--soft);font-size:12px;color:var(--muted)}.payment-proof-first{display:grid;gap:10px;padding:16px;border:1px solid color-mix(in srgb,var(--primary) 28%,var(--line));border-radius:16px;background:color-mix(in srgb,var(--primary) 5%,var(--card));margin-bottom:12px}.payment-proof-first header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.payment-proof-first h3,.payment-proof-first p{margin:0}.payment-proof-first p{margin-top:4px;color:var(--muted);font-size:11px;line-height:1.45}.payment-proof-first input[type=file]{width:100%}.payment-ai-status{min-height:36px;padding:10px 12px;border-radius:12px;background:var(--soft);font-size:11px;color:var(--muted)}.payment-ai-status strong,.payment-ai-status span{display:block}.payment-ai-status strong{color:var(--text);margin-bottom:3px}.payment-ai-status.ok{background:color-mix(in srgb,var(--success) 8%,var(--card));color:var(--text)}.payment-ai-status.warn{background:color-mix(in srgb,var(--warning) 8%,var(--card))}.payment-ai-badge{white-space:nowrap;padding:5px 8px;border-radius:999px;background:var(--card);font-size:9px;font-weight:900;color:var(--primary)}@media(max-width:720px)"
t=must_replace(t,style_old,style_new,'payment proof styles')
upload_line="async function uploadProof(file){if(!(file instanceof File)||!file.size)return'';const form=new FormData();form.append('file',file,file.name);const result=await api('/api/files?purpose=payment-proof',{method:'POST',body:form,timeout:45000,persist:true});return result.file?.id||''}"
assistant_code=r'''async function uploadProof(file){if(!(file instanceof File)||!file.size)return'';const form=new FormData();form.append('file',file,file.name);const result=await api('/api/files?purpose=payment-proof',{method:'POST',body:form,timeout:45000,persist:true});return result.file?.id||''}
function paymentAiSummary(analysis){const parts=[];if(analysis.reference)parts.push(`Operación ${analysis.reference}`);if(Number(analysis.amount||0)>0)parts.push(money(analysis.amount));if(analysis.paymentDate)parts.push(date(analysis.paymentDate));if(analysis.bank||analysis.cheque?.bank)parts.push(analysis.bank||analysis.cheque.bank);if(analysis.recipient||analysis.cheque?.payee)parts.push(`A ${analysis.recipient||analysis.cheque.payee}`);return parts.join(' · ')||'Gemini detectó el medio de pago; revisa los campos antes de confirmar.'}
function setPaymentField(root,name,value){if(value===undefined||value===null||value==='')return;const field=root.querySelector(`[name="${name}"]`);if(field)field.value=String(value)}
function applyPaymentProofAnalysis(root,analysis,methodList){if(!analysis?.detected)throw new Error('Gemini no encontró verificadores de pago legibles en este documento');const method=methodList.find(item=>String(item.kind||'')===String(analysis.methodKind||''));const methodSelect=root.querySelector('#paymentMethod');if(method&&methodSelect){methodSelect.value=method.id;methodSelect.dispatchEvent(new Event('change',{bubbles:true}))}setPaymentField(root,'reference',analysis.reference);setPaymentField(root,'paymentDate',analysis.paymentDate);if(Number(analysis.amount||0)>0){setPaymentField(root,'totalAmount',Math.round(Number(analysis.amount)));const selected=allocationState(root).filter(item=>item.check.checked);if(selected.length===1){selected[0].amount.value=String(Math.min(selected[0].available,Math.round(Number(analysis.amount))));selected[0].amount.disabled=false}}if(analysis.methodKind==='cheque'){setPaymentField(root,'chequeNumber',analysis.cheque?.serialNumber);setPaymentField(root,'chequeCollectionDate',analysis.cheque?.collectionDate);setPaymentField(root,'chequePayee',analysis.cheque?.payee);setPaymentField(root,'chequeAmount',Math.round(Number(analysis.cheque?.amount||analysis.amount||0)));setPaymentField(root,'chequeBank',analysis.cheque?.bank);const status=root.querySelector('[name=status]');if(status)status.value='scheduled'}else if(analysis.paymentDate){const status=root.querySelector('[name=status]');if(status&&status.value!=='disputed')status.value='paid'}const evidence={source:analysis.source||'gemini-payment-proof-v1',methodKind:analysis.methodKind,confidence:Number(analysis.confidence||0),reference:analysis.reference||'',paymentDate:analysis.paymentDate||'',amount:Number(analysis.amount||0),bank:analysis.bank||'',sender:analysis.sender||'',recipient:analysis.recipient||'',accountReference:analysis.accountReference||'',cheque:analysis.cheque||{},warnings:analysis.warnings||[]};root.dataset.paymentProofAnalysis=JSON.stringify(evidence);syncAllocationSummary(root,{forceTotal:false});const statusNode=root.querySelector('[data-payment-ai-status]'),confidence=Math.round(Number(analysis.confidence||0)*100);if(statusNode){statusNode.className='payment-ai-status ok';statusNode.innerHTML=`<strong>Gemini extrajo los verificadores · ${confidence}%</strong><span>${esc(paymentAiSummary(analysis))}</span>${(analysis.warnings||[]).length?`<span>${esc((analysis.warnings||[]).join(' · '))}</span>`:''}`}}
async function analyzePaymentProofFile(file,root,methodList){const status=root.querySelector('[data-payment-ai-status]');if(status){status.className='payment-ai-status';status.innerHTML='<strong>Leyendo comprobante con Gemini…</strong><span>No necesitas copiar manualmente el número de operación, fecha, monto o serie del cheque.</span>'}try{const fileId=await uploadProof(file);if(!fileId)throw new Error('No se pudo guardar el comprobante');root.dataset.paymentProofFileId=fileId;const payload=await api('/api/finance/payment-proof-analysis',{method:'POST',json:{fileId},timeout:75000});applyPaymentProofAnalysis(root,payload.analysis||{},methodList);return payload.analysis}catch(error){if(status){status.className='payment-ai-status warn';status.innerHTML=`<strong>No se pudo completar la lectura automática</strong><span>${esc(error.message)}. Puedes confirmar los datos manualmente y guardar el mismo comprobante.</span>`}return null}}
function bindPaymentProofAssistant(root,methodList){const input=root.querySelector('#paymentProofFile');if(!input)return;input.addEventListener('change',()=>{const file=input.files?.[0];root.dataset.paymentProofFileId='';root.dataset.paymentProofAnalysis='';if(!file)return;root._paymentProofPromise=analyzePaymentProofFile(file,root,methodList).finally(()=>{root._paymentProofPromise=null})})}'''
t=must_replace(t,upload_line,assistant_code,'payment ai helpers')
composer=t.find('export async function openPaymentDocumentComposer')
if composer<0: raise SystemExit('missing composer')
prefix=t[:composer]; tail=t[composer:]
old_intro="body:`<div class=\"payment-document-note\">Selecciona las facturas que cubre este documento. Puedes combinar varias facturas del mismo pedido o facturas de distintos pedidos, siempre del mismo proveedor.</div>"
new_intro="body:`<section class=\"payment-proof-first\"><header><div><h3>1 · Adjunta el comprobante</h3><p>Gemini leerá automáticamente medio de pago, número de operación, fecha, monto, banco y los datos del cheque cuando corresponda.</p></div><span class=\"payment-ai-badge\">IA</span></header><label class=\"field\"><span>Comprobante de pago</span><input id=\"paymentProofFile\" name=\"proof\" type=\"file\" accept=\"application/pdf,image/*\"></label><div class=\"payment-ai-status\" data-payment-ai-status><strong>Listo para analizar</strong><span>Adjunta una imagen o PDF. Los campos manuales quedan como confirmación y respaldo.</span></div></section><div class=\"payment-document-note\">2 · Selecciona las facturas que cubre este comprobante. Pueden ser varias, siempre del mismo proveedor.</div>"
tail=must_replace(tail,old_intro,new_intro,'proof first intro')
proof_label='<label class="field"><span>Comprobante</span><input name="proof" type="file" accept="application/pdf,image/*"></label>'
tail=must_replace(tail,proof_label,'','remove duplicate proof input')
tail=must_replace(tail,"const proofFileId=await uploadProof(form.get('proof')),isCheque=method.kind==='cheque'","if(root._paymentProofPromise)await root._paymentProofPromise;const proofFileId=root.dataset.paymentProofFileId||await uploadProof(form.get('proof')),isCheque=method.kind==='cheque'",'reuse analyzed proof')
tail=must_replace(tail,"note:form.get('note'),allocations,...(proofFileId?{proofFileId}:{})","note:form.get('note'),allocations,source:root.dataset.paymentProofAnalysis?'ai-reviewed':'manual',metadata:root.dataset.paymentProofAnalysis?{aiProof:JSON.parse(root.dataset.paymentProofAnalysis)}:{},...(proofFileId?{proofFileId}:{})",'persist ai evidence')
tail=must_replace(tail,"const root=$('#modalBody')||document;bindMethodFields(root);bindAllocationUI(root);","const root=$('#modalBody')||document;bindMethodFields(root);bindAllocationUI(root);bindPaymentProofAssistant(root,methodList);",'bind proof assistant')
t=prefix+tail
write(p,t)

# Consolidate category/product/route navigation into one catalog flow.
p='professional/web/app-experience-admin.js'; t=read(p)
t=must_replace(t,"function setActive(){$$('.nav-item[data-view],.bottom-item[data-view],.nav-item[data-experience-view],.bottom-item[data-experience-view]').forEach(button=>button.classList.toggle('active',(button.dataset.experienceView||button.dataset.view)==='operations'));$('#pageEyebrow').textContent='MAESTROS';$('#pageTitle').textContent='Operaciones'}","function setActive(){$$('.nav-item[data-view],.bottom-item[data-view],.nav-item[data-experience-view],.bottom-item[data-experience-view]').forEach(button=>button.classList.toggle('active',(button.dataset.experienceView||button.dataset.view)==='operations'));$('#pageEyebrow').textContent='CATÁLOGO';$('#pageTitle').textContent='Catálogo y recorrido'}",'operations title')
t=must_regex(t,r"function homePanel\(counts\)\{.*?\}\nfunction subHeader", "function homePanel(counts){const cards=[['products','▦','Catálogo y recorrido','Productos, categorías, centros, bodegas, unidades y orden de Lista Maestra en un solo flujo.',counts.products],['suppliers','◇','Proveedores','Datos de abastecimiento, productos vinculados e identidad visual.',counts.suppliers]];return `<section class=\"operations-home-grid\">${cards.map(([tab,icon,title,detail,total])=>`<button class=\"operations-home-card\" type=\"button\" data-operations-tab=\"${tab}\"><span>${icon}</span><div><strong>${title}</strong><p>${detail}</p><small>${total} registrado${total===1?'':'s'}</small></div><b>→</b></button>`).join('')}</section>`}\nfunction subHeader",'operations home')
t=must_replace(t,"function subHeader(title,detail){return `<div class=\"operations-subhead\"><button class=\"btn\" type=\"button\" data-operations-back>← Operaciones</button><div><h2>${title}</h2><p>${detail}</p></div></div>`}","function subHeader(title,detail){return `<div class=\"operations-subhead\"><button class=\"btn\" type=\"button\" data-operations-back>← Catálogo</button><div><h2>${title}</h2><p>${detail}</p></div></div>`}\nfunction catalogNav(active){return `<div class=\"view-actions\" style=\"margin:0 0 12px;justify-content:flex-start;flex-wrap:wrap\"><button class=\"btn ${active==='products'?'primary':''}\" type=\"button\" data-operations-tab=\"products\">Productos</button><button class=\"btn ${active==='categories'?'primary':''}\" type=\"button\" data-operations-tab=\"categories\">Categorías</button><button class=\"btn ${active==='centers'?'primary':''}\" type=\"button\" data-operations-tab=\"centers\">Bodegas y recorrido</button></div>`}", 'catalog nav')
t=must_replace(t,"return `${subHeader('Categorías','Cada categoría pertenece a un centro. Aquí no se ordenan: el orden se define dentro de cada bodega.')}<section", "return `${subHeader('Catálogo y recorrido','Las categorías son parte del mismo flujo que productos, bodegas y orden de Lista Maestra.')}${catalogNav('categories')}<section",'category grouped')
t=must_replace(t,"return `${subHeader('Productos','Cada producto puede estar disponible en uno o varios centros de costo.')}<section", "return `${subHeader('Catálogo y recorrido','Configura productos y luego continúa con categorías y recorrido sin salir de este módulo.')}${catalogNav('products')}<section",'product grouped')
t=must_replace(t,"return `${subHeader('Centros y bodegas','Aquí se define el orden de unidades, bodegas y categorías que se verá en la lista maestra.')}<section", "return `${subHeader('Catálogo y recorrido','Este es el paso final del catálogo: unidades, bodegas, categorías y orden visible en Lista Maestra.')}${catalogNav('centers')}<section",'center grouped')
t=must_replace(t,"<span class=\"eyebrow\">CONFIGURACIÓN OPERATIVA</span><h2>Operaciones</h2><p>Entra a un menú, trabaja y vuelve exactamente al punto anterior.</p>","<span class=\"eyebrow\">CATÁLOGO Y ABASTECIMIENTO</span><h2>Catálogo y recorrido</h2><p>Productos, categorías y recorrido se configuran como un solo sistema. Proveedores queda como módulo relacionado.</p>",'operations header')
write(p,t)

# Settings is now a directory, not a competing editor for master traversal.
p='professional/web/app-experience-settings.js'; t=read(p)
old="<section class=\"settings-section\"><div class=\"settings-section-head\"><div><h3>Operación y datos maestros</h3><p>Categorías, productos, proveedores, centros, bodegas y logos.</p></div></div><div class=\"settings-menu-grid\">${card('⚙','Operaciones','Crea categorías propias, asigna productos y administra logos.','data-experience-view=\"operations\"','Abrir operaciones')}${card('▤','Lista maestra y bodegas','Configura unidades, bodegas y recorrido por centro.','data-scroll-settings=\"procurementAdminPanel\"','Elegir centro')}</div></section>"
new="<section class=\"settings-section\"><div class=\"settings-section-head\"><div><h3>Catálogo y abastecimiento</h3><p>Una sola entrada para productos, categorías, bodegas, recorrido y proveedores.</p></div></div><div class=\"settings-menu-grid\">${card('▦','Catálogo y recorrido','Configura productos, categorías, bodegas, unidades y orden de Lista Maestra en un único flujo.','data-experience-view=\"operations\"','Configurar catálogo')}</div></section>"
t=must_replace(t,old,new,'settings catalog card')
t=must_regex(t,r"\n    <section class=\"settings-section\" id=\"procurementAdminPanel\">.*?</section>","",'remove duplicate settings route')
write(p,t)

# Master-data remains lifecycle maintenance, and points edits to the canonical catalog surface.
p='professional/web/app-procurement.js'; t=read(p)
t=must_replace(t,"<h2>Maestro de datos</h2><p>Administra productos, categorías, proveedores, centros y locales sin destruir historial. Deshabilita, reactiva, edita por lote o fusiona duplicados.</p></div><div class=\"v44-head-actions\"><button class=\"btn\" id=\"v44GoOperations\">Bodegas, unidades y recorrido</button>","<h2>Mantenimiento de datos</h2><p>Deshabilita, reactiva, edita por lote o fusiona duplicados sin destruir historial. La configuración funcional vive en Catálogo y recorrido.</p></div><div class=\"v44-head-actions\"><button class=\"btn primary\" id=\"v44GoOperations\">Configurar catálogo y recorrido</button>",'masterdata purpose')
t=must_replace(t,"$('#v44GoOperations').onclick=()=>openRoute('operations','home')","$('#v44GoOperations').onclick=()=>openRoute('operations','products')",'masterdata canonical link')
write(p,t)

# Catalog provides a clear admin bridge to the same configuration owner.
p='professional/web/app-catalog.js'; t=read(p)
old="<p>Administra fotografías, categorías, formatos y múltiples proveedores por producto. En Matriz puedes habilitar o deshabilitar vínculos directamente.</p></div></header>"
new="<p>Consulta fotografías, formatos y múltiples proveedores por producto. La estructura y el recorrido se configuran en un único módulo.</p></div><button class=\"btn primary\" id=\"v32CatalogConfig\" type=\"button\">Configurar catálogo y recorrido</button></header>"
t=must_replace(t,old,new,'catalog config bridge')
t=must_replace(t,"$('#v32CatalogSearch').oninput=()=>render(false);","$('#v32CatalogConfig')?.addEventListener('click',()=>openRoute('operations','products'));$('#v32CatalogSearch').oninput=()=>render(false);",'catalog bridge binding')
write(p,t)

# Release and capability markers.
p='professional/worker/src/router.js'; t=read(p)
t=must_replace(t,"const VERSION='76';","const VERSION='77';",'router version')
t=must_replace(t,"const RELEASE='2026.08.14.76';","const RELEASE='2026.08.14.77';",'router release')
t=must_replace(t,"supplierInvoiceProfilesV76:true,nativePerformanceV45:true","supplierInvoiceProfilesV76:true,paymentProofGeminiV77:true,orderDetailPaymentsV77:true,catalogFlowConsolidationV77:true,nativePerformanceV45:true",'r77 health')
write(p,t)
p='worker/src/combined.js'; t=read(p);t=must_replace(t,"const PLATFORM_RELEASE='2026.08.14.76';","const PLATFORM_RELEASE='2026.08.14.77';",'combined release');write(p,t)
p='professional/web/app.js'; t=read(p);t=must_replace(t,"CLIENT_RELEASE='2026.08.14.76'","CLIENT_RELEASE='2026.08.14.77'",'client release');write(p,t)
p='professional/web/sw.js'; t=read(p);t=must_replace(t,'nuvasto-v76-supplier-final-unit','nuvasto-v77-payment-proof-ops','service worker release');write(p,t)

# Contract tests cover the actual regression and the IA-first proof flow.
p='professional/tests/functional-contracts.test.mjs'; t=read(p)
t=must_replace(t,"selection=read('web/app-order-selection.js'),multiInvoice=read('web/app-multi-invoice.js'),aiWorker=read('../worker/src/index.js');","selection=read('web/app-order-selection.js'),multiInvoice=read('web/app-multi-invoice.js'),aiWorker=read('../worker/src/index.js'),orderDetail=read('web/app-order-detail-v30.js'),paymentProofAi=read('worker/src/api/payment-proof-ai.js'),experienceAdmin=read('web/app-experience-admin.js'),experienceSettings=read('web/app-experience-settings.js');",'test reads')
insert="""assert.ok(orderDetail.includes('id=\\\"v30Payment\\\"')&&orderDetail.includes("import('./app-payment-workflow.js')")&&orderDetail.includes('openPaymentForOrder'),'order detail must expose the canonical payment flow without preloading finance code');
assert.ok(paymentWorkflow.includes('paymentProofFile')&&paymentWorkflow.includes('/api/finance/payment-proof-analysis')&&paymentWorkflow.includes('Gemini extrajo los verificadores')&&paymentWorkflow.includes("source:root.dataset.paymentProofAnalysis?'ai-reviewed':'manual'"),'payment documents must be proof-first and persist Gemini-reviewed verifier evidence');
assert.ok(paymentProofAi.includes('analyzePaymentProofCanonical')&&paymentProofAi.includes('número de operación')&&paymentProofAi.includes('serialNumber')&&paymentProofAi.includes('Jamás inventes verificadores'),'authenticated Gemini payment proof analysis must extract transfer and cheque verifiers without invention');
assert.ok(enterpriseRoutes.includes("'/api/finance/payment-proof-analysis'")&&workerEnterprise.includes("path==='/api/finance/payment-proof-analysis'"),'payment proof AI must remain behind authenticated enterprise finance routing');
assert.ok(experienceAdmin.includes('Catálogo y recorrido')&&experienceAdmin.includes("catalogNav('products')")&&experienceAdmin.includes("catalogNav('categories')")&&experienceAdmin.includes("catalogNav('centers')"),'products, categories and traversal must share one catalog configuration surface');
assert.ok(experienceSettings.includes('Configurar catálogo')&&!experienceSettings.includes('id=\\\"procurementAdminPanel\\\"'),'Settings must link to the canonical catalog flow instead of duplicating traversal configuration');
assert.ok(router.includes('paymentProofGeminiV77:true')&&router.includes('orderDetailPaymentsV77:true')&&router.includes('catalogFlowConsolidationV77:true'),'r77 health must expose payment proof AI and catalog-flow consolidation');
"""
t=must_replace(t,"assert.ok(sw.includes('nuvasto-v76-supplier-final-unit')&&!sw.includes(\"'./app-procurement.js'\")&&!sw.includes(\"'./app-enterprise.js'\"),'service worker install must cut over stale invoice UI while keeping feature bundles out of critical precache');", "assert.ok(sw.includes('nuvasto-v77-payment-proof-ops')&&!sw.includes(\"'./app-procurement.js'\")&&!sw.includes(\"'./app-enterprise.js'\"),'service worker install must cut over stale finance/catalog UI while keeping feature bundles out of critical precache');\n"+insert.rstrip(), 'functional r77 checks')
write(p,t)

# Production smoke follows the canonical release and checks the new detail/payment assets.
p='professional/tests/production-e2e-v44.mjs'; t=read(p)
t=must_replace(t,"const [releaseText,healthText,appText,bootstrapText,authText,sessionText,legalText,entryText,routerText,masterText,ordersText,selectionText,documentsText,paymentText,invoiceText,runtimeText,nativeText,swText]=await Promise.all([publicText('/platform/release'),publicText('/platform/health'),publicText('/app.js'),publicText('/app-bootstrap.js'),publicText('/app-auth-experience.js'),publicText('/app-session-bootstrap.js'),publicText('/app-legal.js'),publicText('/app-order-core.js'),publicText('/app-router-v14.js'),publicText('/app-master-order.js'),publicText('/app-orders.js'),publicText('/app-order-selection.js'),publicText('/app-documents.js'),publicText('/app-payment-workflow.js'),publicText('/app-invoice-v30.js'),publicText('/app-runtime-v30.js'),publicText('/native-performance.css'),publicText('/sw.js')]);","const [releaseText,healthText,appText,bootstrapText,authText,sessionText,legalText,entryText,routerText,masterText,ordersText,selectionText,documentsText,paymentText,detailText,invoiceText,runtimeText,nativeText,swText]=await Promise.all([publicText('/platform/release'),publicText('/platform/health'),publicText('/app.js'),publicText('/app-bootstrap.js'),publicText('/app-auth-experience.js'),publicText('/app-session-bootstrap.js'),publicText('/app-legal.js'),publicText('/app-order-core.js'),publicText('/app-router-v14.js'),publicText('/app-master-order.js'),publicText('/app-orders.js'),publicText('/app-order-selection.js'),publicText('/app-documents.js'),publicText('/app-payment-workflow.js'),publicText('/app-order-detail-v30.js'),publicText('/app-invoice-v30.js'),publicText('/app-runtime-v30.js'),publicText('/native-performance.css'),publicText('/sw.js')]);",'production detail asset')
t=must_replace(t,"assert.equal(health.multiOrderPaymentV74,true,'health must support multiple orders per payment');","assert.equal(health.multiOrderPaymentV74,true,'health must support multiple orders per payment');assert.equal(health.paymentProofGeminiV77,true,'health must expose Gemini payment proof extraction');assert.equal(health.orderDetailPaymentsV77,true,'health must expose order-detail payment action');assert.equal(health.catalogFlowConsolidationV77,true,'health must expose consolidated catalog traversal');",'production health r77')
t=must_replace(t,"assert.ok(paymentText.includes('openPaymentDocumentComposer')&&paymentText.includes('openCollectivePayment')&&paymentText.includes('/api/finance/payment-documents')&&paymentText.includes('/api/finance/payment-candidates')&&paymentText.includes('Solo este pedido')&&paymentText.includes('Todo el proveedor')&&paymentText.includes('openPaymentMethodsManager')&&paymentText.includes('Cobros programados'),'unitary and collective payment document asset');","assert.ok(paymentText.includes('openPaymentDocumentComposer')&&paymentText.includes('openCollectivePayment')&&paymentText.includes('/api/finance/payment-documents')&&paymentText.includes('/api/finance/payment-candidates')&&paymentText.includes('/api/finance/payment-proof-analysis')&&paymentText.includes('paymentProofFile')&&paymentText.includes('Solo este pedido')&&paymentText.includes('Todo el proveedor')&&paymentText.includes('openPaymentMethodsManager')&&paymentText.includes('Cobros programados'),'unitary, collective and Gemini-assisted payment document asset');assert.ok(detailText.includes('v30Payment')&&detailText.includes('openPaymentForOrder'),'order detail payment action asset');",'production payment checks')
write(p,t)

print('payment proof + operations consolidation patch applied')
